### ISSUE TITLE
Missing file "lib/ssl/Makefile.in"

### ISSUE THREAD

**Issue by sray256** [facebook/proxygen#102]
How I reproduce the issue on Ubuntu 16.04:

git clone git@github.com:facebook/proxygen.git
cd proxygen/proxygen
./deps.sh

Here is the relevant part of the output:

libtoolize: copying file 'm4/lt~obsolete.m4'
libtoolize: Consider adding '-I m4' to ACLOCAL_AMFLAGS in Makefile.am.
libtoolize: 'AC_PROG_RANLIB' is rendered obsolete by 'LT_INIT'
autoreconf: running: /usr/bin/autoconf --force
autoreconf: running: /usr/bin/autoheader --force
autoreconf: running: automake --add-missing --copy --force-missing
configure.ac:23: installing 'build-aux/compile'
configure.ac:17: installing 'build-aux/missing'
configure.ac:237: error: required file 'lib/ssl/Makefile.in' not found
httpclient/samples/curl/Makefile.am: installing 'build-aux/depcomp'
autoreconf: automake failed with exit status: 1

Removing line 242 in configure.ac allows deps.sh and reinstall.sh to run successfully. The line seems to reference a directory ("lib/ssl") that was removed in commit c60ec2f1c9da645f6b18346703ac15d8bb85a79c.

**Comment by afrind** [comment]
My bad.  I’ll fix it if someone hasn’t already beat me to it.

**Comment by afrind** [comment]
should be better now
