### ISSUE TITLE
Multipart form parser

### ISSUE THREAD

**Issue by Dionis-mgn** [facebook/proxygen#103]
Hi!

Is there any mechanism to parse multipart forms/other data? It looks like the only way is too use my own(or 3d-party) library. It made me very upset and a little bit annoys me =(.

Maybe I am missing something?

Thanks.

**Comment by ustczxf** [comment]
I encountered the same issue with you:(

**Comment by w-o-o** [comment]
can you attach a test case or instruction to reproduce this issue?  I can take a look at it

**Comment by afrind** [comment]
I landed a parser for this under experimental.  It's never been used in production so let me know if you encounter any issues.

**Comment by keithmendozasr** [comment]
My apologies for reviving a closed issue. Unfortunately, I'm not having much luck in figuring out how I can use the RFC1827 class to handle the POST body messages. I attempted to find where/when HTTP1xCodec class is called/used exactly; however, I'm not having any luck keeping track of the trail. Looking at RFC1827 class, I get the impression that I should replace HTTP1xCodec in cases that I want the POST body parsed. I'm not sure if this is even the right way to do it.
