### ISSUE TITLE
HTTP Client SSL Request

### ISSUE THREAD

**Issue by daemonSlayer** [facebook/proxygen#105]
I am trying to use the HTTP client in order to be able to send secure requests (SSL/TLS). Using the sample client in the library, I am not being able to complete the request. The request requires HTTP 1.1. 
After compiling the httpclient sample, using these string values :
```
DEFINE_string(http_method, "GET",
    "HTTP method to use. GET or POST are supported");
DEFINE_string(url, "https://www.google.com",
    "URL to perform the HTTP method against");
DEFINE_string(input_filename, "/home/cortana/Desktop/audio_16k16bit.spx",
    "Filename to read from for POST requests");
DEFINE_int32(http_client_connect_timeout, 1000,
    "connect timeout in milliseconds");
DEFINE_string(cert_path, "/etc/ssl/certs/ca-certificates.crt",
    "Path to trusted cert to authenticate with");  // default for Ubuntu 14.04
DEFINE_string(next_protos, "h2,h2-14,spdy/3.1,spdy/3,http/1.1",
    "Next protocol string for NPN/ALPN");
DEFINE_string(plaintext_proto, "", "plaintext protocol");
DEFINE_int32(recv_window, 65536, "Flow control receive window for h2/spdy");
DEFINE_string(headers, "", "List of N=V headers separated by ,"); 

```
I get this as log output : 
```
E0726 11:07:53.822340 11833 AsyncSSLSocket.cpp:131] client handshakeErr: AsyncSocketException: SSL connect timed out, type = Timed out
E0726 11:07:53.822931 11833 CurlClient.cpp:140] Coudln't connect to www.google.com:443:AsyncSocketException: SSL connect timed out, type = Timed out
```

What should I do to remove this problem ? I have tried to check the wireshark output to see if there were any network problems, and I couldn't find anything. Also, I have tried to send a curl request, which is always successful.

**Comment by anirudhvr** [comment]
The curl_client in master works fine for me with just -cert_path and -url.  Are you behind an HTTP proxy or have another reason why the direct connection wouldn't work? Can you confirm that curl and/or wget work to these urls without any proxy specification (e.g., http_proxy environment variable, or a setting in ~/.wgetrc or ~/.curlrc). 

If curl/wget works, you may want to try increasing connect_timeout

**Comment by daemonSlayer** [comment]
Thanks a lot. I just needed to increase the connect_timeout value.
