### ISSUE TITLE
Server & Client duplicate singleton registration of folly::Singleton proxygen::SharedWheelTimer

### ISSUE THREAD

**Issue by suspend0** [facebook/proxygen#107]
First, thanks very much for releasing proxygen.  It's been a fantastic building block for us.  We really appreciate it.  I'm running into trouble trying to use proxygen sample client code inside a binary which runs proxygen::HTTPServer.

To produce a similar error, apply the following patch:

```
$ git diff Makefile.am
diff --git a/proxygen/httpclient/samples/curl/Makefile.am b/proxygen/httpclient/samples/curl/Makefile
index 6cbeaab..d3024e8 100644
--- a/proxygen/httpclient/samples/curl/Makefile.am
+++ b/proxygen/httpclient/samples/curl/Makefile.am
@@ -11,7 +11,8 @@ libproxygencurl_la_SOURCES = \

 libproxygencurl_la_LIBADD = \
         ../../../lib/libproxygenlib.la \
-       ../../../lib/http/libproxygenhttp.la
+       ../../../lib/http/libproxygenhttp.la \
+       ../../../httpserver/libproxygenhttpserver.la

 libproxygencurl_la_LDFLAGS=-static
```

After a successful build & link (had to `make clean` to pickup changes), the following error:

```
$ ./curl
Double registration of singletons of the same underlying type; check for multiple definitions of type folly::Singleton<proxygen::SharedWheelTimer>
Aborted (core dumped)
```

The above exposes the symptom but isn't very useful.  The symptom in my build is the following:
- If linking to `libproxygenhttpserver`, there's an undefined reference to `proxygen::HTTPUpstreamSession`
- If linking to `libproxygenlib`, there's an undefined reference to `proxygen::HTTPServer`
- If linking to both, the error with double registration of `proxygen::SharedWheelTimer`
- Note the proxgen .deb file does not include `libproxygenhttp`, so I haven't included that in my tests.

I hope that this is sensible on some level.  Thank you for your attention.
-dg

**Comment by suspend0** [comment]
The revision of proxygen I tested is a674e99561404730487256e5f889485d47c3d8c9 (approx 8 commits back)

**Comment by abhiguru** [comment]
did you figure out what was the reason ?

**Comment by abhiguru** [comment]
I had to build HTTPServer from source as a part of my code and just using the libproxygenlib.a as an input lib to get around this issue, was really trying to avoid doing that... using CMake

**Comment by suspend0** [comment]
The reason is b/c proxygen httpserver & proxygen client code wasn't designed to work in the same binary.  This may be reasonable choice by the authors of the library but it surprised me.

To work around I wrote my own client based on libcurl.

**Comment by afrind** [comment]
The code should be able to work in the same binary.  We’ll try to fix this.

**Comment by psetevik** [comment]
Any progress on this ? Getting affected  by the same issue. Have a simple HTTPServer-based server (simple copy/edit of stock EchoHandler/EchoServer) and when I try to use any timer-related functionality on HTTPTransaction (ie txn_->setIdleTimeout(..), I get the dreaded:


Double registration of singletons of the same underlying type; check for multiple definitions of type folly::Singleton<N8proxygen16SharedWheelTimerE>

Both Folly and Proxygen are compiled from github exports that are  few days old

**Comment by afrind** [comment]
So I just built a simple proxy server sample starting from the Echo sample, and adding code *like* the curl client, though not directly copy/pasting it.  I didn't have any HHWheelTimer issues.  I will try to get this shipped soon but it's probably early next week.  How I handled the HHWheelTimer required by HTTPConnector was to create one per-thread (using folly::ThreadLocal) inside my handler factory, from onServerStart.  Then I pass this per-thread wheel timer into the request handler at construction time, and pass it to HTTPConnector from there:

```
class ProxyHandlerFactory : public RequestHandlerFactory {
 public:
  void onServerStart(folly::EventBase* evb) noexcept override {
    stats_.reset(new ProxyStats);
    timer_->timer = HHWheelTimer::newTimer(
      evb,
      std::chrono::milliseconds(HHWheelTimer::DEFAULT_TICK_INTERVAL),
      folly::AsyncTimeout::InternalEnum::NORMAL,
      std::chrono::seconds(FLAGS_server_timeout));
  }

  void onServerStop() noexcept override {
    stats_.reset();
    timer_->timer.reset();
  }

  RequestHandler* onRequest(RequestHandler*, HTTPMessage*) noexcept override {
    return new ProxyHandler(stats_.get(), timer_->timer.get());
  }

 private:
  struct TimerWrapper {
    HHWheelTimer::UniquePtr timer;
  };
  folly::ThreadLocalPtr<ProxyStats> stats_;
  folly::ThreadLocal<TimerWrapper> timer_;
};
```
...

```
ProxyHandler::ProxyHandler(ProxyStats* stats, folly::HHWheelTimer* timer):
    stats_(stats),
    connector_{this, timer},
    serverHandler_(*this) {
}
```

Let me know if something like that works for you.

**Comment by abhiguru** [comment]
If the handler does a HTTPCurlClient call with a runInEventBaseThread using the evb that was passed in onServerStart(assuming it is passed into the handler) can it use the timer or should it use a separate timer?

**Comment by afrind** [comment]
There should generally only be one timer per thread, associated with an evb, and the timer is not thread safe.  But if I understand your question correctly, you have something like:

```
...from handler code:
evb_->runInEventBaseThread([timer_] { do something with timer })

```

This is ok, but it Is actually overkill, since the handler code is already in the event base thread.  You can just do:

`evb->runInLoop([timer_] { do something with timer });`

**Comment by abhiguru** [comment]
got it that("overkill...") clears up some of the confusion

**Comment by psetevik** [comment]
Thanks for looking into it.

The IO Worker thread (one that "receives" inbound requests) already has an EventBase, along with HHWheelTimer that is "ticked" by that EventBase (as managing TOs for inbound ManagedConnections/HTTPSessions/Transactions requires a HHWheelTimer ).

It makes sense to use same  EventBase and its HHWheelTimer object for outbound Sessions/Transactions as well. EventBase has a static getter that returns thread-specific evb. HHWheelTimer  is pretty heavy (as per PG's own comments).

In general, the RequestHandler begs for access to its underlying HttpTransaction, as otherwise, the capabilities are seriously dumbed-down. For example, no way to affect the TO (a virtual must in proxy application), no access to parent HTTPSession (ditto).

I understand the motivation for removing ability to shoot self in the foot :) - otherwise, PG team's life would be living hell @ FB.

**Comment by afrind** [comment]
Yes I noticed there was already an HHWheelTimer inside wangle/acceptor/ConnectionManager.  This used to be an AsyncTimeoutSet (lightweight) but was converted to an HHWheelTimer without thinking about the weight or how best to share that one.  I filed an issue internally to try to clean that up.

The SharedWheelTimer is a global map of evb to WheelTimers.  We've had issues internally with different users of HHWheelTimer on how to reflect shared ownership, and this was one attempt to resolve it.

As for exposing the underlying HTTPTransaction and HTTPSession in HTTPServer, that is mostly orthogonal to this thread, so let's take it up (either as an issue or a discussion thread in the google group).

**Comment by abhiguru** [comment]
@afrind I tried runInLoop as suggested instead of runInEventBaseThread but it throws an exception Check failed: isInEventBaseThread() I posted a version of the code in the gist below 

https://gist.github.com/abhiguru/68041ef47969bb63b7a375aee99d1c93

**Comment by afrind** [comment]
Ok, I think the sample shows how to use one timer per thread and prevent the issue described.
