### ISSUE TITLE
GMock dependency is broken

### ISSUE THREAD

**Issue by mlabour** [facebook/proxygen#112]
==> default: wget https://googlemock.googlecode.com/files/gmock-1.7.0.zip
==> default: --2016-08-31 19:17:04--  https://googlemock.googlecode.com/files/gmock-1.7.0.zip
==> default: Resolving googlemock.googlecode.com (googlemock.googlecode.com)... 
==> default: 173.194.195.82, 2607:f8b0:4001:c0c::52
==> default: Connecting to googlemock.googlecode.com (googlemock.googlecode.com)|173.194.195.82|:443... 
==> default: connected.
==> default: HTTP request sent, awaiting response... 
==> default: 404 Not Found
==> default: 2016-08-31 19:17:09 ERROR 404: Not Found.
==> default: make[3]:

**Comment by anirudhvr** [comment]
gmock has been moved to the googletest repo. The change would be to pull from https://github.com/google/googletest/googlemock. PR for wangle which fixed this: https://github.com/facebook/wangle/pull/60. cc: @lanxi

**Comment by lanxi** [comment]
Thank you! Pull request https://github.com/facebook/proxygen/pull/113 has been created to update the dependency.
