### ISSUE TITLE
make aborts when compiling AsyncTimeoutSet.cpp

### ISSUE THREAD

**Issue by mlabour** [facebook/proxygen#115]
==> default: In file included from /usr/local/include/folly/io/async/Request.h:27:0,
==> default:                  from AsyncTimeoutSet.cpp:14:
==> default: /usr/local/include/folly/Synchronized.h:157:37: error: 'withWLock' function uses 'auto' type specifier without trailing return type
==> default:    auto withWLock(Function&& function) {
==> default:                                      ^
==> default: /usr/local/include/folly/Synchronized.h:157:37: note: deduced return type only available with -std=c++14 or -std=gnu++14
==> default: /usr/local/include/folly/Synchronized.h:163:39: error: 'withWLock' function uses 'auto' type specifier without trailing return type
==> default:    auto withWLock(Function&& function) const {
==> default:                                        ^
==> default: /usr/local/include/folly/Synchronized.h:163:39: note: deduced return type only available with -std=c++14 or -std=gnu++14
==> default: /usr/local/include/folly/Synchronized.h:179:40: error: 'withWLockPtr' function uses 'auto' type specifier without trailing return type
==> default:    auto withWLockPtr(Function&& function) {
==> default:                                         ^
==> default: /usr/local/include/folly/Synchronized.h:179:40: note: deduced return type only available with -std=c++14 or -std=gnu++14
==> default: /usr/local/include/folly/Synchronized.h:183:42: error: 'withWLockPtr' function uses 'auto' type specifier without trailing return type
==> default:    auto withWLockPtr(Function&& function) const {
==> default:                                           ^
==> default: /usr/local/include/folly/Synchronized.h:183:42: note: deduced return type only available with -std=c++14 or -std=gnu++14
==> default: /usr/local/include/folly/Synchronized.h:194:39: error: 'withRLock' function uses 'auto' type specifier without trailing return type
==> default:    auto withRLock(Function&& function) const {
==> default:                                        ^
==> default: /usr/local/include/folly/Synchronized.h:194:39: note: deduced return type only available with -std=c++14 or -std=gnu++14
==> default: /usr/local/include/folly/Synchronized.h:201:42: error: 'withRLockPtr' function uses 'auto' type specifier without trailing return type
==> default:    auto withRLockPtr(Function&& function) const {
==> default:                                           ^
==> default: /usr/local/include/folly/Synchronized.h:201:42: note: deduced return type only available with -std=c++14 or -std=gnu++14
==> default: /usr/local/include/folly/Synchronized.h:275:39: error: 'withULock' function uses 'auto' type specifier without trailing return type
==> default:    auto withULock(Function&& function) const {
==> default:                                        ^
==> default: /usr/local/include/folly/Synchronized.h:275:39: note: deduced return type only available with -std=c++14 or -std=gnu++14
==> default: /usr/local/include/folly/Synchronized.h:293:40: error: 'withULockPtr' function uses 'auto' type specifier without trailing return type
==> default:    auto withULockPtr(Function&& function) {
==> default:                                         ^
==> default: /usr/local/include/folly/Synchronized.h:293:40: note: deduced return type only available with -std=c++14 or -std=gnu++14
==> default: /usr/local/include/folly/Synchronized.h:297:42: error: 'withULockPtr' function uses 'auto' type specifier without trailing return type
==> default:    auto withULockPtr(Function&& function) const {
==> default:                                           ^
==> default: /usr/local/include/folly/Synchronized.h:297:42: note: deduced return type only available with -std=c++14 or -std=gnu++14
==> default: /usr/local/include/folly/Synchronized.h:370:36: error: 'withLock' function uses 'auto' type specifier without trailing return type
==> default:    auto withLock(Function&& function) {
==> default:                                     ^
==> default: /usr/local/include/folly/Synchronized.h:370:36: note: deduced return type only available with -std=c++14 or -std=gnu++14
==> default: /usr/local/include/folly/Synchronized.h:376:38: error: 'withLock' function uses 'auto' type specifier without trailing return type
==> default:    auto withLock(Function&& function) const {
==> default:                                       ^
==> default: /usr/local/include/folly/Synchronized.h:376:38: note: deduced return type only available with -std=c++14 or -std=gnu++14
==> default: /usr/local/include/folly/Synchronized.h:392:39: error: 'withLockPtr' function uses 'auto' type specifier without trailing return type
==> default:    auto withLockPtr(Function&& function) {
==> default:                                        ^
==> default: /usr/local/include/folly/Synchronized.h:392:39: note: deduced return type only available with -std=c++14 or -std=gnu++14
==> default: /usr/local/include/folly/Synchronized.h:396:41: error: 'withLockPtr' function uses 'auto' type specifier without trailing return type
==> default:    auto withLockPtr(Function&& function) const {
==> default:                                          ^
==> default: /usr/local/include/folly/Synchronized.h:396:41: note: deduced return type only available with -std=c++14 or -std=gnu++14
==> default: make[5]: Leaving directory `/home/vagrant/proxygen/proxygen/lib/utils'
==> default: make[5]: *** [AsyncTimeoutSet.lo] Error 1
==> default: make[4]: Leaving directory `/home/vagrant/proxygen/proxygen/lib/utils'
==> default: make[4]: *** [all-recursive] Error 1
==> default: make[3]: Leaving directory `/home/vagrant/proxygen/proxygen/lib/utils'
==> default: make[3]: *** [all] Error 2
==> default: make[2]: Leaving directory `/home/vagrant/proxygen/proxygen/lib'
==> default: make[2]: *** [all-recursive] Error 1
==> default: make[1]: Leaving directory `/home/vagrant/proxygen/proxygen'
==> default: make[1]: *** [all-recursive] Error 1
==> default: make: *** [all] Error 2
==> default: Proxygen not installed
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

**Comment by lanxi** [comment]
@mlabour automatic return type deduction is a feature of c++14 if you are running gcc >=4.8.0
Can you check your gcc version?

**Comment by mlabour** [comment]
@lanxi. I am running gcc 5.3. I was under the assumption that Proxygen was c++11 compliant but not yet c++14. What would you advise that we do? Thank you!
[vagrant@vagrant-ubuntu-trusty-64 proxygen]$ gcc --version
gcc (Ubuntu 5.3.0-3ubuntu1~14.04) 5.3.0 20151204
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by mjs6643** [comment]
I'm not an Autotools expert but it looks like Proxygen is configured to target `c++0x`

```
# Checks for programs.
AC_PROG_CXX
AC_PROG_CC
AC_PROG_CPP
AC_CXX_COMPILE_STDCXX_0X
AC_PROG_RANLIB

# Be sure to add any -std option to CXXFLAGS before we invoke any
# AC_COMPILE_IFELSE() or similar macros. Any such macros that are invoked
# before we update CXXFLAGS will not be run with the same options that we use
# during the real build.
STD=""
if test "x$ac_cv_cxx_compile_cxx0x_cxx" = xyes; then
   STD="-std=c++0x"
fi
if test "x$ac_cv_cxx_compile_cxx0x_gxx" = xyes; then
   STD="-std=gnu++0x"
fi
```

versus what I see in Folly's `configure.ac`

```AC_CXX_COMPILE_STDCXX_1Y

# Be sure to add any -std option to CXXFLAGS before we invoke any
# AC_COMPILE_IFELSE() or similar macros. Any such macros that are invoked
# before we update CXXFLAGS will not be run with the same options that we use
# during the real build.
STD=""
if test "x$ac_cv_cxx_compile_cxx1y_cxx" = xyes; then
   STD="-std=c++1y"
fi
if test "x$ac_cv_cxx_compile_cxx1y_gxx" = xyes; then
   STD="-std=gnu++1y"
fi```

**Comment by lanxi** [comment]
override CXXFLAGS='-DLIBMC_FBTRACE_DISABLE  -Wno-missing-field-initializers -Wno-deprecated -O3 -g -W -Wall -Wextra -Wno-unused-parameter -fno-strict-aliasing -std=gnu++0x -g -O2' with -std=gnu++1y?
