### ISSUE TITLE
/usr/bin/ld: EchoHandler.o: undefined reference to symbol '_ZNSt3__18ios_base5clearEj'

### ISSUE THREAD

**Issue by janlely** [facebook/proxygen#119]
OS : ubuntu 14.04
CC:  clang-3.8
CXX : clang++-3.8
libc++ : latest
boost : 1.59

folly, wangle : latest
ERROR:
/usr/bin/ld: EchoHandler.o: undefined reference to symbol '_ZNSt3__18ios_base5clearEj'
//usr/local/lib/libc++.so.1: error adding symbols: DSO missing from command line

**Comment by afrind** [comment]
I installed clang-3.8 and ran 

CC=/usr/bin/clang-3.8 CXX=/usr/bin/clang-3.8 ./configure
CC=/usr/bin/clang-3.8 CXX=/usr/bin/clang-3.8 make

and got a similar issue:

/bin/bash ../../../libtool  --tag=CXX   --mode=link /usr/bin/clang-3.8 -std=gnu++14  -DLIBMC_FBTRACE_DISABLE  -Wno-missing-field-initializers -Wno-deprecated -O3 -g -W -Wall -Wextra -Wno-unused-parameter -fno-strict-aliasing -g -O2   -o echo_server EchoHandler.o EchoServer.o ../../libproxygenhttpserver.la -lwangle -lfolly -lz -lssl -lcrypto -lcap -levent -lgflags -lglog  -L/usr/lib64 -lpthread -pthread -lfolly -lglog -ldouble-conversion -lboost_system -lboost_thread 
libtool: link: /usr/bin/clang-3.8 -std=gnu++14 -DLIBMC_FBTRACE_DISABLE -Wno-missing-field-initializers -Wno-deprecated -O3 -g -W -Wall -Wextra -Wno-unused-parameter -fno-strict-aliasing -g -O2 -o .libs/echo_server EchoHandler.o EchoServer.o -pthread  ../../.libs/libproxygenhttpserver.so -lwangle -lz -lssl -lcrypto -lcap -levent -lgflags -L/usr/lib64 -lpthread -lfolly -lglog -ldouble-conversion -lboost_system -lboost_thread -pthread
/usr/bin/ld: EchoHandler.o: undefined reference to symbol '__cxa_allocate_exception@@CXXABI_1.3'
//usr/lib/x86_64-linux-gnu/libstdc++.so.6: error adding symbols: DSO missing from command line
clang: error: linker command failed with exit code 1 (use -v to see invocation)

This command worked when I added -lstdc++ though, also I didn't take the time to recompile folly and wangle with clang.  I'm not sure about libstdc++ vs libc++.

**Comment by afrind** [comment]
This went a bit stale.  I'm closing it out but please reopen if you are still stuck here or if you have a resolution that worked for you.
