### ISSUE TITLE
Install Problem similar to #25 which is closed

### ISSUE THREAD

**Issue by CipherLiu** [facebook/proxygen#121]
![screenshot from 2016-10-15 13 45 36](https://cloud.githubusercontent.com/assets/3993620/19407784/c711fc80-92de-11e6-9c04-2a86953f2cca.png)
after run deps.sh ,the complie just hang there..

**Comment by lnicco** [comment]
Hi @CipherLiu, as in #25 there could be some dependency issue with Folly/thrift. 
I'm taking a look. Thanks for reporting this. 

Just to help me reproduce it, could you add some information on what your environment is ?
Linux distribution and version, and gcc version ?
thanks

**Comment by lnicco** [comment]
@CipherLiu I am not able to reproduce this. 
Are you still affected by this issue ?

**Comment by CipherLiu** [comment]
@lnicco sorry for the delay , I just ignore the tests

**Comment by lnicco** [comment]
this is an old issue. 
please reopen if still broken
