### ISSUE TITLE
wangle lib not included

### ISSUE THREAD

**Issue by itwalter** [facebook/proxygen#124]
commit 9d898219da13ecf1c12d35904e5d6ee25599d777 added `#include <wangle/client/ssl/SSLSession.h>` into _proxygen/httpserver/tests/HTTPServerTest.cpp_

However, as shown in _wangle/CMakeLists.txt (tags/v2016.10.31.00)_, the header files _wangle/client/ssl/*.h_ have not been installed into _/usr/local/include/wangle/client/ssl/_

In this way, deps.sh will terminate with the following error:

> make[4]: Entering directory `/.../proxygen/proxygen/httpserver/tests'
depbase=`echo HTTPServerTest.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
> 	g++ -std=gnu++14 -DHAVE_CONFIG_H   -I../../.. -I../../lib/test/googletest-release-1.8.0/googlemock/include -I../../lib/test/googletest-release-1.8.0/googletest/include  -I/usr/local/include   -DLIBMC_FBTRACE_DISABLE  -Wno-missing-field-initializers -Wno-deprecated -O3 -g -W -Wall -Wextra -Wno-unused-parameter -fno-strict-aliasing -g -O2 -MT HTTPServerTest.o -MD -MP -MF $depbase.Tpo -c -o HTTPServerTest.o HTTPServerTest.cpp &&\
> 	mv -f $depbase.Tpo $depbase.Po
HTTPServerTest.cpp:20:42: fatal error: wangle/client/ssl/SSLSession.h: No such file or directory
>  #include <wangle/client/ssl/SSLSession.h>
>                                           ^
> compilation terminated.
> make[4]: *** [HTTPServerTest.o] Error 1
> make[4]: Leaving directory `/.../proxygen/proxygen/httpserver/tests'
> make[3]: *** [check-am] Error 2
> make[3]: Leaving directory `/.../proxygen/proxygen/httpserver/tests'
> make[2]: *** [check-recursive] Error 1
> make[2]: Leaving directory `/.../proxygen/proxygen/httpserver/tests'
> make[1]: *** [check-recursive] Error 1
> make[1]: Leaving directory `/.../proxygen/proxygen/httpserver'
> make: *** [check-recursive] Error 1

Two alternatives to fix:
1. In wangle, install the _wangle/client/ssl/*.h_ to _/usr/local/include/wangle/client/ssl/_
2. Add the library path in _proxygen/configure.ac_:
> AM_CPPFLAGS='-I$(top_srcdir)/.. -I$(top_srcdir)/lib/test/googletest-release-1.8.0/googlemock/include -I$(top_srcdir)/lib/test/googletest-release-1.8.0/googletest/include **-I$(top_srcdir)/wangle**'

**Comment by itwalter** [comment]
This was found in proxygen tags/v0.32.0-403-gcd79c81

**Comment by russoue** [comment]
Can you please submit a PR for it?

**Comment by lnicco** [comment]
Hi @itwalter, thanks for reporting this, and apologies for the delay. 
It's going to be fixed soon, with a diff slightly different from the one you proposed. 
I'm going to add "-lwangle" to the list of libs instead.

**Comment by lnicco** [comment]
this issue should be fixed by this wangle commit
https://github.com/facebook/wangle/commit/bf271118962eb6b2d30adac2e6281b6871d26c72

**Comment by itwalter** [comment]
@lnicco The fix is awesome, thanks. 
BTW, the fix I proposed failed the auto test, but it is workable in our several environments.  I did not dig into the difference between Travis and my dev env yet.

**Comment by itwalter** [comment]
Just created #132 for the versioning & dependency issue found during investigation for current issue.

**Comment by lnicco** [comment]
thanks @itwalter, 
the Travis build could be broken for some other reason. 
we are tracking it internally. 

thanks for filing #132: I believe that we always want to build from master folly and wangle though
