### ISSUE TITLE
large post data process

### ISSUE THREAD

**Issue by sofartogo** [facebook/proxygen#126]
Hi, I'm a user of Proxygen, and like it very much.

Now I met a problem : 
When I use curl to post large data to my http server(based on proxygen), I cannot receive complete post data in the server side(just receive part of it). I'm not sure whether I use the proxygen http server in a wrong way or some settings of curl is wrong. Can anybody share some opinions?

Excuse for my pool English.

**Comment by sofartogo** [comment]
Hi, I'v solve the problem mentioned above...

Multiple IOBuf bodies is a chain, I construct the completed body by memcpy all the bodies in the chain to a unique one.

Thanks anyway!

**Comment by afrind** [comment]
The coalesce() function will do this for you if you need a contiguous memory buffer, but could be expensive for very large POSTs. You may want to consider writing your body processing code to work with non-contiguous buffers (see folly/io/Cursor.h)

**Comment by sofartogo** [comment]
I'v used coalesce() to refresh my code because I need to process the contiguous memory buffer. Thanks very much!
