### ISSUE TITLE
Support for QUIC

### ISSUE THREAD

**Issue by elsteelbrain** [facebook/proxygen#127]
QUIC is a transport layer protocol introduced by Google as a successor to SPDY. It is very similar to TCP + TLS + HTTP/2 but it works on UDP instead of TCP. It has great tolerance for network interruptions and "dramatically" reduces connection establishment time by providing 0-RTT handshakes.
[proto-quic](https://github.com/google/proto-quic) is standalone library for QUIC. There is also [libquic](https://github.com/devsisters/libquic) and [go-quic](https://github.com/lucas-clemente/quic-go) (implementation in GoLang).

Google has been using it heavily across all its sites since a 2013. Almost all of the Google sites are powered by QUIC right now, so, its battle tested.

What do you think? Are you interested in adding support in Proxygen?

**Comment by w-o-o** [comment]
We are interested in supporting QUIC for sure.  However, no ETA to share now.

**Comment by raeesbhatti** [comment]
@w-o-o Is anyone currently working on this or is it a TODO?

**Comment by afrind** [comment]
We're involved with the QUIC standardization efforts through the IETF, but we're not likely to add support for "google" QUIC.

**Comment by lnicco** [comment]
closing this since as @afrind said we do not have plans to support "google QUIC"

**Comment by rektide** [comment]
https://code.facebook.com/posts/608854979307125/building-zero-protocol-for-fast-secure-mobile-connections/ makes me feel like Facebook may have an implementation of QUIC tucked under a mattress somewhere, & the modified Zero protocol alteration of it. These sure would be great to get to see.

**Comment by afrind** [comment]
We are currently building an implementation of IETF QUIC, which is evolving from Google QUIC.  We don’t have an implementation of Google QUIC and we don’t have plans to support it.  We plan to open source our IETF QUIC implementation and the proxygen integration with it as soon as we practically can.

**Comment by vinothchandar** [comment]
>We plan to open source our IETF QUIC implementation and the proxygen integration with it as soon as we practically can.

@afrind is there a rough ETA? Also curious, if you have any explicit goals for reducing the client binary size. We (at Uber) are also exploring this route, with a focus of having a thin binary that can be put inside apps easily. Would be thrilled to connect over this..

**Comment by edsburke** [comment]
Hi FB team, I am bumping this thread to bring up extensive community interests in FB Quic. Would you please share its current status and ETA to open source it? Your feedback would be very appreciated.

Thanks a lot.

**Comment by afrind** [comment]
We are still in the process of building and testing IETF QUIC.  Now that fizz has been open sourced, all of the requisite dependencies of our iQUIC implementation are available.  I still can't commit to a specific open source timeline for quic itself, but I would expect it to happen in 2019, hopefully no later than iQUIC gaining RFC status.

**Comment by edsburke** [comment]
Thank you @afrind for your quick response. Is it going to be QUIC over TCP as [aforementioned](https://code.fb.com/networking-traffic/building-zero-protocol-for-fast-secure-mobile-connections/), or over UDP instead?

Regarding the proxygen, will iQUIC be integrated into it as default transport protocol? Thank you very much!!

**Comment by afrind** [comment]
IETF QUIC is only defined over UDP.  Zero Protocol (gQUIC crypto over TCP) is a FB specific thing, and I'm not sure it's open source plans.

For proxygen, I don't think it will be the default, but it will be like one line of config to enable a QUIC server (assuming you already had HTTPS), and similarly simple on the client?

**Comment by edsburke** [comment]
Thanks a log @afrind. This makes it quite clear.
