### ISSUE TITLE
[Segnalation] Mix issues during the installation and the compilation

### ISSUE THREAD

**Issue by MatteoBertolino92** [facebook/proxygen#128]
Ubuntu 14.04.

1) In the README it is adviced: g++ -std=c++11 -o my_echo EchoServer.cpp EchoHandler.cpp -lproxygenhttpserver -lfolly -lglog -lgflags -pthread
Actually there is the error: error: ‘withWLock’ function uses ‘auto’ type specifier without trailing return type
That can be solved compiling with g++ -std=c++1y 

2) Compilation error: in HTTServertest.cpp , it does not find #include <wangle/client/ssl/SSLSession.h>
I solved without investigation, just putting my absolute path to SSLSession.h.
I suggest you to try and eventually fix it.

**Comment by lnicco** [comment]
Hi @MatteoBertolino92,
thanks for reporting the issues. 
Your second point is a known issue (see #124) and there is a fix ready to be pushed soon. 

I'll look into the first issue you pointed out.
