### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by sofartogo** [facebook/proxygen#130]
Hi, After running httpserver for a long time, program occurs an error : 

Could not create logging file: Too many open files
COULD NOT CREATE A LOGGINGFILE 20161123-073115.17162!Could not create logging file: Too many open files
COULD NOT CREATE A LOGGINGFILE 20161123-073115.17162!Could not create logging file: Too many open files
COULD NOT CREATE A LOGGINGFILE 20161123-073115.17162!E1123 07:31:15.651653 17167 AsyncServerSocket.cpp:808] accept failed: out of file descriptors; entering accept back-off state
E1123 07:31:15.652848 17171 Acceptor.cpp:345] error accepting on acceptor socket: accept() failed
E1123 07:31:16.653069 17167 AsyncServerSocket.cpp:808] accept failed: out of file descriptors; entering accept back-off state
E1123 07:31:16.653123 17172 Acceptor.cpp:345] error accepting on acceptor socket: accept() failed
E1123 07:31:17.654228 17167 AsyncServerSocket.cpp:808] accept failed: out of file descriptors; entering accept back-off state
E1123 07:31:17.654299 17173 Acceptor.cpp:345] error accepting on acceptor socket: accept() failed
E1123 07:31:18.655439 17167 AsyncServerSocket.cpp:808] accept failed: out of file descriptors; entering accept back-off state
E1123 07:31:18.655539 17174 Acceptor.cpp:345] error accepting on acceptor socket: accept() failed
E1123 07:31:19.656649 17167 AsyncServerSocket.cpp:808] accept failed: out of file descriptors; entering accept back-off state
E1123 07:31:19.656728 17175 Acceptor.cpp:345] error accepting on acceptor socket: accept() failed
E1123 07:31:20.657832 17167 AsyncServerSocket.cpp:808] accept failed: out of file descriptors; entering accept back-off state
E1123 07:31:20.657917 17168 Acceptor.cpp:345] error accepting on acceptor socket: accept() failed
E1123 07:31:21.659037 17167 AsyncServerSocket.cpp:808] accept failed: out of file descriptors; entering accept back-off state
E1123 07:31:21.659086 17169 Acceptor.cpp:345] error accepting on acceptor socket: accept() failed
E1123 07:31:22.660146 17167 AsyncServerSocket.cpp:808] accept failed: out of file descriptors; entering accept back-off state
E1123 07:31:22.660183 17170 Acceptor.cpp:345] error accepting on acceptor socket: accept() failed
E1123 07:31:23.661309 17167 AsyncServerSocket.cpp:808] accept failed: out of file descriptors; entering accept back-off state
E1123 07:31:23.661373 17171 Acceptor.cpp:345] error accepting on acceptor socket: accept() failed
E1123 07:31:24.662505 17167 AsyncServerSocket.cpp:808] accept failed: out of file descriptors; entering accept back-off state
E1123 07:31:24.662587 17172 Acceptor.cpp:345] error accepting on acceptor socket: accept() failed
E1123 07:31:25.663686 17167 AsyncServerSocket.cpp:808] accept failed: out of file descriptors; entering accept back-off state
E1123 07:31:25.663785 17173 Acceptor.cpp:345] error accepting on acceptor socket: accept() failed
E1123 07:31:26.664918 17167 AsyncServerSocket.cpp:808] accept failed: out of file descriptors; entering accept back-off state
E1123 07:31:26.665025 17174 Acceptor.cpp:345] error accepting on acceptor socket: accept() failed
E1123 07:31:27.666134 17167 AsyncServerSocket.cpp:808] accept failed: out of file descriptors; entering accept back-off state
E1123 07:31:27.666239 17175 Acceptor.cpp:345] error accepting on acceptor socket: accept() failed
E1123 07:31:28.667325 17167 AsyncServerSocket.cpp:808] accept failed: out of file descriptors; entering accept back-off state
E1123 07:31:28.667378 17168 Acceptor.cpp:345] error accepting on acceptor socket: accept() failed
E1123 07:31:29.668488 17167 AsyncServerSocket.cpp:808] accept failed: out of file descriptors; entering accept back-off state
E1123 07:31:29.668566 17169 Acceptor.cpp:345] error accepting on acceptor socket: accept() failed
E1123 07:31:30.669669 17167 AsyncServerSocket.cpp:808] accept failed: out of file descriptors; entering accept back-off state
E1123 07:31:30.669771 17170 Acceptor.cpp:345] error accepting on acceptor socket: accept() failed

I wonder the reason is too many connections not released. Httpserver don't close connection proactively.

Below is the code of onUpgrade & requestComplete & onError of HttpHandler:
`
void RedisProxyHandler::onUpgrade(UpgradeProtocol protocol) noexcept
{
    // handler doesn't support upgrades
}

void RedisProxyHandler::requestComplete() noexcept
{
    delete this;
}

void RedisProxyHandler::onError(ProxygenError err) noexcept
{
    delete this;
}
`

Except increasing the number of  'open files' of system(ulimited -a), Is there any other method to solve this issue? Maybe I miss some connection close method in my http handler?

Thanks.

**Comment by lanxi** [comment]
Hi @sofartogo rather than allowing unlimited number of open sockets for your httpserver, it might be worthwhile looking for any kind of leaking inside your service. It is not expected for acceptor to run out of available fd/sockets even if it is a considerable large number.

**Comment by afrind** [comment]
proxygen has to have one open file (fd) for each client socket.  Your fd limit needs to be at least as high as the maximum number of concurrent connections you want to have.  If you are hitting this but don't have many connected clients then it's probably a leak.

**Comment by afrind** [comment]
I think it's either a leak in the application code or system system settings not being high enough for peak traffic.  Please reopen with repro steps if you have them.
