### ISSUE TITLE
Versioning & Dependency Issue

### ISSUE THREAD

**Issue by itwalter** [facebook/proxygen#132]
When digging in #124, potential issue is found in deps.sh, since it always "git clone" from the latest tag of external projects.

In this case, the tag labelled for proxygen does not make sense because the dependencies are NOT fixed and clear.  As long as external projects evolve, proxygen will be subject to the unstability from outside.

**Comment by lnicco** [comment]
the tag was introduced to work around some non backwards compatible change in the dependencies. 
It is not in use anymore and we want to always build from master folly and wangle as that is what we also use internally, so they should be guaranteed to be in sync at (almost) all times
