### ISSUE TITLE
SIGSEGV proxygen::HTTPMessage::dumpMessage() occasionally 

### ISSUE THREAD

**Issue by abhiguru** [facebook/proxygen#134]
*** Aborted at 1481230987 (unix time) try "date -d @1481230987" if you are using GNU date ***
PC: @     0x55837fd0a5cc proxygen::HTTPMessage::dumpMessage()
*** SIGSEGV (@0x7fb781262c88) received by PID 13941 (TID 0x7fb6d547e700) from PID 18446744071581346952; stack trace: ***
    @     0x7fb6e077b670 (unknown)
    @     0x55837fd0a5cc proxygen::HTTPMessage::dumpMessage()
    @     0x55837fce96eb CurlService::CurlClient::connectSuccess()
    @     0x55837fd00433 proxygen::HTTPConnector::connectSuccess()
    @     0x7fb6e0b018d5 (anonymous namespace)::AsyncSSLSocketConnector::handshakeSuc()
    @     0x7fb6e0b07557 folly::AsyncSSLSocket::handleConnect()
    @     0x7fb6e0b0aa2f folly::AsyncSSLSocket::handleRead()
    @     0x7fb6e0af606a folly::AsyncSocket::ioReady()
    @     0x7fb6dcee2a0c event_base_loop
    @     0x7fb6e0b0dbd0 folly::EventBase::loopBody()
    @     0x7fb6e0b0f8b6 folly::EventBase::loopForever()
    @     0x55837fc808fe VideoProcessor::initSegmentListener()
    @     0x55837fc80629 VideoProcessor::VideoProcessor()
    @     0x55837fc6b4d6 _ZZ4mainENKUlN3vcu12CurlResponseEE0_clES0_
    @     0x55837fc6c51a _ZZZN5folly6FutureIN3vcu12CurlResponseEE18thenImplementationIRZ4mainEUlS2_E0_NS_6detail14callableResultIS2_S6_EELb0EJOS2_EEENSt9enable_ifIXntsrNT0_13ReturnsFutureE5valueENSC_6ReturnEE4typeEOT_NS7_9argResultIXT1_ESH_JDpT2_EEEENUlONS_3TryIS2_EEE_clESP_ENKUlvE_clEv
    @     0x55837fc6d63b _ZN5folly11makeTryWithIZZNS_6FutureIN3vcu12CurlResponseEE18thenImplementationIRZ4mainEUlS3_E0_NS_6detail14callableResultIS3_S7_EELb0EJOS3_EEENSt9enable_ifIXntsrNT0_13ReturnsFutureE5valueENSD_6ReturnEE4typeEOT_NS8_9argResultIXT1_ESI_JDpT2_EEEENUlONS_3TryIS3_EEE_clESQ_EUlvE_EENSC_IXntsrSt7is_sameINSt9result_ofIFSI_vEE4typeEvE5valueENSO_ISX_EEE4typeESJ_
    @     0x55837fc6cd02 _ZN5folly7PromiseIN3vcu12CurlResponseEE7setWithIZZNS_6FutureIS2_E18thenImplementationIRZ4mainEUlS2_E0_NS_6detail14callableResultIS2_S9_EELb0EJOS2_EEENSt9enable_ifIXntsrNT0_13ReturnsFutureE5valueENSF_6ReturnEE4typeEOT_NSA_9argResultIXT1_ESK_JDpT2_EEEENUlONS_3TryIS2_EEE_clESS_EUlvE_EEvSL_
    @     0x55837fc6c634 _ZZN5folly6FutureIN3vcu12CurlResponseEE18thenImplementationIRZ4mainEUlS2_E0_NS_6detail14callableResultIS2_S6_EELb0EJOS2_EEENSt9enable_ifIXntsrNT0_13ReturnsFutureE5valueENSC_6ReturnEE4typeEOT_NS7_9argResultIXT1_ESH_JDpT2_EEEENUlONS_3TryIS2_EEE_clESP_
    @     0x55837fc6e773 _ZN5folly6detail8function14FunctionTraitsIFvONS_3TryIN3vcu12CurlResponseEEEEE9callSmallIZNS_6FutureIS5_E18thenImplementationIRZ4mainEUlS5_E0_NS0_14callableResultIS5_SF_EELb0EJOS5_EEENSt9enable_ifIXntsrNT0_13ReturnsFutureE5valueENSK_6ReturnEE4typeEOT_NS0_9argResultIXT1_ESP_JDpT2_EEEEUlS7_E_EEvRNS1_4DataES7_
    @     0x55837fcaee94 folly::detail::function::FunctionTraits<>::operator()()
    @     0x55837fcaac34 _ZZN5folly6detail4CoreIN3vcu12CurlResponseEE10doCallbackEvENUlvE_clEv
    @     0x55837fcb8018 _ZN5folly6detail8function14FunctionTraitsIFvvEE9callSmallIZNS0_4CoreIN3vcu12CurlResponseEE10doCallbackEvEUlvE_EEvRNS1_4DataE
    @     0x55837fda482b folly::detail::function::FunctionTraits<>::operator()()
    @     0x55837fda77b1 wangle::ThreadPoolExecutor::runTask()
    @     0x55837fd9c523 wangle::CPUThreadPoolExecutor::threadRun()
    @     0x55837fdb5eab _ZSt13__invoke_implIvRKMN6wangle18ThreadPoolExecutorEFvSt10shared_ptrINS1_6ThreadEEERPS1_JRS4_EET_St21__invoke_memfun_derefOT0_OT1_DpOT2_
    @     0x55837fdb548a _ZSt8__invokeIRKMN6wangle18ThreadPoolExecutorEFvSt10shared_ptrINS1_6ThreadEEEJRPS1_RS4_EENSt9result_ofIFOT_DpOT0_EE4typeESE_SH_
    @     0x55837fdb44f3 _ZNKSt12_Mem_fn_baseIMN6wangle18ThreadPoolExecutorEFvSt10shared_ptrINS1_6ThreadEEELb1EEclIJRPS1_RS4_EEEDTcl8__invokedtdefpT6_M_pmfspcl7forwardIT_Efp_EEEDpOSC_
    @     0x55837fdb2b2c _ZNSt5_BindIFSt7_Mem_fnIMN6wangle18ThreadPoolExecutorEFvSt10shared_ptrINS2_6ThreadEEEEPS2_S5_EE6__callIvJEJLm0ELm1EEEET_OSt5tupleIJDpT0_EESt12_Index_tupleIJXspT1_EEE
    @     0x55837fdb1243 _ZNSt5_BindIFSt7_Mem_fnIMN6wangle18ThreadPoolExecutorEFvSt10shared_ptrINS2_6ThreadEEEEPS2_S5_EEclIJEvEET0_DpOT_
    @     0x55837fdaefc8 folly::detail::function::FunctionTraits<>::callBig<>()
    @     0x55837fda482b folly::detail::function::FunctionTraits<>::operator()()

**Comment by afrind** [comment]
Highly doubtful that the bug is in dumpMessage itself, again, ASAN would likely help.  Given that you have reported several other memory related crashes perhaps all have a similar root cause.

**Comment by abhiguru** [comment]
Unable to reproduce this at the moment will open with ASAN logs when reproduced
