### ISSUE TITLE
Window.cpp:20 Check failed setCapacity(capactity) ocassionally 

### ISSUE THREAD

**Issue by abhiguru** [facebook/proxygen#135]
Occasionally seen

F1209 02:58:16.844967 16095 Window.cpp:20] Check failed: setCapacity(capacity) 
*** Check failure stack trace: ***
    @     0x7f1cdb06b5ad  google::LogMessage::Fail()
    @     0x7f1cdb06d413  google::LogMessage::SendToLog()
    @     0x7f1cdb06b13b  google::LogMessage::Flush()
    @     0x7f1cdb06ddfe  google::LogMessageFatal::~LogMessageFatal()
    @     0x56481414c073  proxygen::Window::Window()
    @     0x564814123261  proxygen::HTTPTransaction::HTTPTransaction()
    @     0x5648141205ef  _ZNSt8_Rb_treeIjSt4pairIKjN8proxygen15HTTPTransactionEESt10_Select1stIS4_ESt4lessIjESaIS4_EE17_M_emplace_uniqueIJRKSt21piecewise_construct_tSt5tupleIJRjEESF_IJONS2_18TransportDirectionESG_SG_RNS2_11HTTPSessionERNS2_18HTTP2PriorityQueueERNS2_18WheelTimerInstanceERPNS2_16HTTPSessionStatsEObRmOmRNS2_5http214PriorityUpdateESG_EEEEES0_ISt17_Rb_tree_iteratorIS4_EbEDpOT_
    @     0x56481411c928  proxygen::HTTPSession::createTransaction()
    @     0x56481412d873  proxygen::HTTPUpstreamSession::newTransaction()
    @     0x5648140e5447  CurlService::CurlClient::connectSuccess()
    @     0x5648140fc433  proxygen::HTTPConnector::connectSuccess()
    @     0x7f1cdc39b8d5  (anonymous namespace)::AsyncSSLSocketConnector::handshakeSuc()
    @     0x7f1cdc3a1557  folly::AsyncSSLSocket::handleConnect()
    @     0x7f1cdc3a4a2f  folly::AsyncSSLSocket::handleRead()
    @     0x7f1cdc39006a  folly::AsyncSocket::ioReady()
    @     0x7f1cd877ca0c  event_base_loop
    @     0x7f1cdc3a7bd0  folly::EventBase::loopBody()
    @     0x7f1cdc3a98b6  folly::EventBase::loopForever()
    @     0x56481407c8fe  VideoProcessor::initSegmentListener()
    @     0x56481407c629  VideoProcessor::VideoProcessor()
    @     0x5648140674d6  _ZZ4mainENKUlN3vcu12CurlResponseEE0_clES0_
    @     0x56481406851a  _ZZZN5folly6FutureIN3vcu12CurlResponseEE18thenImplementationIRZ4mainEUlS2_E0_NS_6detail14callableResultIS2_S6_EELb0EJOS2_EEENSt9enable_ifIXntsrNT0_13ReturnsFutureE5valueENSC_6ReturnEE4typeEOT_NS7_9argResultIXT1_ESH_JDpT2_EEEENUlONS_3TryIS2_EEE_clESP_ENKUlvE_clEv
    @     0x56481406963b  _ZN5folly11makeTryWithIZZNS_6FutureIN3vcu12CurlResponseEE18thenImplementationIRZ4mainEUlS3_E0_NS_6detail14callableResultIS3_S7_EELb0EJOS3_EEENSt9enable_ifIXntsrNT0_13ReturnsFutureE5valueENSD_6ReturnEE4typeEOT_NS8_9argResultIXT1_ESI_JDpT2_EEEENUlONS_3TryIS3_EEE_clESQ_EUlvE_EENSC_IXntsrSt7is_sameINSt9result_ofIFSI_vEE4typeEvE5valueENSO_ISX_EEE4typeESJ_
    @     0x564814068d02  _ZN5folly7PromiseIN3vcu12CurlResponseEE7setWithIZZNS_6FutureIS2_E18thenImplementationIRZ4mainEUlS2_E0_NS_6detail14callableResultIS2_S9_EELb0EJOS2_EEENSt9enable_ifIXntsrNT0_13ReturnsFutureE5valueENSF_6ReturnEE4typeEOT_NSA_9argResultIXT1_ESK_JDpT2_EEEENUlONS_3TryIS2_EEE_clESS_EUlvE_EEvSL_
    @     0x564814068634  _ZZN5folly6FutureIN3vcu12CurlResponseEE18thenImplementationIRZ4mainEUlS2_E0_NS_6detail14callableResultIS2_S6_EELb0EJOS2_EEENSt9enable_ifIXntsrNT0_13ReturnsFutureE5valueENSC_6ReturnEE4typeEOT_NS7_9argResultIXT1_ESH_JDpT2_EEEENUlONS_3TryIS2_EEE_clESP_
    @     0x56481406a773  _ZN5folly6detail8function14FunctionTraitsIFvONS_3TryIN3vcu12CurlResponseEEEEE9callSmallIZNS_6FutureIS5_E18thenImplementationIRZ4mainEUlS5_E0_NS0_14callableResultIS5_SF_EELb0EJOS5_EEENSt9enable_ifIXntsrNT0_13ReturnsFutureE5valueENSK_6ReturnEE4typeEOT_NS0_9argResultIXT1_ESP_JDpT2_EEEEUlS7_E_EEvRNS1_4DataES7_
    @     0x5648140aae94  folly::detail::function::FunctionTraits<>::operator()()
    @     0x5648140a6c34  _ZZN5folly6detail4CoreIN3vcu12CurlResponseEE10doCallbackEvENUlvE_clEv
    @     0x5648140b4018  _ZN5folly6detail8function14FunctionTraitsIFvvEE9callSmallIZNS0_4CoreIN3vcu12CurlResponseEE10doCallbackEvEUlvE_EEvRNS1_4DataE
    @     0x5648141a082b  folly::detail::function::FunctionTraits<>::operator()()
    @     0x5648141a37b1  wangle::ThreadPoolExecutor::runTask()
    @     0x564814198523  wangle::CPUThreadPoolExecutor::threadRun()

**Comment by afrind** [comment]
Can you see what is the value of 'capacity' and where did it come from?  Can you run with -v 3 or -vmodule Window*:3?  There's some detail that can be printed from setCapacity that may help.

**Comment by afrind** [comment]
@abhiguru We're still interested to debug this if you have more details to go on.

**Comment by afrind** [comment]
Closing out this old issue.
