### ISSUE TITLE
Idle timeout offset by +5000 ms ( 5 secs)

### ISSUE THREAD

**Issue by psetevik** [facebook/proxygen#136]
When playing with EchoServer code, I noticed that requested idletimeout is enforced with positive offset of 5 secs. In other words, when set to 5000 ms, it will actually be enforced @ 10000 msec. 10 sec -> 15 sec, 20 -> 25 and so on.

TO value is set via:

  HTTPServerOptions options;
  options.threads = static_cast<size_t>(FLAGS_threads);
  options.idleTimeout = std::chrono::milliseconds(20000); // <- HERE

To test, I simply telnet into port 11000 (default http port in EchoServer) and wait, w/o sending any data to to remote side, for connection to timeout

#######

When set to 100ms (admittedly low value)

dev@ub1604:~$ time telnet localhost 11000
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
Connection closed by foreign host.

real	0m5.110s
user	0m0.000s
sys	0m0.000s

When set to 5 secs:

dev@ub1604:~$ time telnet localhost 11000
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
Connection closed by foreign host.

real	0m10.019s
user	0m0.000s
sys	0m0.000s

When set to 10 secs
dev@ub1604:~$ time telnet localhost 11000
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
Connection closed by foreign host.

real	0m15.006s
user	0m0.000s
sys	0m0.000s

When set to 20 sec
dev@ub1604:~$ time telnet localhost 11000
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
Connection closed by foreign host.

real	0m25.009s
user	0m0.000s
sys	0m0.000s

**Comment by afrind** [comment]
Indeed.  The forceful shutdown of a connection is delayed by the HTTPSessionController's "graceful shutdown timeout", which defaults to 5 seconds.  The extra grace period is to catch a request that may be in flight to the server.  It makes a little more sense with HTTP/2.  When the idle timer expires we send an immediate GOAWAY with last good stream=maxint.  A final GOAWAY with the real last good stream is sent after the graceful shutdown timeout, assuming the client doesn't terminate sooner.  You can change it it by calling acceptor->setGracefulShutdownTimeout() from AcceptorFactory::newAcceptor (will gladly accept the PR).

**Comment by psetevik** [comment]
Yes, I noticed the "graceful" thing yesterday as I was trying to figure out what is going on. 

I guess the waters are muddied by the recent fad of "preopening" connections in browsers, in expectation that end use might actually click on some link(s). So you get all these conns opened, but no requests ever come through.
