### ISSUE TITLE
Error building latest release

### ISSUE THREAD

**Issue by bmgandre** [facebook/proxygen#138]
The latest release is failing to build using the latest release of folly and wangle.
v0.32.0 is almost 4 months old, so is there plans to release a new version? 
... or maybe tags are missing here.

**Comment by agah-pt** [comment]
I agree with the post above.
It would help to have tags or something to keep track of versions.

**Comment by afrind** [comment]
We've enabled weekly tagging and I see the latest tag is from this week.
