### ISSUE TITLE
build fails on httpserver proxy sample

### ISSUE THREAD

**Issue by bjd** [facebook/proxygen#142]
```
make[5]: Entering directory `/rest/proxygen/proxygen/httpserver/samples/proxy'
...
ProxyHandler.cpp:24:13: error: expected constructor, destructor, or type conversion before ‘(’ token
 DEFINE_int32(proxy_connect_timeout, 1000,
             ^
ProxyHandler.cpp: In member function ‘virtual void ProxyService::ProxyHandler::onRequest(std::unique_ptr<proxygen::HTTPMessage>)’:
ProxyHandler.cpp:67:35: error: ‘FLAGS_proxy_connect_timeout’ was not declared in this scope
         std::chrono::milliseconds(FLAGS_proxy_connect_timeout), opts);
```

Adding ```#include <gflags/gflags.h>``` to ProxyHandler.cpp fixes it

**Comment by lnicco** [comment]
thanks @bjd for reporting this. Will be fixed soon!

**Comment by lnicco** [comment]
in any case, could you please post more information on your setup, and the command you run to build ?
as this is building fine internally

**Comment by bjd** [comment]
I'm trying to build it on a Centos 6.7 system with devtoolset-4 (g++ 5.3.1).
I have built and installed all the dependencies manually (in similar way as what deps.sh is doing for ubuntu). I have the dependencies installed under custom location at /rest/build and then try to build proxygen as follows:
```
export PREFIX=/rest/build
cd proxygen/proxygen
LD_LIBRARY_PATH=$PREFIX/lib:$LD_LIBRARY_PATH LDFLAGS="-L$PREFIX/lib" CFLAGS="-I$PREFIX/include" CXXFLAGS="-I$PREFIX/include" ./configure --prefix=$PREFIX --with-boost-libdir=$PREFIX/lib
make -j8 && make install
```

**Comment by lnicco** [comment]
@bjd thanks for the additional info. We currently officially support ubuntu only and that's where we run our contbuild right now. 
You manually replicating what deps.sh does could explain the error you are seeing here.
 
I have fixed the include in ProxyHandler, let us know if you hit any other issue,
or if you have feedback on the new proxy example.
