### ISSUE TITLE
Issues in using libproxygenhttpserver and facebook libthrift 

### ISSUE THREAD

**Issue by gangadharmgithub** [facebook/proxygen#144]
I have a Make file with below libraries linked to my program and compilation goes fine.
-lproxygenhttpserver -lthrift -lthriftcpp2 -lthriftprotocol

But when I run the program,  I see below error: 
./TestClient
ERROR: flag 'dcache_unit_test' was defined more than once (in files '/root/test/wangle-2016.10.17.00/wangle/ssl/SSLSessionCacheManager.cpp' and '/wangle/wangle/ssl/SSLSessionCacheManager.cpp').

I found that both proxygen and thrift libraries are compiled using wangle static archive. To fix above issue I decided to build 
1. wangle shared library (cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr -DBUILD_SHARED_LIBS=ON .)
2. Compile facebook thrift (make sure it uses wangle shared library
3. Compile proxygen (make sure it uses wangle shared library)

I verified  steps 1 and 2.  

In step 3 I am hitting below issue:
proxygen/proxygen# ./configure --prefix=/usr
....
configure: error: Please install the wangle library from https://github.com/facebook/wangle

But I see the library in 
# ls -l /usr/lib/libwangle.so.1
lrwxrwxrwx 1 root root 18 Jan 11 10:38 /usr/lib/libwangle.so.1 -> libwangle.so.1.0.0

What is the issue?

**Comment by gangadharmgithub** [comment]
from config.log:

configure:18885: g++ -o conftest -DLIBMC_FBTRACE_DISABLE  -Wno-missing-field-initializers -Wno-deprecated -O3 -g -W -Wall -Wextra -Wno-unused-parameter -fno-strict-aliasing -g -O2   conftest.cpp -lwangle  -lfolly -lz -lssl -lcrypto -lcap -levent -lgflags -lglog  >&5
/usr/lib/gcc/x86_64-linux-gnu/6/../../../../lib/libwangle.so: error: undefined reference to 'pthread_setname_np'
/usr/lib/gcc/x86_64-linux-gnu/6/../../../../lib/libwangle.so: error: undefined reference to 'pthread_create'
/usr/lib/gcc/x86_64-linux-gnu/6/../../../../lib/libwangle.so: error: undefined reference to 'pthread_getspecific'
/usr/lib/gcc/x86_64-linux-gnu/6/../../../../lib/libwangle.so: error: undefined reference to 'pthread_setspecific'
collect2: error: ld returned 1 exit status
configure:18885: $? = 1

**Comment by gangadharmgithub** [comment]
The below changed fixed the issue.

root@vsan-blr49:~/ganga/pgengit/proxygen# git diff
diff --git a/proxygen/configure.ac b/proxygen/configure.ac
index 19566f5..b931ba7 100644
--- a/proxygen/configure.ac
+++ b/proxygen/configure.ac
@@ -35,6 +35,7 @@ CXXFLAGS="-fno-strict-aliasing $CXXFLAGS"
 CXXFLAGS="-O3 -g -W -Wall -Wextra -Wno-unused-parameter $CXXFLAGS"
 CXXFLAGS=" -Wno-missing-field-initializers -Wno-deprecated $CXXFLAGS"
 CXXFLAGS="-DLIBMC_FBTRACE_DISABLE $CXXFLAGS"
+CXXFLAGS="-pthread $CXXFLAGS"

 CFLAGS="-DLIBMC_FBTRACE_DISABLE $CFLAGS"

**Comment by lanxi** [comment]
Hi @gangadharmgithub,

Thanks for addressing this issue! According to the [README](https://github.com/facebook/proxygen/blob/master/README.md#using-it) file, when you build with `-lproxygenhttpserver -lthrift -lthriftcpp2 -lthriftprotocol`, `-pthread` flag is also needed. That should resolve the error you were encountering. Please let us know if you have any questions/concerns and thank you again for your contribution!

**Comment by gangadharmgithub** [comment]
Hi @lanxi,

In my application I have -pthread flag. The problem is when running ./configure to build a libproxygenhttpserver library,  I am seeing below issue:

**configure: error: Please install the wangle library from https://github.com/facebook/wangle**

./configure.log shows:
------------------------------
onfigure:18885: g++ -o conftest -DLIBMC_FBTRACE_DISABLE -Wno-missing-field-initializers -Wno-deprecated -O3 -g -W -Wall -Wextra -Wno-unused-parameter -fno-strict-aliasing -g -O2 conftest.cpp -lwangle -lfolly -lz -lssl -lcrypto -lcap -levent -lgflags -lglog >&5
/usr/lib/gcc/x86_64-linux-gnu/6/../../../../lib/libwangle.so: error: undefined reference to 'pthread_setname_np'
/usr/lib/gcc/x86_64-linux-gnu/6/../../../../lib/libwangle.so: error: undefined reference to 'pthread_create'
/usr/lib/gcc/x86_64-linux-gnu/6/../../../../lib/libwangle.so: error: undefined reference to 'pthread_getspecific'
/usr/lib/gcc/x86_64-linux-gnu/6/../../../../lib/libwangle.so: error: undefined reference to 'pthread_setspecific'
collect2: error: ld returned 1 exit status
-------------------------------------------

which is not my application issue.  we can not build a httpproxygen library if we have shared libwangle.so.1 in the library path.

The proposed pullrequest (https://github.com/facebook/proxygen/pull/145)  fixes that issue.

Let me know if this needs to be fixed in wangle source.

**Comment by lanxi** [comment]
Thank you @gangadharmgithub :) The pull request has been processed for this.
