### ISSUE TITLE
Buildline for ECHO in Readme uses C++11 but requires C++14

### ISSUE THREAD

**Issue by Memnarch** [facebook/proxygen#151]
Just noticed the following buildline is wrong(in Readme)

> g++ -std=c++11 -o my_echo EchoServer.cpp EchoHandler.cpp -lproxygenhttpserver -lfolly -lglog -lgflags -pthread

But it requires C++14, so it should look like this:

> g++ -std=c++14 -o my_echo EchoServer.cpp EchoHandler.cpp -lproxygenhttpserver -lfolly -lglog -lgflags -pthread

Otherwhise errors like this will popup:
```
/usr/local/include/folly/Synchronized.h:163:39: note: deduced return type only available with -std=c++14 or -std=gnu++14
/usr/local/include/folly/Synchronized.h:179:40: error: ‘withWLockPtr’ function uses ‘auto’ type specifier without trailing return type
   auto withWLockPtr(Function&& function) {
                                        ^

```

**Comment by lnicco** [comment]
thanks for the report, 
this is the same issue signaled in #128 
fixing it now
