### ISSUE TITLE
High CPU usage with Proxygen

### ISSUE THREAD

**Issue by michaelpog** [facebook/proxygen#152]
I'm building a multi-proxy Http server, and I'm comparing two frameworks.
1) C++ Proxygen
2) Java Vertx.

Both frameworks are based on event loops so I built two prototypes and I expected the performance of Proxygen to be superior, since it's in C++, and is using so many of folly's optimizations.
However my application built with Proxygen is using much more cpu than the one I built with Java Vert.x. Pretty much on every value of req/sec. (using wrk2 for benchmarking)

Eventually, the proxygen based multi-proxy breaks first because it hits a CPU_USAGE>750% (8 core machine).

In a nutshell, the multi-proxy is doing the following:
*)Takes a POST HTTP request, with a Json body.
*) Deserializes the json.
*) Builds multiple outbound requests to downstream services.
*) Receives and aggregates the responses into one http response.
*) Builds a json out of the aggregate response and sends it upstream.

The logic (which is minimal) and architecture of both prototypes are identical up to nuances of the language and framework itself.

When profiling the application with callgrind and google perftools. I see that my logic is not the bottleneck, however I cannot figure out where it is since proxygen/folly/wangle strip all the symbols. 
So my call graph looks like a bunch of arrows coming out and into libproxyhttpserver.so. And all I can see is 70% of the time is spent in folly::eventbase::loopbody in eventbase.cpp (an arrow coming out of libproxyhttpserver.so). 
That forks into: 
~31% folly::NotificationQueue::ensureSignalLocked NotificationQueue.h 
and
 ~35% in folly:AsyncSocket::handleRead::AsyncSocket.cpp. 
Each of those has an arrow pointing back into libproxyhttpserver.so

Can anyone please tell me how I can rebuild proxygen with all its dependencies with debug symbols, and maybe even with no optimizations?
What tools do you guys use to analyze proxygen's performance?
Any ideas on why the cpu usage is so high.

A few more details. I have 2 http server threads, and 6 Http Client threads ( I have an IOThreadPoolExecutor of 6 threads). I've tried moved all my little logic that there is into a pool of CPUThreadPoolExecutor, but that doesn't make a lot of difference.

Thanks for your help.

**Comment by dddmello** [comment]
Proxygen can be rebuilt by running ./deps.sh and ./reinstall.sh from within the proxygen dir.  On my local ubuntu vm debug symbols appear to already be present simply following the above instructions (i.e. can load up the folly/proxygen libs using gdb and can inspect debugging info in the wangle lib).

Was there something special the way folly/wangle/proxygen was built?

You should be able to remove proxygen build optimizations by removing '-O3' from proxygen's CXXFLAGS var in its configure.ac.

We use a combination of internal tools and have used some other external ones like 'perf' before.

I don't have any specific ideas why cpu usage would be high right now.

**Comment by michaelpog** [comment]
Yes, you're right. The symbols were there. I was just using a sampling profiler and it did not see all symbols. But Valgrind does see all of them.
I've pretty much taken out all logic out of the http client IOThreadLoopExepcutor threads. I can't confirm with any profiler that I know of. But the CPU on these thread is very high on high Requests/sec. 
I tend to think that there's some kind of contention on a resource, which is guarded by some spin lock. Would you mind telling me if that assumption is plausible?
Thanks

**Comment by dddmello** [comment]
Nothing specific that I'm aware (in regards to a spin lock).  Generally the server waits in the event loop for things to occur and that shouldn't be spiking the CPU.

Would you be able to attach a perf profile and/or a repro?  Does the profiling correctly account for child functions?  I know you mentioned you stripped most of the logic out of the http client threads but also curious whether this is correctly represented in the profiling.

**Comment by michaelpog** [comment]
I was, I kind of isolated it somewhat. 
The profiler wasn't particularly helpful since it was showing me that most of the time is spent in my code, but when I took my code out completely, it didn't matter. 
I am pretty confident it's the combination of the spin lock in the IOThreadLoopExecutor (The one you hit when you call add) and the spin locks of the queues. I changed my architecture from having one http server thread passing requests to 7 http client threads to having 8 http server threads, each one is also an http client. So no passing messages between threads and no contention on the queues. The CPU dropped significantly, and I was able to do better Requests/ sec. However it's still performing worse than Java Vertx (architected the same way). This time I profiled it again with Valgrind and Google Perftools.
Valgrind is pretty useless, it slows down the application SO much... Particularly the IO, since the CPU seems very very low on each thread, but latencies are high.
I tried Google Perftools, and I can't really learn anything from it. Going down the call graph, by the time it gets to "my code" the percentage is very low, so it seems like the cpu is lost all the way through the Proxygen+wangle+folly stack. So Unfortunately I can't point to anything.
The one thing I've noticed when I was profiling with Valgrind is that the time spent in the proxygen. http_parser_parse_url is kind of higher than it should be. 
Unfortunately that's all I could gather

**Comment by AdamDailyMotion** [comment]
I guess it depends on how many cores you are running and how much traffic you are pumping through the system. I've benchmarked the system running 8 cores just running the echo sample at 50% sending 40K messages per second. Do you have a branch you'd like us to look at?

**Comment by michaelpog** [comment]
So my work load is 1 incoming request turns into 32 outgoing requests. I was able to do 2100 incoming requests/sec which means it's 67200 outgoing requests/responses per second. And the CPU is around 620% on 8 cores so that would be 77.5% overall.
I don't know how to compare it to the echo server experiment you just mentioned.
I don't have a branch right now that I  can share with you, however it would not be hard to create one. 
I hope I get time to create one in the future.

**Comment by afrind** [comment]
Is your proxy using TLS or plaintext?  OpenSSL has some silly locking conventions that can slow things down.

**Comment by michaelpog** [comment]
plaintext

**Comment by afrind** [comment]
Just hitting the echo server now (which sends empty response bodies), I'm able to get full CPU saturation over plaintext with 8 cores, running over localhost, with 491k RPS plaintext HTTP/2.  I made a small tweak to send 12k body bytes back as well, and I still get full saturation and 335k RPS.  I'm not seeing a non-CPU bottleneck. This is on a 48 core Intel Xeon CPU E5-2678 v3 @ 2.50GHz.

This is obviously not an apples to apples comparison with your server, which is doing something different.  Are you maintaining persistent connections to your downstream services?  If not, are you doing DNS resolution inline perhaps?

**Comment by michaelpog** [comment]
Yeah, it's hard to compare. I implemented my own connection pool, thanks to your prior help. And I am maintaining connection to my downstream services. I do set an aggressive timeout and the downstream services do timeout sometimes, which is fine, it's part of what I was trying to simulate. No DNS resolution.
I've currently stopped my experiments. I hope if I have more time in the future to get back to it, maybe by then, there will be a connection pool available. Ideally I wanted to provide you with two examples, C++ with Proxygen and Java with Vert.x 3 so you could reproduce the results, but my current repos contain some proprietary logic.

**Comment by afrind** [comment]
I'm going to close this out for now then.  If you do come up with a repro you can share, please let us know.
