### ISSUE TITLE
need an autogen.sh to help autoconf configure

### ISSUE THREAD

**Issue by markhu** [facebook/proxygen#154]
The first time I tried running `autoconf` to generate the `configure` script, it failed with the below error.
Many other projects supply an `autogen.sh` script to help.

```
 ~/git/github.com/proxygen/proxygen (master) $ autoconf

configure.ac:17: error: possibly undefined macro: AM_INIT_AUTOMAKE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:23: error: possibly undefined macro: AC_PROG_LIBTOOL
configure.ac:43: error: possibly undefined macro: AC_MSG_ERROR
configure.ac:212: error: possibly undefined macro: AM_CONDITIONAL
```

I happen to be trying to compile under CentOS6.7 and was able to get past the above by running

    $ sudo yum install autoconf268 autoconf-archive automake libtool cmake gcc-c++

...and am now slogging through the rest of the dependencies in the Ubuntu-specific deps.sh script. Starting with https://github.com/google/glog

**Comment by maxgeorg** [comment]
@markhu, thank you for giving Proxygen library a try!
Talking about autogen.sh, would proxygen/proxygen/deps.sh work for you?
deps.sh pulls proxygen dependencies from GitHub, autoconfigs them and builds them, does the same for proxygen library itself. As part of that process deps.sh runs 'autoreconf -ivf' to generate proxygen/proxygen/configure. You can find more details in proxygen/README.md.
Does  deps.sh solve the problem you run into?

**Comment by maxgeorg** [comment]
BTW which OS did you try it on?

**Comment by markhu** [comment]
I was trying to build under CentOS 6.5 so the Ubuntu-specific deps.sh could not work.
I tried making a deps-centos.sh per https://github.com/facebook/proxygen/pull/155 which got further before stalling out on https://github.com/facebook/folly/issues/564

**Comment by afrind** [comment]
Thanks for you work trying to build deps-centos.sh.  Is the plan to move forward with that, and if so is this issue still blocking that effort?

**Comment by markhu** [comment]
I'm stalled on trying to make it work for CentOS 6. It should be easier under CentOS 7, but my company's Ops department doesn't support that yet.
Anyone is welcome to take over after PR #155 as I have no time to pursue this.

**Comment by afrind** [comment]
Closing out old issues.  Proxygen uses CMake now.  Please reopen if you are having other issues.
