### ISSUE TITLE
Latency spikes

### ISSUE THREAD

**Issue by patrick-hallinan** [facebook/proxygen#161]
We've started using proxygen and are very happy with the latency numbers most of the time but when we are at a high load (like 1000 messages/second) we see latency spikes.  We've tested with your reference echo server and we see the spikes with that alone.  The spikes happen infrequently but regularly (like 0.01% of the time).  Do you know if this is expected behavior?

**Comment by afrind** [comment]
Can you be more specific about the latency spikes?  Is a single request affected or multiple requests during the spike?  What is the amplitude of the spike?  What client are you using to reproduce against the echo server?  Is it possible other resources are being contended on the client or server machines?

**Comment by patrick-hallinan** [comment]
Sorry for not getting back to this.  We determined that proxygen was not the issue.
