### ISSUE TITLE
Problems with httpserver push sample

### ISSUE THREAD

**Issue by plartem** [facebook/proxygen#162]
After running push sample and using
`curl -v http://localhost:11000/`
I get this error
`F0405 16:42:26.128540 19430 PushRequestHandler.cpp:42] Check failed: folly::readFile(kPushFileName.c_str(), gPushBody) Failed to read push file=proxygen/httpserver/samples/push/pusheen.txt
*** Check failure stack trace: ***
    @     0x7f4e9cd05daa  (unknown)
    @     0x7f4e9cd05ce4  (unknown)
    @     0x7f4e9cd056e6  (unknown)
    @     0x7f4e9cd08687  (unknown)
    @           0x4316d9  PushService::PushRequestHandler::PushRequestHandler()
    @           0x425a50  PushRequestHandlerFactory::onRequest()
    @     0x7f4e9d6ea211  proxygen::HTTPServerAcceptor::newHandler()
    @     0x7f4e9d70d97b  proxygen::HTTPDownstreamSession::setupOnHeadersComplete()
    @     0x7f4e9d715b36  proxygen::HTTPSession::onHeadersComplete()
    @     0x7f4e9d76e27a  proxygen::HTTPChecks::onHeadersComplete()
    @     0x7f4e9d74f1bb  proxygen::HTTP1xCodec::onHeadersComplete()
    @     0x7f4e9d7508a2  proxygen::HTTP1xCodec::onHeadersCompleteCB()
    @     0x7f4e9d709890  proxygen::http_parser_execute()
    @     0x7f4e9d74aca0  proxygen::HTTP1xCodec::onIngress()
    @     0x7f4e9d710546  proxygen::HTTPSession::processReadData()
    @     0x7f4e9d7128fc  proxygen::HTTPSession::readDataAvailable()
    @     0x7f4e9d0c3534  folly::AsyncSocket::handleRead()
    @     0x7f4e9d0bb89e  folly::AsyncSocket::ioReady()
    @     0x7f4e9a7a4f24  (unknown)
    @     0x7f4e9d0dae45  folly::EventBase::loopBody()
    @     0x7f4e9d0dcbd6  folly::EventBase::loopForever()
    @     0x7f4e9d7acacd  wangle::IOThreadPoolExecutor::threadRun()
    @     0x7f4e9d7c2367  std::_Mem_fn_base<>::operator()<>()
    @     0x7f4e9d7c04f9  _ZNSt5_BindIFSt7_Mem_fnIMN6wangle18ThreadPoolExecutorEFvSt10shared_ptrINS2_6ThreadEEEEPS2_S5_EE6__callIvIEILm0ELm1EEEET_OSt5tupleIIDpT0_EESt12_Index_tupleIIXspT1_EEE
    @     0x7f4e9d7bea4a  std::_Bind<>::operator()<>()
    @     0x7f4e9d7bc69e  folly::detail::function::FunctionTraits<>::callBig<>()
    @     0x7f4e9c853c30  (unknown)
    @     0x7f4e9c396184  start_thread
    @     0x7f4e9c0c3bed  (unknown)
    @              (nil)  (unknown)
`

**Comment by afrind** [comment]
Looks like the push file (pusheen.txt) is not present at that path relative to your CWD.  Update the path in the code or run from a different directory?

**Comment by plartem** [comment]
@afrind sorry, my bad, hadn't noticed that 🤦‍♂️ . I changed path, recompiled, used curl again and now it stucks here (!downstreamPush_ is true and onRequest stops executing)
```cpp
downstreamPush_ = downstream_->newPushedResponse(new PushHandler);
if (!downstreamPush_) {
      // can't push
      return;
    }
```
how can I fix this?

**Comment by afrind** [comment]
Probably push is not enabled from your client.  Either it is not HTTP/2 or it is not enabling push in the settings frame.

But that looks like a bug in the server.  We should probably continue building the original response even if push is not enabled.  Want to submit a PR?

**Comment by plartem** [comment]
@afrind push increases Request-Number, but don't return any body
```
* Connected to localhost (::1) port 11000 (#0)
> GET /requestLargePush HTTP/1.1
> User-Agent: curl/7.35.0
> Host: localhost:11000
> Accept: */*
> X-PushIt: 1
>
< HTTP/1.1 200 OK
< Request-Number: 9
< Date: Wed, 05 Apr 2017 17:15:13 GMT
< Connection: keep-alive
< Content-Length: 0
<
* Connection #0 to host localhost left intact

```

**Comment by afrind** [comment]
Yes you are right.  A response is returned from onEOM.

**Comment by afrind** [comment]
Curl doesn't really seem to know what to do with a push, but I can see the sample server initiating a push and curl resetting it:

 ./buck-out/gen/proxygen/httpserver/samples/push/push_server  -v 4

 curl -vvv --http2-prior-knowledge -H "X-PushIt: True"  http://localhost:11002/ > /tmp/r

From the server's output:

I0425 09:09:20.459095 105743 PushRequestHandler.cpp:72] sending small push 
V0425 09:09:20.459249 105743 HTTP2PriorityQueue.cpp:513] Updating id=2 with parent=0 and weight=16
V0425 09:09:20.459286 105743 HTTP2Codec.cpp:948] generating PUSH_PROMISE for stream=2

...

V0425 09:09:20.460080 105743 HTTP2Codec.cpp:648] parsing RST_STREAM frame for stream=2 length=4
V0425 09:09:20.460096 105743 HTTP2Codec.cpp:665] RST_STREAM with code=PROTOCOL_ERROR for streamID=2 user-agent=curl/7.51.0
V0425 09:09:20.460104 105743 HTTPSession.cpp:959] stream abort on [downstream = [::1]:61114, [::1]:11002 = local], streamID=2, code=PROTOCOL_ERROR

I'm going to close for now, but feel free to re-open if you have additional questions.

**Comment by brunonishimoto** [comment]
I am having the same problem that it stucks at `if(!downstreamPush_)`. How to fix it?
