### ISSUE TITLE
TestSuite fail in WSL(ubuntu 16.04)

### ISSUE THREAD

**Issue by sicmy** [facebook/proxygen#165]
build is succeeds, but the testsute is fail.

Making check in httpserver
make[1]: Entering directory '/srv/widerplanet/wp_ase_v3/libs/proxygen/proxygen/httpserver'
Making check in .
make[2]: Entering directory '/srv/widerplanet/wp_ase_v3/libs/proxygen/proxygen/httpserver'
make[2]: Nothing to be done for 'check-am'.
make[2]: Leaving directory '/srv/widerplanet/wp_ase_v3/libs/proxygen/proxygen/httpserver'
Making check in samples
make[2]: Entering directory '/srv/widerplanet/wp_ase_v3/libs/proxygen/proxygen/httpserver/samples'
Making check in echo
make[3]: Entering directory '/srv/widerplanet/wp_ase_v3/libs/proxygen/proxygen/httpserver/samples/echo'
Making check in .
make[4]: Entering directory '/srv/widerplanet/wp_ase_v3/libs/proxygen/proxygen/httpserver/samples/echo'
make[4]: Nothing to be done for 'check-am'.
make[4]: Leaving directory '/srv/widerplanet/wp_ase_v3/libs/proxygen/proxygen/httpserver/samples/echo'
make[3]: Leaving directory '/srv/widerplanet/wp_ase_v3/libs/proxygen/proxygen/httpserver/samples/echo'
Making check in proxy
make[3]: Entering directory '/srv/widerplanet/wp_ase_v3/libs/proxygen/proxygen/httpserver/samples/proxy'
Making check in .
make[4]: Entering directory '/srv/widerplanet/wp_ase_v3/libs/proxygen/proxygen/httpserver/samples/proxy'
make[4]: Nothing to be done for 'check-am'.
make[4]: Leaving directory '/srv/widerplanet/wp_ase_v3/libs/proxygen/proxygen/httpserver/samples/proxy'
make[3]: Leaving directory '/srv/widerplanet/wp_ase_v3/libs/proxygen/proxygen/httpserver/samples/proxy'
Making check in push
make[3]: Entering directory '/srv/widerplanet/wp_ase_v3/libs/proxygen/proxygen/httpserver/samples/push'
Making check in .
make[4]: Entering directory '/srv/widerplanet/wp_ase_v3/libs/proxygen/proxygen/httpserver/samples/push'
make[4]: Nothing to be done for 'check-am'.
make[4]: Leaving directory '/srv/widerplanet/wp_ase_v3/libs/proxygen/proxygen/httpserver/samples/push'
make[3]: Leaving directory '/srv/widerplanet/wp_ase_v3/libs/proxygen/proxygen/httpserver/samples/push'
make[3]: Entering directory '/srv/widerplanet/wp_ase_v3/libs/proxygen/proxygen/httpserver/samples'
make[3]: Nothing to be done for 'check-am'.
make[3]: Leaving directory '/srv/widerplanet/wp_ase_v3/libs/proxygen/proxygen/httpserver/samples'
make[2]: Leaving directory '/srv/widerplanet/wp_ase_v3/libs/proxygen/proxygen/httpserver/samples'
Making check in tests
make[2]: Entering directory '/srv/widerplanet/wp_ase_v3/libs/proxygen/proxygen/httpserver/tests'
Making check in .
make[3]: Entering directory '/srv/widerplanet/wp_ase_v3/libs/proxygen/proxygen/httpserver/tests'
make  HTTPServerTests
make[4]: Entering directory '/srv/widerplanet/wp_ase_v3/libs/proxygen/proxygen/httpserver/tests'
depbase=`echo HTTPServerTest.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
g++ -std=gnu++14 -DHAVE_CONFIG_H   -I../../.. -I../../lib/test/googletest-release-1.8.0/googlemock/include -I../../lib/t
est/googletest-release-1.8.0/googletest/include  -I/usr/include   -pthread -DLIBMC_FBTRACE_DISABLE  -Wno-missing-field-i
nitializers -Wno-deprecated -O3 -g -W -Wall -Wextra -Wno-unused-parameter -fno-strict-aliasing -g -O2 -MT HTTPServerTest
.o -MD -MP -MF $depbase.Tpo -c -o HTTPServerTest.o HTTPServerTest.cpp &&\
mv -f $depbase.Tpo $depbase.Po
HTTPServerTest.cpp: In member function ‘virtual void UseExistingSocket_TestWithExistingAsyncServerSocket_Test::TestBody(
)’:
HTTPServerTest.cpp:469:8: warning: unused variable ‘evb’ [-Wunused-variable]
   auto evb = EventBaseManager::get()->getEventBase();
        ^
HTTPServerTest.cpp: In member function ‘virtual void UseExistingSocket_TestWithSocketFd_Test::TestBody()’:
HTTPServerTest.cpp:495:8: warning: unused variable ‘evb’ [-Wunused-variable]
   auto evb = EventBaseManager::get()->getEventBase();
        ^
HTTPServerTest.cpp: In member function ‘virtual void UseExistingSocket_TestWithMultipleSocketFds_Test::TestBody()’:
HTTPServerTest.cpp:521:8: warning: unused variable ‘evb’ [-Wunused-variable]
   auto evb = EventBaseManager::get()->getEventBase();
        ^
/bin/bash ../../libtool  --tag=CXX   --mode=link g++ -std=gnu++14  -pthread -DLIBMC_FBTRACE_DISABLE  -Wno-missing-field-
initializers -Wno-deprecated -O3 -g -W -Wall -Wextra -Wno-unused-parameter -fno-strict-aliasing -g -O2   -o HTTPServerTe
sts HTTPServerTest.o ../libproxygenhttpserver.la ../../lib/test/libtestmain.la ../../httpclient/samples/curl/libproxygen
curl.la -lwangle -lfolly -lz -lssl -lcrypto -lcap -levent -lgflags -lglog  -L/usr/lib64 -lpthread -pthread -lfolly -lglo
g -ldouble-conversion -lboost_system -lboost_thread
libtool: link: g++ -std=gnu++14 -pthread -DLIBMC_FBTRACE_DISABLE -Wno-missing-field-initializers -Wno-deprecated -O3 -g
-W -Wall -Wextra -Wno-unused-parameter -fno-strict-aliasing -g -O2 -o .libs/HTTPServerTests HTTPServerTest.o -pthread  .
./.libs/libproxygenhttpserver.so ../../lib/test/.libs/libtestmain.a -L/usr/lib64 -lboost_context -lboost_program_options
 -lboost_filesystem -lboost_regex -lboost_chrono -lsnappy ../../httpclient/samples/curl/.libs/libproxygencurl.a /srv/wid
erplanet/wp_ase_v3/libs/proxygen/proxygen/lib/.libs/libproxygenlib.a -lwangle -lz -lssl -lcrypto -lcap -levent -lgflags
-lpthread /usr/local/lib/libfolly.so -lglog -ldouble-conversion -lboost_system -lboost_thread -pthread
make[4]: Leaving directory '/srv/widerplanet/wp_ase_v3/libs/proxygen/proxygen/httpserver/tests'
make  check-TESTS
make[4]: Entering directory '/srv/widerplanet/wp_ase_v3/libs/proxygen/proxygen/httpserver/tests'
make[5]: Entering directory '/srv/widerplanet/wp_ase_v3/libs/proxygen/proxygen/httpserver/tests'
FAIL: HTTPServerTests
============================================================================
Testsuite summary for proxygen 32.0
============================================================================
# TOTAL: 1
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
============================================================================
See httpserver/tests/test-suite.log
============================================================================
Makefile:765: recipe for target 'test-suite.log' failed
make[5]: *** [test-suite.log] Error 1
make[5]: Leaving directory '/srv/widerplanet/wp_ase_v3/libs/proxygen/proxygen/httpserver/tests'
Makefile:871: recipe for target 'check-TESTS' failed
make[4]: *** [check-TESTS] Error 2
make[4]: Leaving directory '/srv/widerplanet/wp_ase_v3/libs/proxygen/proxygen/httpserver/tests'
Makefile:969: recipe for target 'check-am' failed
make[3]: *** [check-am] Error 2
make[3]: Leaving directory '/srv/widerplanet/wp_ase_v3/libs/proxygen/proxygen/httpserver/tests'
Makefile:658: recipe for target 'check-recursive' failed
make[2]: *** [check-recursive] Error 1
make[2]: Leaving directory '/srv/widerplanet/wp_ase_v3/libs/proxygen/proxygen/httpserver/tests'
Makefile:560: recipe for target 'check-recursive' failed
make[1]: *** [check-recursive] Error 1
make[1]: Leaving directory '/srv/widerplanet/wp_ase_v3/libs/proxygen/proxygen/httpserver'
Makefile:418: recipe for target 'check-recursive' failed
make: *** [check-recursive] Error 1

**Comment by dddmello** [comment]
Hi - is WSL here referring to 'Windows Subsystem for Linux'?

Anyhow I just fresh installed an ubuntu 16.04.2 image and built proxygen with no problem - including the running of associated unit tests.

If this is indeed a problem specific to the use case when running from WSL as defined above, this is not technically supported.  I do not believe we have the resources to actively validate such a configuration moving forward.

If I've misinterpreted please provide some more information if possible regarding any possible local changes you may have or anything different from a standard ubuntu system configuration.

**Comment by sicmy** [comment]
thankyou~!!
