### ISSUE TITLE
Not able to compile this with GCC version 4.9.2. 

### ISSUE THREAD

**Issue by nginxsantos** [facebook/proxygen#167]
I heard from this forum that C++14 is required to compile this and C++14  comes with gcc version 6.0 and have a restriction of going to gcc version 6.0 which comes with debian 9. 

Any help?

**Comment by Orvid** [comment]
GCC 4.9 should be sufficient to compile Proxygen, and will continue to be supported for at least the next year. What error are you seeing?

**Comment by badarihp** [comment]
Hi,
 One of the issue I am facing is 
$ ./configure
./configure: line 2672: syntax error near unexpected token `proxygen-config.h,'
./configure: line 2672: `AX_PREFIX_CONFIG_H(proxygen-config.h, proxygen, config.h)'

Not sure how to resolve this, getting this error on latest release build of proxygen.

**Comment by badarihp** [comment]
I faced a crash ... while trying to start EchoServer which is compiled with gcc 4.9.

Program terminated with signal SIGSEGV, Segmentation fault.^M
#**0  construct<wangle::IOThreadPoolExecutor, unsigned long&, std::shared_ptr<wangle::NamedThreadFactory> > (__p=0x3463e80, this=<optimized out>) at /usr/include/c++/4.9/ext/new_allocator.h:120^M
120             { ::new((void *)__p) _Up(std::forward<_Args>(__args)...); }^M
(gdb)
bt^M
#0  construct<wangle::IOThreadPoolExecutor, unsigned long&, std::shared_ptr<wangle::NamedThreadFactory> > (__p=0x3463e80, this=<optimized out>) at /usr/include/c++/4.9/ext/new_allocator.h:120^M**
#1  _S_construct<wangle::IOThreadPoolExecutor, unsigned long&, std::shared_ptr<wangle::NamedThreadFactory> > (__p=0x3463e80, __a=...) at /usr/include/c++/4.9/bits/alloc_traits.h:253^M
#2  construct<wangle::IOThreadPoolExecutor, unsigned long&, std::shared_ptr<wangle::NamedThreadFactory> > (__p=0x3463e80, __a=...) at /usr/include/c++/4.9/bits/alloc_traits.h:399^M
#3  _Sp_counted_ptr_inplace<unsigned long&, std::shared_ptr<wangle::NamedThreadFactory> > (__a=..., this=0x3463e00) at /usr/include/c++/4.9/bits/shared_ptr_base.h:515^M
#4  construct<std::_Sp_counted_ptr_inplace<wangle::IOThreadPoolExecutor, std::allocator<wangle::IOThreadPoolExecutor>, (__gnu_cxx::_Lock_policy)2>, std::allocator<wangle::IOThreadPoolExecutor> const, unsigned long&, std::shared_ptr<wangle::NamedThreadFactory> > (__p=0x3463e00, this=<synthetic pointer>) at /usr/include/c++/4.9/ext/new_allocator.h:120^M
#5  _S_construct<std::_Sp_counted_ptr_inplace<wangle::IOThreadPoolExecutor, std::allocator<wangle::IOThreadPoolExecutor>, (__gnu_cxx::_Lock_policy)2>, std::allocator<wangle::IOThreadPoolExecutor> const, unsigned long&, std::shared_ptr<wangle::NamedThreadFactory> > (__p=<optimized out>, __a=<synthetic pointer>) at /usr/include/c++/4.9/bits/alloc_traits.h:253^M
#6  construct<std::_Sp_counted_ptr_inplace<wangle::IOThreadPoolExecutor, std::allocator<wangle::IOThreadPoolExecutor>, (__gnu_cxx::_Lock_policy)2>, std::allocator<wangle::IOThreadPoolExecutor> const, unsigned long&, std::shared_ptr<wangle::NamedThreadFactory> > (__p=<optimized out>, __a=<synthetic pointer>) at /usr/include/c++/4.9/bits/alloc_traits.h:399^M
#7  __shared_count<wangle::IOThreadPoolExecutor, std::allocator<wangle::IOThreadPoolExecutor>, unsigned long&, std::shared_ptr<wangle::NamedThreadFactory> > (__a=..., this=0x7f8f4c413678) at /usr/include/c++/4.9/bits/shared_ptr_base.h:619^M
#8  std::__shared_ptr<wangle::IOThreadPoolExecutor, (__gnu_cxx::_Lock_policy)2>::__shared_ptr<std::allocator<wangle::IOThreadPoolExecutor>, unsigned long&, std::shared_ptr<wangle::NamedThreadFactory> >(std::_Sp_make_shared_tag, std::allocator<wangle::IOThreadPoolExecutor> const&, unsigned long&, std::shared_ptr<wangle::NamedThreadFactory>&&) (this=this@entry=0x7f8f4c413670, __tag=..., __a=...) at /usr/include/c++/4.9/bits/shared_ptr_base.h:1090^M
#9  0x00007f8f619f6aa9 in shared_ptr<std::allocator<wangle::IOThreadPoolExecutor>, unsigned long&, std::shared_ptr<wangle::NamedThreadFactory> > (__a=..., __tag=..., this=0x7f8f4c413670) at /usr/include/c++/4.9/bits/shared_ptr.h:316^M
#10 allocate_shared<wangle::IOThreadPoolExecutor, std::allocator<wangle::IOThreadPoolExecutor>, unsigned long&, std::shared_ptr<wangle::NamedThreadFactory> > (__a=...) at /usr/include/c++/4.9/bits/shared_ptr.h:588^M
#11 make_shared<wangle::IOThreadPoolExecutor, unsigned long&, std::shared_ptr<wangle::NamedThreadFactory> > () at /usr/include/c++/4.9/bits/shared_ptr.h:604^M
#12 proxygen::HTTPServer::start(std::function<void ()>, std::function<void (std::__exception_ptr::exception_ptr)>) (this=0x7f8f4cc13330, onSuccess=..., onError=...) at HTTPServer.cpp:119^M
#13 0x00007f8f61d84b26 in __static_initialization_and_destruction_0 (__initialize_p=0, __priority=0) at /anroot/projects/tos/.host/x86_64-linux-gnu/inc/tos/scheduler/FMClient.h:237^M
#14 0x00007f8f61d862c6 in std::_Sp_counted_ptr_inplace<std::thread::_Impl<std::_Bind_simple<startServer(int, char**)::<lambda()>()> >, std::allocator<std::thread::_Impl<std::_Bind_simple<startServer(int, char**)::<lambda()>()> > >, (__gnu_cxx::_Lock_policy)2u>::_Sp_counted_ptr_inplace<std::_Bind_simple<startServer(int, char**)::<lambda()>()> >(std::allocator<std::thread::_Impl<std::_Bind_simple<startServer(int, char**)::<lambda()>()> > >) (this=0x346e6f0, __a=...) at /usr/include/c++/4.9/bits/shared_ptr_base.h:511^M

**Comment by lnicco** [comment]
@nginxsantos any update ? you mentioned having troubles to build proxygen with gcc 4.9.2, is that still true ? do you have any update, or can you share a log of the build error ?

@badarihp your issue is a runtime issue, let's handle it separately from this one
https://github.com/facebook/proxygen/issues/171

**Comment by nginxsantos** [comment]
I was able to do so.Thanks.
