### ISSUE TITLE
Support OpenSSL 1.1.0

### ISSUE THREAD

**Issue by mmlac** [facebook/proxygen#168]
In order to support OpenSSL 1.1.0, configure.ac needs to use `OPENSSL_init_ssl` instead of `SSL_library_init`.

Just replacing it worked for me, but I don't know enough about autoconf to make a switch like shown below to support both.

It builds with this change and seems to compile my project, but I have not done any deeper validation, so there might be more impact within the proxygen codebase.

From https://wiki.openssl.org/index.php/Library_Initialization:
```
libssl should be initialized with calls to SSL_library_init and SSL_load_error_strings. If your program is multi-threaded, you should install the static locks. If you need (or don't need) configuration from openssl.cnf, then you should call OPENSSL_config or OPENSSL_noconfig.
If you are supporting both pre-1.1.0 and post-1.1.0 version of the OpenSSL library and you want to take control of SSL_library_init and OPENSSL_init_ssl, then you can perform:
#include <openssl/opensslv.h>
...

#if OPENSSL_VERSION_NUMBER < 0x10100000L
SSL_library_init();
#else
OPENSSL_init_ssl(0, NULL);
#endif

```

**Comment by w-o-o** [comment]
interesting, proxygen relies on folly for SSL operations.  Besides the autoconf, do we also need to update folly part https://github.com/facebook/folly/blob/master/folly/io/async/SSLContext.cpp#L848?

**Comment by anirudhvr** [comment]
Folly already compiles and runs fine with 1.1.0. 

@mmlac I'm not sure why SSL_library_init is a problem because 1.1.0 does this
# define SSL_library_init() OPENSSL_init_ssl(0, NULL)

**Comment by mmlac** [comment]
I am not quite sure, I updated my Arch box and could no longer build proxygen without this change in the `configure.ac` file. Folly / Wangle built fine without any changes. Folly also uses CMake, so their detection algorithm might be different than Autoconf? (sorry, not very versed with C++ build systems)

**Comment by Orvid** [comment]
Folly only uses CMake on Windows. It's autoconf for everything else :)

**Comment by portsip** [comment]
@Orvid does proxygen support windows now ?

**Comment by lnicco** [comment]
not an issue anymore. closing
