### ISSUE TITLE
Could a http server with paths example be provided ?

### ISSUE THREAD

**Issue by GuacheSuede** [facebook/proxygen#169]
A typical web server like, serves html files and does data retrievals typically of a server project

 Thank You

**Comment by w-o-o** [comment]
Hello @GuacheSuede ,  did you check out [the sample http server](https://github.com/facebook/proxygen/blob/master/proxygen/httpserver/samples/echo/EchoServer.cpp)? this seems close to your request.   If this is not sufficient, let us know what you are interested.

**Comment by GuacheSuede** [comment]
Hi @w-o-o ,
I think these 3 points would be sufficient to allow a more complete example

- Routing
- File Serving
- JSON Returns (Not important)

**Comment by afrind** [comment]
check out the static webserver example.  I'm not sure exactly what you mean by routing here.  If you mean you want to proxy a request to another server, see the proxy example.  Feel free to reopen here if it's still unclear.
