### ISSUE TITLE
Crash while running EchoServer (built with g++ 4.9.2)

### ISSUE THREAD

**Issue by badarihp** [facebook/proxygen#171]
Hi,
 Got Crash while trying to start EchoServer compiled with g++ 4.9.2 .

Program terminated with signal SIGSEGV, Segmentation fault.^M
#0  construct<wangle::IOThreadPoolExecutor, unsigned long&, std::shared_ptr<wangle::NamedThreadFactory> > (__p=0x3463e80, this=<optimized out>) at /usr/include/c++/4.9/ext/new_allocator.h:120^M
120             { ::new((void *)__p) _Up(std::forward<_Args>(__args)...); }^M
(gdb)
bt^M
#0  construct<wangle::IOThreadPoolExecutor, unsigned long&, std::shared_ptr<wangle::NamedThreadFactory> > (__p=0x3463e80, this=<optimized out>) at /usr/include/c++/4.9/ext/new_allocator.h:120^M
#1  _S_construct<wangle::IOThreadPoolExecutor, unsigned long&, std::shared_ptr<wangle::NamedThreadFactory> > (__p=0x3463e80, __a=...) at /usr/include/c++/4.9/bits/alloc_traits.h:253^M
#2  construct<wangle::IOThreadPoolExecutor, unsigned long&, std::shared_ptr<wangle::NamedThreadFactory> > (__p=0x3463e80, __a=...) at /usr/include/c++/4.9/bits/alloc_traits.h:399^M
#3  _Sp_counted_ptr_inplace<unsigned long&, std::shared_ptr<wangle::NamedThreadFactory> > (__a=..., this=0x3463e00) at /usr/include/c++/4.9/bits/shared_ptr_base.h:515^M
#4  construct<std::_Sp_counted_ptr_inplace<wangle::IOThreadPoolExecutor, std::allocator<wangle::IOThreadPoolExecutor>, (__gnu_cxx::_Lock_policy)2>, std::allocator<wangle::IOThreadPoolExecutor> const, unsigned long&, std::shared_ptr<wangle::NamedThreadFactory> > (__p=0x3463e00, this=<synthetic pointer>) at /usr/include/c++/4.9/ext/new_allocator.h:120^M
#5  _S_construct<std::_Sp_counted_ptr_inplace<wangle::IOThreadPoolExecutor, std::allocator<wangle::IOThreadPoolExecutor>, (__gnu_cxx::_Lock_policy)2>, std::allocator<wangle::IOThreadPoolExecutor> const, unsigned long&, std::shared_ptr<wangle::NamedThreadFactory> > (__p=<optimized out>, __a=<synthetic pointer>) at /usr/include/c++/4.9/bits/alloc_traits.h:253^M
#6  construct<std::_Sp_counted_ptr_inplace<wangle::IOThreadPoolExecutor, std::allocator<wangle::IOThreadPoolExecutor>, (__gnu_cxx::_Lock_policy)2>, std::allocator<wangle::IOThreadPoolExecutor> const, unsigned long&, std::shared_ptr<wangle::NamedThreadFactory> > (__p=<optimized out>, __a=<synthetic pointer>) at /usr/include/c++/4.9/bits/alloc_traits.h:399^M
#7  __shared_count<wangle::IOThreadPoolExecutor, std::allocator<wangle::IOThreadPoolExecutor>, unsigned long&, std::shared_ptr<wangle::NamedThreadFactory> > (__a=..., this=0x7f8f4c413678) at /usr/include/c++/4.9/bits/shared_ptr_base.h:619^M
#8  std::__shared_ptr<wangle::IOThreadPoolExecutor, (__gnu_cxx::_Lock_policy)2>::__shared_ptr<std::allocator<wangle::IOThreadPoolExecutor>, unsigned long&, std::shared_ptr<wangle::NamedThreadFactory> >(std::_Sp_make_shared_tag, std::allocator<wangle::IOThreadPoolExecutor> const&, unsigned long&, std::shared_ptr<wangle::NamedThreadFactory>&&) (this=this@entry=0x7f8f4c413670, __tag=..., __a=...) at /usr/include/c++/4.9/bits/shared_ptr_base.h:1090^M
#9  0x00007f8f619f6aa9 in shared_ptr<std::allocator<wangle::IOThreadPoolExecutor>, unsigned long&, std::shared_ptr<wangle::NamedThreadFactory> > (__a=..., __tag=..., this=0x7f8f4c413670) at /usr/include/c++/4.9/bits/shared_ptr.h:316^M
#10 allocate_shared<wangle::IOThreadPoolExecutor, std::allocator<wangle::IOThreadPoolExecutor>, unsigned long&, std::shared_ptr<wangle::NamedThreadFactory> > (__a=...) at /usr/include/c++/4.9/bits/shared_ptr.h:588^M
#11 make_shared<wangle::IOThreadPoolExecutor, unsigned long&, std::shared_ptr<wangle::NamedThreadFactory> > () at /usr/include/c++/4.9/bits/shared_ptr.h:604^M
#12 proxygen::HTTPServer::start(std::function<void ()>, std::function<void (std::__exception_ptr::exception_ptr)>) (this=0x7f8f4cc13330, onSuccess=..., onError=...) at HTTPServer.cpp:119^M
#13 0x00007f8f61d84b26 in __static_initialization_and_destruction_0 (__initialize_p=0, __priority=0) at /anroot/projects/tos/.host/x86_64-linux-gnu/inc/tos/scheduler/FMClient.h:237^M
#14 0x00007f8f61d862c6 in std::_Sp_counted_ptr_inplace<std::thread::_Impl<std::_Bind_simple<startServer(int, char**)::<lambda()>()> >, std::allocator<std::thread::_Impl<std::_Bind_simple<startServer(int, char**)::<lambda()>()> > >, (__gnu_cxx::_Lock_policy)2u>::_Sp_counted_ptr_inplace<std::_Bind_simple<startServer(int, char**)::<lambda()>()> >(std::allocator<std::thread::_Impl<std::_Bind_simple<startServer(int, char**)::<lambda()>()> > >) (this=0x346e6f0, __a=...) at /usr/include/c++/4.9/bits/shared_ptr_base.h:511^M

Any quick fix for this issue ?

**Comment by lnicco** [comment]
thanks for reporting this crash @badarihp I will need to reproduce it first, so if you could share the build command you used that will help

**Comment by badarihp** [comment]
Hi ,
 I used following command to build the echo server:
g++ -std=c++14 -lcurl -lproxygenhttpserver -lfolly  -lglog -lgflags -pthread  -g $ALL_SRC

**Comment by lnicco** [comment]
thanks @badarihp, I am trying to reproduce the issue locally with no success. 
I am on 
Ubuntu 14.04.5 LTS, 
gcc 4.9.4-2ubuntu1~14.04.1
Is upgrading an option for you ?

**Comment by badarihp** [comment]
We were able to narrow down the issue, in our environment each thread has limited stack space, so creating the HTTPServerOptions and HTTPServer objects on the stack was leading to this issue.

**Comment by lnicco** [comment]
thanks @badarihp! 
sorry I couldn't reproduce that, so I wasn't that much of a help.

perhaps next time, attaching a core dump could help us troubleshooting. 
glad it's fixed
