### ISSUE TITLE
failed to compile with openssl-1.1.0

### ISSUE THREAD

**Issue by zj5121** [facebook/proxygen#172]
OS: arch linux
Openssl; 1.1.0

Failed to run ./configure, because SSL_Library_init is replaced by OPENSSL_Library_init.
although SSL_Library_init is defined as a macro to OPENSSL_LIbrary_init in libssl, but the configure script tried to declare it as an extern function!

**Comment by lnicco** [comment]
Hi @zj5121, 
We currently support Ubuntu only (with CentOS in the works thanks to a Pull Request).

That being said, if you could please post here the full error message we can try to help you in case is only related to openssl

**Comment by zj5121** [comment]
Sorry, it should be OPENSSL_init_ssl in new openssl lib, if I changed configure.ac from SSL_library_init to OPENSSL_init_ssl, it's ok. 
I'm not so deeply know how auto-tools works, if there is a way to 'OR' the cases of old or new version of openssl, that should be better.
Thanks!

**Comment by anirudhvr** [comment]
@zj5121 Thanks for pointing this out. @lnicco @afrind can we just change the check to SSL_accept() or somesuch that exists on all OpenSSL clones? Even SSLeay_version() is a macro in 1.1.0

**Comment by anirudhvr** [comment]
@zj5121 can you check if another non-macro function such as 'SSL_SESSION_new' works instead of SSL_library_init with 1.1.0?

**Comment by lnicco** [comment]
@zj5121, based on a discussion with @anirudhvr we agreed that using SSL_SESSION_new should fix the build for openssl 1.1.0 and keep it all working for previous versions.

please reopen this issue in case that's not working
