### ISSUE TITLE
CONNECT method has defined body?

### ISSUE THREAD

**Issue by vinniefalco** [facebook/proxygen#173]
According to
```
BodyAllowed isRequestBodyAllowed(boost::optional<HTTPMethod> method) {
  if (method == HTTPMethod::TRACE) {
    return BodyAllowed::NOT_ALLOWED;
  }
  if (method == HTTPMethod::OPTIONS || method == HTTPMethod::POST ||
      method == HTTPMethod::PUT || method == HTTPMethod::CONNECT) {
    return BodyAllowed::DEFINED;
  }
  return BodyAllowed::NOT_DEFINED;
}
```

`BodyAllowed` is `DEFINED` for `HTTPMethod::CONNECT`. But, from https://tools.ietf.org/html/rfc7231#section-4.3.6

>A payload within a CONNECT request message has no defined semantics; sending a payload body on a CONNECT request might cause some existing implementations to reject the request.

Why does proxygen treat the payload as defined?

**Comment by maxgeorg** [comment]
@vinniefalco, thank you for reporting this problem! The fix should be on GitHub by now.

**Comment by vinniefalco** [comment]
Glad I asked!

**Comment by w-o-o** [comment]
@vinniefalco  could you close the issue if it is fixed?
