### ISSUE TITLE
folly::init()

### ISSUE THREAD

**Issue by patrick-hallinan** [facebook/proxygen#178]
We don't know if we have an issue or not but a couple of month ago we started segfaulting when we called out to upstream servers in a request handler.  The segfault was from folly logging a fatal error and saying that we probably weren't calling folly::init().  This is the folly code :

https://github.com/facebook/folly/blob/master/folly/Singleton-inl.h#L233-#L247

So we added a call to folly::init() at startup things appear to be fine but we don't understand what changed.  None of the samples call folly::init() and they all work fine.  One difference that we have is a connection pool.  We've spent some hours digging through the proxygen code to try to understand if we are doing anything wrong but so far everything seems fine.

**Comment by w-o-o** [comment]
@patrick-hallinan ,  can you paste a stack trace?  Eyeballing the source code is difficult.

**Comment by ikobzar** [comment]
Just making sure you run ./deps.sh && ./reinstall.sh in case if you rebased proxygen.

**Comment by patrick-hallinan** [comment]
What I did was create a new virtual machine with Ubuntu 16.04 and did a fresh install of everything.

**Comment by patrick-hallinan** [comment]
This is the stack trace:

I0717 15:03:39.950933  1121 RequestHandler.cpp:64] onEOM()
I0717 15:03:39.951020  1121 RequestHandler.cpp:110] onEOM() Send Requests
F0717 15:03:39.951210  1121 Singleton-inl.h:241] Singleton N5folly21ThreadWheelTimekeeperE requested before registrationComplete() call.
This usually means that either main() never called folly::init, or singleton was requested before main() (which is not allowed).
*** Check failure stack trace: ***
    @     0x7f4b596d75cd  google::LogMessage::Fail()
    @     0x7f4b596d9433  google::LogMessage::SendToLog()
    @     0x7f4b596d715b  google::LogMessage::Flush()
    @     0x7f4b596d9e1e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f4b59a7e9dc  folly::detail::SingletonHolder<>::createInstance()
    @     0x7f4b59a77cc0  folly::detail::getTimekeeperSingleton()
    @           0x4b7872  folly::Future<>::within<>()
    @           0x4b5fb1  folly::Future<>::within()
    @           0x4a84cc  _ZN5folly6FutureISt4pairISt10unique_ptrIN8proxygen11HTTPMessageESt14default_deleteIS4_EES2_INS_5IOBufES5_IS8_EEEE9onTimeoutIZN11ConnManager14RequestHandler5onEOMEvEUlvE_EESC_NSt6chrono8durationIlSt5ratioILl1ELl1000EEEEOT_PNS_10TimekeeperE
    @           0x4a6864  ConnManager::RequestHandler::onEOM()
    @     0x7f4b5a176278  proxygen::HTTPTransaction::processIngressEOM()
    @     0x7f4b5a17666d  proxygen::HTTPTransaction::onIngressEOM()
    @     0x7f4b5a165c0f  proxygen::HTTPSession::onMessageComplete()
    @     0x7f4b5a19a017  proxygen::HTTP1xCodec::onMessageComplete()
    @     0x7f4b5a19a1ea  proxygen::HTTP1xCodec::onMessageCompleteCB()
    @     0x7f4b5a154131  proxygen::http_parser_execute()
    @     0x7f4b5a198290  proxygen::HTTP1xCodec::onIngress()
    @     0x7f4b5a15c76e  proxygen::HTTPSession::processReadData()
    @     0x7f4b5a15ee10  proxygen::HTTPSession::readDataAvailable()
    @     0x7f4b59ac1dae  folly::AsyncSocket::handleRead()
    @     0x7f4b59ab9daa  folly::AsyncSocket::ioReady()
    @     0x7f4b55b8b4c9  event_base_loop
    @     0x7f4b59ada2a0  folly::EventBase::loopBody()
    @     0x7f4b59adc046  folly::EventBase::loopForever()
    @     0x7f4b5a1fca3f  wangle::IOThreadPoolExecutor::threadRun()
    @     0x7f4b5a213e6e  std::_Mem_fn_base<>::operator()<>()
    @     0x7f4b5a211de8  _ZNSt5_BindIFSt7_Mem_fnIMN6wangle18ThreadPoolExecutorEFvSt10shared_ptrINS2_6ThreadEEEEPS2_S5_EE6__callIvIEILm0ELm1EEEET_OSt5tupleIIDpT0_EESt12_Index_tupleIIXspT1_EEE
    @     0x7f4b5a20ffa7  std::_Bind<>::operator()<>()
    @     0x7f4b5a20da76  folly::detail::function::FunctionTraits<>::callBig<>()
    @     0x7f4b57fe7c80  (unknown)
    @     0x7f4b592956ba  start_thread
    @     0x7f4b57a563dd  clone
Aborted (core dumped)

**Comment by maxgeorg** [comment]
@patrick-hallinan, according to the stack you posted, there is some code in ConnManager::RequestHandler::onEOM() is trying to instantiate a Timekeeper singleton from folly. These days folly singleton infrastructure is checking that folly::init() was called when application started. I guess there was a relatively recent (April 2017) change in folly promoting the error message in the Singleton-inl.h code snapshot you referred above from LOG(DFATAL) to LOG(FATAL).
I guess the samples don't run into this problem since they don't try to instantiate any singletons. Or they use an old folly version.

**Comment by patrick-hallinan** [comment]
Thanks!
