### ISSUE TITLE
Consider removing ./deps.sh reliance on sudo

### ISSUE THREAD

**Issue by voznesenskym** [facebook/proxygen#179]
I would prefer to leave sudo behind, as we plan on using proxygen within a docker container. While I could always apt-get it, it seems closer to a hack then a real solution.

**Comment by voznesenskym** [comment]
Ill do it this weekend. Maybe fix the mac stuff while we are at it.

**Comment by w-o-o** [comment]
@voznesenskym  did you figure that out?  If so, could you send a PR for us

**Comment by voznesenskym** [comment]
Yeah I did. Let me clarify what Uber's contribution policy is these days
and get back to you.

**Comment by jbeshay** [comment]
This is a very old issue but the recommendation to avoid sudo right now is to use `--no-install-dependencies` in the build.sh script and handle that manually outside of the script.
