### ISSUE TITLE
Ubuntu 14.04 Installation Failure

### ISSUE THREAD

**Issue by Maktm** [facebook/proxygen#184]
Hi,

I'm trying to set up proxygen on an Ubuntu 14.04 VPS but I get the following error messages when running `./deps.sh` with gcc 4.8.4:

        In file included from ./../folly/Assume.h:21:0,
                        from Assume.cpp:17:
        ./../folly/Portability.h:53:5: error: 'max_align_t' is not a member of 'std'
            std::max_align_t,
            ^
        ./../folly/Portability.h:53:5: note: suggested alternative:
        In file included from /usr/include/c++/4.8/cstddef:42:0,
                        from ./../folly/Portability.h:21,
                        from ./../folly/Assume.h:21,
                        from Assume.cpp:17:
        /usr/lib/gcc/x86_64-linux-gnu/4.8/include/stddef.h:425:3: note:   'max_align_t'
        } max_align_t;
        ^
        In file included from ./../folly/Assume.h:21:0,
                        from Assume.cpp:17:
        ./../folly/Portability.h:53:5: error: 'max_align_t' is not a member of 'std'
            std::max_align_t,
            ^
        ./../folly/Portability.h:53:5: note: suggested alternative:
        In file included from /usr/include/c++/4.8/cstddef:42:0,
                        from ./../folly/Portability.h:21,
                        from ./../folly/Assume.h:21,
                        from Assume.cpp:17:
        /usr/lib/gcc/x86_64-linux-gnu/4.8/include/stddef.h:425:3: note:   'max_align_t'
        } max_align_t;
        ^
        In file included from ./../folly/Assume.h:21:0,
                        from Assume.cpp:17:
        ./../folly/Portability.h:66:19: error: template argument 1 is invalid
            std::nullptr_t>;
                        ^
        ./../folly/Portability.h:69:40: error: 'folly::detail::max_basic_alignment' has not been declared
        constexpr size_t max_align_v = detail::max_basic_alignment::value;
                                                ^
        ./../folly/Portability.h:101:29: error: requested alignment is not an integer constant
        struct alignas(max_align_v) max_align_t {};
                                    ^
        In file included from ./../folly/CpuId.h:21:0,
                        from Checksum.cpp:19:
        ./../folly/Portability.h:53:5: error: 'max_align_t' is not a member of 'std'
            std::max_align_t,
            ^
        ./../folly/Portability.h:53:5: note: suggested alternative:
        In file included from /usr/include/c++/4.8/cstddef:42:0,
                        from ./../folly/Checksum.h:20,
                        from Checksum.cpp:17:
        /usr/lib/gcc/x86_64-linux-gnu/4.8/include/stddef.h:425:3: note:   'max_align_t'
        } max_align_t;
        ^
        In file included from ./../folly/CpuId.h:21:0,
                        from Checksum.cpp:19:
        ./../folly/Portability.h:53:5: error: 'max_align_t' is not a member of 'std'
            std::max_align_t,
            ^
        ./../folly/Portability.h:53:5: note: suggested alternative:
        In file included from /usr/include/c++/4.8/cstddef:42:0,
                        from ./../folly/Checksum.h:20,
                        from Checksum.cpp:17:
        /usr/lib/gcc/x86_64-linux-gnu/4.8/include/stddef.h:425:3: note:   'max_align_t'
        } max_align_t;
        ^
        In file included from ./../folly/CpuId.h:21:0,
                        from Checksum.cpp:19:
        ./../folly/Portability.h:66:19: error: template argument 1 is invalid
            std::nullptr_t>;
                        ^
        ./../folly/Portability.h:69:40: error: 'folly::detail::max_basic_alignment' has not been declared
        constexpr size_t max_align_v = detail::max_basic_alignment::value;
                                                ^
        ./../folly/Portability.h:101:29: error: requested alignment is not an integer constant
        struct alignas(max_align_v) max_align_t {};
                                    ^
        In file included from ./../folly/Function.h:227:0,
                        from ./../folly/Executor.h:21,
                        from Executor.cpp:17:
        ./../folly/Portability.h:53:5: error: 'max_align_t' is not a member of 'std'
            std::max_align_t,
            ^
        ./../folly/Portability.h:53:5: note: suggested alternative:
        In file included from /usr/include/c++/4.8/cstddef:42:0,
                        from ./../folly/Portability.h:21,
                        from ./../folly/Function.h:227,
                        from ./../folly/Executor.h:21,
                        from Executor.cpp:17:
        /usr/lib/gcc/x86_64-linux-gnu/4.8/include/stddef.h:425:3: note:   'max_align_t'
        } max_align_t;
        ^
        In file included from ./../folly/Function.h:227:0,
                        from ./../folly/Executor.h:21,
                        from Executor.cpp:17:
        ./../folly/Portability.h:53:5: error: 'max_align_t' is not a member of 'std'
            std::max_align_t,
            ^
        ./../folly/Portability.h:53:5: note: suggested alternative:
        In file included from /usr/include/c++/4.8/cstddef:42:0,
                        from ./../folly/Portability.h:21,
                        from ./../folly/Function.h:227,
                        from ./../folly/Executor.h:21,
                        from Executor.cpp:17:
        /usr/lib/gcc/x86_64-linux-gnu/4.8/include/stddef.h:425:3: note:   'max_align_t'
        } max_align_t;
        ^
        In file included from ./../folly/Function.h:227:0,
                        from ./../folly/Executor.h:21,
                        from Executor.cpp:17:
        ./../folly/Portability.h:66:19: error: template argument 1 is invalid
            std::nullptr_t>;
                        ^
        ./../folly/Portability.h:69:40: error: 'folly::detail::max_basic_alignment' has not been declared
        constexpr size_t max_align_v = detail::max_basic_alignment::value;
                                                ^
        ./../folly/Portability.h:101:29: error: requested alignment is not an integer constant
        struct alignas(max_align_v) max_align_t {};
                                    ^
        make[2]: *** [Assume.lo] Error 1
        make[2]: *** Waiting for unfinished jobs....
        In file included from ./../folly/Assume.h:21:0,
                        from ./../folly/ExceptionWrapper.h:32,
                        from ExceptionWrapper.cpp:16:
        ./../folly/Portability.h:53:5: error: 'max_align_t' is not a member of 'std'
            std::max_align_t,
            ^
        ./../folly/Portability.h:53:5: note: suggested alternative:
        In file included from /usr/include/c++/4.8/cstddef:42:0,
                        from ./../folly/Portability.h:21,
                        from ./../folly/Assume.h:21,
                        from ./../folly/ExceptionWrapper.h:32,
                        from ExceptionWrapper.cpp:16:
        /usr/lib/gcc/x86_64-linux-gnu/4.8/include/stddef.h:425:3: note:   'max_align_t'
        } max_align_t;
        ^
        In file included from ./../folly/Assume.h:21:0,
                        from ./../folly/ExceptionWrapper.h:32,
                        from ExceptionWrapper.cpp:16:
        ./../folly/Portability.h:53:5: error: 'max_align_t' is not a member of 'std'
            std::max_align_t,
            ^
        ./../folly/Portability.h:53:5: note: suggested alternative:
        In file included from /usr/include/c++/4.8/cstddef:42:0,
                        from ./../folly/Portability.h:21,
                        from ./../folly/Assume.h:21,
                        from ./../folly/ExceptionWrapper.h:32,
                        from ExceptionWrapper.cpp:16:
        /usr/lib/gcc/x86_64-linux-gnu/4.8/include/stddef.h:425:3: note:   'max_align_t'
        } max_align_t;
        ^
        In file included from ./../folly/Assume.h:21:0,
                        from ./../folly/ExceptionWrapper.h:32,
                        from ExceptionWrapper.cpp:16:
        ./../folly/Portability.h:66:19: error: template argument 1 is invalid
            std::nullptr_t>;
                        ^
        ./../folly/Portability.h:69:40: error: 'folly::detail::max_basic_alignment' has not been declared
        constexpr size_t max_align_v = detail::max_basic_alignment::value;
                                                ^
        ./../folly/Portability.h:101:29: error: requested alignment is not an integer constant
        struct alignas(max_align_v) max_align_t {};
                                    ^
        make[2]: *** [Executor.lo] Error 1
        make[2]: *** [Checksum.lo] Error 1
        In file included from ./../folly/Assume.h:21:0,
                        from ./../folly/ExceptionWrapper.h:32,
                        from ./../folly/File.h:26,
                        from File.cpp:17:
        ./../folly/Portability.h:53:5: error: 'max_align_t' is not a member of 'std'
            std::max_align_t,
            ^
        ./../folly/Portability.h:53:5: note: suggested alternative:
        In file included from /usr/include/c++/4.8/cstddef:42:0,
                        from ./../folly/Portability.h:21,
                        from ./../folly/Assume.h:21,
                        from ./../folly/ExceptionWrapper.h:32,
                        from ./../folly/File.h:26,
                        from File.cpp:17:
        /usr/lib/gcc/x86_64-linux-gnu/4.8/include/stddef.h:425:3: note:   'max_align_t'
        } max_align_t;
        ^
        In file included from ./../folly/Assume.h:21:0,
                        from ./../folly/ExceptionWrapper.h:32,
                        from ./../folly/File.h:26,
                        from File.cpp:17:
        ./../folly/Portability.h:53:5: error: 'max_align_t' is not a member of 'std'
            std::max_align_t,
            ^
        ./../folly/Portability.h:53:5: note: suggested alternative:
        In file included from /usr/include/c++/4.8/cstddef:42:0,
                        from ./../folly/Portability.h:21,
                        from ./../folly/Assume.h:21,
                        from ./../folly/ExceptionWrapper.h:32,
                        from ./../folly/File.h:26,
                        from File.cpp:17:
        /usr/lib/gcc/x86_64-linux-gnu/4.8/include/stddef.h:425:3: note:   'max_align_t'
        } max_align_t;
        ^
        In file included from ./../folly/Assume.h:21:0,
                        from ./../folly/ExceptionWrapper.h:32,
                        from ./../folly/File.h:26,
                        from File.cpp:17:
        ./../folly/Portability.h:66:19: error: template argument 1 is invalid
            std::nullptr_t>;
                        ^
        ./../folly/Portability.h:69:40: error: 'folly::detail::max_basic_alignment' has not been declared
        constexpr size_t max_align_v = detail::max_basic_alignment::value;
                                                ^
        ./../folly/Portability.h:101:29: error: requested alignment is not an integer constant
        struct alignas(max_align_v) max_align_t {};
                                    ^
        In file included from ./../folly/ExceptionWrapper.h:689:0,
                        from ExceptionWrapper.cpp:16:
        ./../folly/ExceptionWrapper-inl.h: In member function 'auto folly::exception_wrapper::HandleStdExceptReduce<IsConst>::operator()(ThrowFn&&, CatchFn&) const':
        ./../folly/ExceptionWrapper-inl.h:535:59: error: parameter declared 'auto'
            return [ th = std::forward<ThrowFn>(th), &ca ](auto&& continuation)
                                                                ^
        ./../folly/ExceptionWrapper-inl.h: In lambda function:
        ./../folly/ExceptionWrapper-inl.h:537:42: error: 'continuation' was not declared in this scope
            if (auto e = const_cast<StdEx*>(th(continuation))) {
                                                ^
        ./../folly/ExceptionWrapper-inl.h: In member function 'auto folly::exception_wrapper::HandleStdExceptReduce<IsConst>::operator()(ThrowFn&&, CatchFn&) const':
        ./../folly/ExceptionWrapper-inl.h:553:56: error: parameter declared 'auto'
            return [ th = std::forward<ThrowFn>(th), &ca ](auto&&) -> StdEx* {
                                                                ^
        ./../folly/ExceptionWrapper-inl.h: In static member function 'static void folly::exception_wrapper::handle_(std::true_type, This&, CatchFns& ...)':
        ./../folly/ExceptionWrapper-inl.h:589:18: error: parameter declared 'auto'
            [&](auto&& continuation) {
                        ^
        In file included from ./../folly/FBString.h:44:0,
                        from ./../folly/Demangle.h:19,
                        from ./../folly/Conv.h:41,
                        from ./../folly/Format.h:24,
                        from detail/IPAddress.cpp:19:
        ./../folly/Portability.h:53:5: error: 'max_align_t' is not a member of 'std'
            std::max_align_t,
            ^
        ./../folly/Portability.h:53:5: note: suggested alternative:
        In file included from /usr/include/c++/4.8/cstddef:42:0,
                        from ./../folly/Conv.h:29,
                        from ./../folly/Format.h:24,
                        from detail/IPAddress.cpp:19:
        /usr/lib/gcc/x86_64-linux-gnu/4.8/include/stddef.h:425:3: note:   'max_align_t'
        } max_align_t;
        ^
        In file included from ./../folly/FBString.h:44:0,
                        from ./../folly/Demangle.h:19,
                        from ./../folly/Conv.h:41,
                        from ./../folly/Format.h:24,
                        from detail/IPAddress.cpp:19:
        ./../folly/Portability.h:53:5: error: 'max_align_t' is not a member of 'std'
            std::max_align_t,
            ^
        ./../folly/Portability.h:53:5: note: suggested alternative:
        In file included from /usr/include/c++/4.8/cstddef:42:0,
                        from ./../folly/Conv.h:29,
                        from ./../folly/Format.h:24,
                        from detail/IPAddress.cpp:19:
        /usr/lib/gcc/x86_64-linux-gnu/4.8/include/stddef.h:425:3: note:   'max_align_t'
        } max_align_t;
        ^
        In file included from ./../folly/FBString.h:44:0,
                        from ./../folly/Demangle.h:19,
                        from ./../folly/Conv.h:41,
                        from ./../folly/Format.h:24,
                        from detail/IPAddress.cpp:19:
        ./../folly/Portability.h:66:19: error: template argument 1 is invalid
            std::nullptr_t>;
                        ^
        ./../folly/Portability.h:69:40: error: 'folly::detail::max_basic_alignment' has not been declared
        constexpr size_t max_align_v = detail::max_basic_alignment::value;
                                                ^
        ./../folly/Portability.h:101:29: error: requested alignment is not an integer constant
        struct alignas(max_align_v) max_align_t {};
                                    ^
        In file included from ./../folly/FBString.h:44:0,
                        from ./../folly/Range.h:22,
                        from ./../folly/dynamic.h:66,
                        from dynamic.cpp:17:
        ./../folly/Portability.h:53:5: error: 'max_align_t' is not a member of 'std'
            std::max_align_t,
            ^
        ./../folly/Portability.h:53:5: note: suggested alternative:
        In file included from /usr/include/c++/4.8/cstddef:42:0,
                        from /usr/include/boost/config/select_stdlib_config.hpp:18,
                        from /usr/include/boost/config.hpp:40,
                        from /usr/include/boost/operators.hpp:85,
                        from ./../folly/dynamic.h:64,
                        from dynamic.cpp:17:
        /usr/lib/gcc/x86_64-linux-gnu/4.8/include/stddef.h:425:3: note:   'max_align_t'
        } max_align_t;
        ^
        In file included from ./../folly/FBString.h:44:0,
                        from ./../folly/Range.h:22,
                        from ./../folly/dynamic.h:66,
                        from dynamic.cpp:17:
        ./../folly/Portability.h:53:5: error: 'max_align_t' is not a member of 'std'
            std::max_align_t,
            ^
        ./../folly/Portability.h:53:5: note: suggested alternative:
        In file included from /usr/include/c++/4.8/cstddef:42:0,
                        from /usr/include/boost/config/select_stdlib_config.hpp:18,
                        from /usr/include/boost/config.hpp:40,
                        from /usr/include/boost/operators.hpp:85,
                        from ./../folly/dynamic.h:64,
                        from dynamic.cpp:17:
        /usr/lib/gcc/x86_64-linux-gnu/4.8/include/stddef.h:425:3: note:   'max_align_t'
        } max_align_t;
        ^
        In file included from ./../folly/FBString.h:44:0,
                        from ./../folly/Range.h:22,
                        from ./../folly/dynamic.h:66,
                        from dynamic.cpp:17:
        ./../folly/Portability.h:66:19: error: template argument 1 is invalid
            std::nullptr_t>;
                        ^
        ./../folly/Portability.h:69:40: error: 'folly::detail::max_basic_alignment' has not been declared
        constexpr size_t max_align_v = detail::max_basic_alignment::value;
                                                ^
        ./../folly/Portability.h:101:29: error: requested alignment is not an integer constant
        struct alignas(max_align_v) max_align_t {};
                                    ^
        make[2]: *** [ExceptionWrapper.lo] Error 1
        In file included from ./../folly/Assume.h:21:0,
                        from ./../folly/Bits.h:75,
                        from ./../folly/Hash.h:28,
                        from ./../folly/concurrency/CacheLocality.h:31,
                        from concurrency/CacheLocality.cpp:17:
        ./../folly/Portability.h:53:5: error: 'max_align_t' is not a member of 'std'
            std::max_align_t,
            ^
        ./../folly/Portability.h:53:5: note: suggested alternative:
        In file included from /usr/include/c++/4.8/cstddef:42:0,
                        from /usr/include/boost/config/select_stdlib_config.hpp:18,
                        from /usr/include/boost/config.hpp:40,
                        from /usr/include/boost/static_assert.hpp:17,
                        from /usr/include/boost/iterator/iterator_adaptor.hpp:10,
                        from ./../folly/Bits.h:73,
                        from ./../folly/Hash.h:28,
                        from ./../folly/concurrency/CacheLocality.h:31,
                        from concurrency/CacheLocality.cpp:17:
        /usr/lib/gcc/x86_64-linux-gnu/4.8/include/stddef.h:425:3: note:   'max_align_t'
        } max_align_t;
        ^
        In file included from ./../folly/Assume.h:21:0,
                        from ./../folly/Bits.h:75,
                        from ./../folly/Hash.h:28,
                        from ./../folly/concurrency/CacheLocality.h:31,
                        from concurrency/CacheLocality.cpp:17:
        ./../folly/Portability.h:53:5: error: 'max_align_t' is not a member of 'std'
            std::max_align_t,
            ^
        ./../folly/Portability.h:53:5: note: suggested alternative:
        In file included from /usr/include/c++/4.8/cstddef:42:0,
                        from /usr/include/boost/config/select_stdlib_config.hpp:18,
                        from /usr/include/boost/config.hpp:40,
                        from /usr/include/boost/static_assert.hpp:17,
                        from /usr/include/boost/iterator/iterator_adaptor.hpp:10,
                        from ./../folly/Bits.h:73,
                        from ./../folly/Hash.h:28,
                        from ./../folly/concurrency/CacheLocality.h:31,
                        from concurrency/CacheLocality.cpp:17:
        /usr/lib/gcc/x86_64-linux-gnu/4.8/include/stddef.h:425:3: note:   'max_align_t'
        } max_align_t;
        ^
        In file included from ./../folly/Assume.h:21:0,
                        from ./../folly/Bits.h:75,
                        from ./../folly/Hash.h:28,
                        from ./../folly/concurrency/CacheLocality.h:31,
                        from concurrency/CacheLocality.cpp:17:
        ./../folly/Portability.h:66:19: error: template argument 1 is invalid
            std::nullptr_t>;
                        ^
        ./../folly/Portability.h:69:40: error: 'folly::detail::max_basic_alignment' has not been declared
        constexpr size_t max_align_v = detail::max_basic_alignment::value;
                                                ^
        ./../folly/Portability.h:101:29: error: requested alignment is not an integer constant
        struct alignas(max_align_v) max_align_t {};
                                    ^
        In file included from ./../folly/ExceptionWrapper.h:689:0,
                        from ./../folly/File.h:26,
                        from File.cpp:17:
        ./../folly/ExceptionWrapper-inl.h: In member function 'auto folly::exception_wrapper::HandleStdExceptReduce<IsConst>::operator()(ThrowFn&&, CatchFn&) const':
        ./../folly/ExceptionWrapper-inl.h:535:59: error: parameter declared 'auto'
            return [ th = std::forward<ThrowFn>(th), &ca ](auto&& continuation)
                                                                ^
        ./../folly/ExceptionWrapper-inl.h: In lambda function:
        ./../folly/ExceptionWrapper-inl.h:537:42: error: 'continuation' was not declared in this scope
            if (auto e = const_cast<StdEx*>(th(continuation))) {
                                                ^
        ./../folly/ExceptionWrapper-inl.h: In member function 'auto folly::exception_wrapper::HandleStdExceptReduce<IsConst>::operator()(ThrowFn&&, CatchFn&) const':
        ./../folly/ExceptionWrapper-inl.h:553:56: error: parameter declared 'auto'
            return [ th = std::forward<ThrowFn>(th), &ca ](auto&&) -> StdEx* {
                                                                ^
        ./../folly/ExceptionWrapper-inl.h: In static member function 'static void folly::exception_wrapper::handle_(std::true_type, This&, CatchFns& ...)':
        ./../folly/ExceptionWrapper-inl.h:589:18: error: parameter declared 'auto'
            [&](auto&& continuation) {
                        ^
        In file included from ./../folly/String.h:33:0,
                        from ./../folly/Format.h:27,
                        from detail/IPAddress.cpp:19:
        ./../folly/FBVector.h: In lambda function:
        ./../folly/FBVector.h:1432:49: error: parameter packs not expanded with '...':
                M_construct(start, std::forward<Args>(args)...);
                                                        ^
        ./../folly/FBVector.h:1432:49: note:         'args'
        In file included from ./../folly/String.h:33:0,
                        from ./../folly/Format.h:27,
                        from ./../folly/dynamic-inl.h:25,
                        from ./../folly/dynamic.h:580,
                        from dynamic.cpp:17:
        ./../folly/FBVector.h: In lambda function:
        ./../folly/FBVector.h:1432:49: error: parameter packs not expanded with '...':
                M_construct(start, std::forward<Args>(args)...);
                                                        ^
        ./../folly/FBVector.h:1432:49: note:         'args'
        In file included from ./../folly/String.h:33:0,
                        from ./../folly/Format.h:27,
                        from File.cpp:22:
        ./../folly/FBVector.h: In lambda function:
        ./../folly/FBVector.h:1432:49: error: parameter packs not expanded with '...':
                M_construct(start, std::forward<Args>(args)...);
                                                        ^
        ./../folly/FBVector.h:1432:49: note:         'args'
        In file included from ./../folly/String.h:33:0,
                        from ./../folly/Format.h:27,
                        from concurrency/CacheLocality.cpp:28:
        ./../folly/FBVector.h: In lambda function:
        ./../folly/FBVector.h:1432:49: error: parameter packs not expanded with '...':
                M_construct(start, std::forward<Args>(args)...);
                                                        ^
        ./../folly/FBVector.h:1432:49: note:         'args'
        make[2]: *** [detail/IPAddress.lo] Error 1
        make[2]: *** [File.lo] Error 1
        make[2]: *** [concurrency/CacheLocality.lo] Error 1
        make[2]: *** [dynamic.lo] Error 1
        make[2]: Leaving directory `/home/dev/Desktop/test/proxygen/proxygen/folly/folly'
        make[1]: *** [all-recursive] Error 1
        make[1]: Leaving directory `/home/dev/Desktop/test/proxygen/proxygen/folly/folly'
        make: *** [all] Error 2

My VPS only has 2GB of RAM and I know the requirements say that a minimum of 3GB is required but these don't look like issues related to that. Does anyone have a solution for this?

**Comment by afrind** [comment]
This looks like problems building folly.  Can you check in that project?

**Comment by lnicco** [comment]
also, try upgrading to gcc 4.9. it should fix your issues.
the Travis CI for ubuntu 14.04, gcc 4.9 is passing just fine:
https://travis-ci.org/facebook/proxygen/builds/255905427

**Comment by lnicco** [comment]
Yeah, folly requires gcc 4.9 https://github.com/facebook/folly/commit/7bdb20f850299dc14045ef9e00b8b90a1dce17b7
