### ISSUE TITLE
Proxygen Performance

### ISSUE THREAD

**Issue by nginxsantos** [facebook/proxygen#185]
Hi,

I am using the asynchronous communication, receiving the message and distributing to backend. But, with log disabled, I am not getting the number beyond 900RPS, although my CPU and Memory usage does not go high. I don't know where is the issue.

I also looked at some online blog and it seems they also got numbers what I got.

https://engineering.instagram.com/c-futures-at-instagram-9628ff634f49

According to the above blog the only way to improve the performance was to create multiple instance. I can create multiple instance, but I don't have a loadbalancer to load balance among them. I am not sure about the chaining concept in this. Can someone please explain.

Is there way where we can still listen for one IP and Port to receive the incoming client request but increase the instance/threads to achieve high numbers.

Can someone please help.

Thanks in advance.

Regards, Santos

**Comment by nginxsantos** [comment]
Any thoughts on this?

**Comment by afrind** [comment]
It's difficult to say without seeing your code, can you paste a snippet?  I'd say what's most likely is that you are tying up the i/o thread waiting for the response which is preventing the thread from servicing other new connections/requests.

**Comment by afrind** [comment]
Closing since we don't have any additional input to comment on.  Please reopen if you have a repro or code you would like us to look at.
