### ISSUE TITLE
Is there any detailed documentation?

### ISSUE THREAD

**Issue by set-daemon** [facebook/proxygen#186]
Hi,
Is there any code analysis on proxygen? I'm wondering about and trying to find out how does proxygen work, now i just known there are two group threads working undergroup, one is acceptor thread group, another is io thread group, but don't known the communication within them, and more unknowns. Maybe it's hard to me, so seek for your help.

**Comment by afrind** [comment]
Well, there's not detailed documentation, and we'd like to improve it, but for now it's pretty ad hoc.

To answer your question, the acceptor group accepts new connections and load balances them to the IO threads.  Once a connection has been picked up by an IO thread it will be serviced there for its entire lifetime. 

I'll leave this open if you have other specific questions I can answer.  Maybe we can use this thread as the beginning of a wiki or FAQ.

**Comment by set-daemon** [comment]
Thanks @afrind, so the operation read/write on this connection is done in IO thread?  
I'm reading the code of proxygen/wangle/folly, it may last for a long time, any questions will be submitted here for help, and thanks again.

**Comment by afrind** [comment]
Yes all socket operations are done from the I/O thread in a non-blocking fashion.

**Comment by jbeshay** [comment]
Cleaning up old issues. There is still no comprehensive documentation, but a minimal doxygen is available: https://github.com/facebook/proxygen?tab=readme-ov-file#documentation
