### ISSUE TITLE
http client performance issue? ('Invalid transition tried: EOMQueued sendHeaders')

### ISSUE THREAD

**Issue by zhi-zhao-dailymotion** [facebook/proxygen#189]
Hi, 
We're using the http client, it works fine with rps < 500, however, once the rps goes above 800, we start seeing the following error msg:
E0816 StateMachine.h:31] Invalid transition tried: EOMQueued sendHeaders
F0816 HTTPTransaction.cpp:712] Check failed: HTTPTransactionEgressSM::transit( egressState_, HTTPTransactionEgressSM::Event::sendHeaders)

below are some of the call traces:
    @     0x7ffff7a4ea2d  proxygen::HTTPTransaction::sendHeadersWithOptionalEOM()
    @           0x4b12fb  proxygen::ResponseBuilder::send()
    @           0x4b1118  proxygen::ResponseBuilder::sendWithEOM()
Obviously the CHECK of transit inside sendHeadersWithOptionalEOM() failed and the service aborted.

The environment is ubuntu 16.04

I'm wondering why did it end up with an invalid state (EOMQueued sendHeaders) when the rps is high (>800)?

Any suggestions on how to debug/fix or what to look for/check is welcome. Thanks in advance!

**Comment by afrind** [comment]
This means that you are trying to call sendHeaders after you have already called sendEOM.  I'm not sure why it would only be happening for you at high RPS, but it's very likely a logic bug in your handler.  Perhaps you can paste some code of how your handler is generating the reply?

**Comment by afrind** [comment]
Since I haven't received a repro and paste of your code, closing for now.  Please reopen if you have more for us to look at.
