### ISSUE TITLE
successful built proxygen, but failt to make echo.

### ISSUE THREAD

**Issue by jenenliu** [facebook/proxygen#192]
Hi, I've build proxygen ok, but when I run this command to buid echo.
`g++ -std=c++14 -o my_echo EchoServer.cpp EchoHandler.cpp -lproxygenhttpserver -lfolly -lglog -lgflags -pthread `

I got this error:
`In file included from /usr/local/include/proxygen/lib/http/codec/compress/HeaderTable.h:13:0,
                 from /usr/local/include/proxygen/lib/http/codec/compress/HPACKContext.h:13,
                 from /usr/local/include/proxygen/lib/http/codec/compress/HPACKDecoder.h:17,
                 from /usr/local/include/proxygen/lib/http/codec/compress/HPACKCodec.h:14,
                 from /usr/local/include/proxygen/lib/http/codec/HTTPCodec.h:21,
                 from /usr/local/include/proxygen/lib/http/session/HTTPTransaction.h:25,
                 from /usr/local/include/proxygen/httpserver/RequestHandler.h:12,
                 from /usr/local/include/proxygen/httpserver/Filters.h:12,
                 from /usr/local/include/proxygen/httpserver/HTTPServerOptions.h:14,
                 from /usr/local/include/proxygen/httpserver/HTTPServer.h:15,
                 from EchoServer.cpp:13:
/usr/local/include/proxygen/lib/http/codec/compress/HPACKHeader.h:15:62: fatal error: proxygen/lib/http/codec/compress/HPACKHeaderName.h: No such file or directory
compilation terminated.
In file included from /usr/local/include/proxygen/lib/http/codec/compress/HeaderTable.h:13:0,
                 from /usr/local/include/proxygen/lib/http/codec/compress/HPACKContext.h:13,
                 from /usr/local/include/proxygen/lib/http/codec/compress/HPACKDecoder.h:17,
                 from /usr/local/include/proxygen/lib/http/codec/compress/HPACKCodec.h:14,
                 from /usr/local/include/proxygen/lib/http/codec/HTTPCodec.h:21,
                 from /usr/local/include/proxygen/lib/http/session/HTTPTransaction.h:25,
                 from /usr/local/include/proxygen/httpserver/RequestHandler.h:12,
                 from EchoHandler.h:13,
                 from EchoHandler.cpp:10:
/usr/local/include/proxygen/lib/http/codec/compress/HPACKHeader.h:15:62: fatal error: proxygen/lib/http/codec/compress/HPACKHeaderName.h: No such file or directory
compilation terminated.
`

my os is *ubuntu16.04* , and all the build process is : 
`git clone https://github.com/facebook/proxygen`
`cd proxygen/proxygen`
`./deps.sh`
`./reinstall`
`cd httpserver/samples/echo`

can someone check that out, thanks a lot !

**Comment by jordandong** [comment]
you need gcc4.9 +

Best,
Dong

**Comment by jenenliu** [comment]
@jordandong 
seem it is, gcc version
`gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
`

**Comment by afrind** [comment]
Yes, we missed a makefile change in a diff last week.  Fix coming.

**Comment by afrind** [comment]
Please pull and try again.  Reopen if still an issue.

**Comment by jenenliu** [comment]
@afrind it works now, thanks a lot.
