### ISSUE TITLE
Does proxygen have HTTP/2 client support?

### ISSUE THREAD

**Issue by zhi-zhao-dailymotion** [facebook/proxygen#193]
Hi, 
I'm trying to use proxygen as an HTTP/2 client if possible.

I tried to use the curl client from proxygen/httpclient/samples/curl and send request to the h2_port 11002 of the echo_server from proxygen/httpserver/samples/echo/. 

The curl client gives error:
> E0926 15:29:37.948189 25962 CurlClient.cpp:195] An error occurred: Error parsing message: invalid constant string

And the echo_server gives error:

> E0926 15:31:11.405316 25835 HTTP2Codec.cpp:1334] Connection error with ingress=
00000000  47 45 54 20 2f 20 48 54  54 50 2f 31 2e 31 0d 0a  |GET / HTTP/1.1..|
00000010  55 70 67 72 61 64 65 3a  20 68 32 63 0d 0a 48 54  |Upgrade: h2c..HT|
00000020  54 50 32 2d 53 65 74 74  69 6e 67 73 3a 20 41 41  |TP2-Settings: AA|
00000030  45 41 41 42 41 41 41 41  49 41 41 41 41 41 41 41  |EAABAAAAIAAAAAAA|
00000040  55 41 41 45 41 41 41 41  59 41 41 67 41 41 0d 0a  |UAAEAAAAYAAgAA..|
00000050  55 73 65 72 2d 41 67 65  6e 74 3a 20 70 72 6f 78  |User-Agent: prox|
00000060  79 67 65 6e 5f 63 75 72  6c 0d 0a 48 6f 73 74 3a  |ygen_curl..Host:|
00000070  20 6c 6f 63 61 6c 68 6f  73 74 3a 31 30 30 30 32  | localhost:10002|
00000080  0d 0a 41 63 63 65 70 74  3a 20 2a 2f 2a 0d 0a 43  |..Accept: */*..C|
00000090  6f 6e 6e 65 63 74 69 6f  6e 3a 20 55 70 67 72 61  |onnection: Upgra|
000000a0  64 65 2c 20 48 54 54 50  32 2d 53 65 74 74 69 6e  |de, HTTP2-Settin|
000000b0  67 73 2c 20 6b 65 65 70  2d 61 6c 69 76 65 0d 0a  |gs, keep-alive..|
000000c0  0d 0a                                             |..              |

According to https://github.com/facebook/proxygen/issues/158, I tried 
> curl -I --http2 --http2-prior-knowledge http://localhost:10002

and it works.

I'm wondering is there any special settings that we need to do to make the proxygen http client work for HTTP/2? If so, is there an example? Only thing I found so far is 
`if (h2c_) {
    HTTP2Codec::requestUpgrade(request_);
  }
`
from CurlClient.cpp

Thank you.

**Comment by afrind** [comment]
Yes proxygen has supported HTTP/2 for several years.

There are three ways to use HTTP/2:

1. Connect to a TLS server and use the h2 ALPN token
2. Connect to a plaintext HTTP server and use h2c Upgrade
3. Connect to a plaintext HTTP/2 server with prior knowledge

The echo server port 11002 is like 3).  You need to use the curl client --plaintext_proto argument to connect to it.  Or you can use -h2c option against port 11000 for 2) above.  The echo server doesn't have a TLS port by default, but if you configure a certificate, etc you can also use 1).
