### ISSUE TITLE
HTTPMethod PATCH is not supported.

### ISSUE THREAD

**Issue by badarihp** [facebook/proxygen#199]
Hi,
  Looks like HTTPMethod PATCH is not supported (https://github.com/facebook/proxygen/blob/master/proxygen/lib/http/HTTPMethod.h ). 

Would like to know of any plans to support the same?

Regards
 badari

**Comment by afrind** [comment]
You can call HTTPMessage::setMethod() with any string you like, and retrieve with getMethodString. 
 getMethod will return none if your method is not in the list.  The enum is just a shortcut and uses less storage.  That said, should be an easy PR to add PATCH there if you like.

**Comment by badarihp** [comment]
Thank you for info

**Comment by badarihp** [comment]
Hi Alan,
 Have initiated a PR : https://github.com/facebook/proxygen/pull/200 

Thanks
 badari
