### ISSUE TITLE
deps-centos.sh shall use "yum -y install"  instead of "yum install" to avoid input "y" duing docker img build

### ISSUE THREAD

**Issue by hobbytp** [facebook/proxygen#203]
I try to build proxygen in centos OS docker image, but the dockerfile always failed as below, so I think we can change from "yum install" to "yum -y install" to avoid the manual step during docker image build.
```
 Total download size: 81 M
 Is this ok [y/d/N]: Exiting on user command
```

BR,

Hobby

**Comment by dddmello** [comment]
Sure can take a look and if things look reasonable will add it in.

**Comment by lnicco** [comment]
this has been merged. 
closing the issue
