### ISSUE TITLE
does proxygen have websockets support?

### ISSUE THREAD

**Issue by mariasmo** [facebook/proxygen#206]
hi ,

does proxygen have websockets support yet?

thanks

**Comment by afrind** [comment]
Can you elaborate by what websocket support you would like from proxygen?  Proxygen can handle the HTTP interactions required for a websocket handshake (Upgrade headers, send 101 Switching Protocls), but does not provide any native parsing or generating of websocket frames.

**Comment by jmccl** [comment]
I suspect @mariasmo is essentially requesting that the websocket proxygen module referred to by @lanxi in #170 be open sourced.

**Comment by ritunp** [comment]
We recently added support for WebSockets. Proxygen handles the handshake part if the application asks for a WebSocket upgrade. To ask for a WebSocket upgrade on a transaction, the HTTPMessage has  a call "setEgressWebsocketUpgrade". Responses will similarly be marked with a flag if they contain appropriate WebSocket response headers - this can be checked with a call to "isIngressWebsocketUpgrade" on the HTTPMessage.

Note: for now, you would need to add the "Sec-WebSocket-Version" header to the HTTPMessage. This requirement should go away soon.

**Comment by frenchietechie** [comment]
Hello does anybody have an example of making a working websocket request?

I have been at this for a couple of days and I can't get it to work

**Comment by frenchietechie** [comment]
PS: trying various variations of something like this: https://gist.github.com/frenchietechie/47ba9ffa069f359ad99e1dcbf7f7f892

but I keep getting error codes such as <h1>Bad Request</h1>
<p>Your browser sent a request that this server could not understand.<br />

**Comment by kvtsoy** [comment]
Are you connecting to a proxygen server?

**Comment by jbeshay** [comment]
An example has been committed in bc44e34bc5861a4db1e7b22133e28c05d330e1ab.
