### ISSUE TITLE
Please provide a sample  on how the RFC1827 class can be used.

### ISSUE THREAD

**Issue by keithmendozasr** [facebook/proxygen#209]
This is in reference to issue #103. I found the the class; but, I'm having a hard time figuring out how I can use this codec. Looking at the code, I get the impression that this should somehow replace the HTTP1xCodec in my RequestHandler. However, looking at how HTTP1xCodec is used that approach doesn't feel right.

I'm willing to contribute a working sample if someone can point me in the right direction on how to use the RFC1827 class.

**Comment by afrind** [comment]
It's not supposed to replace 1xCodec.  It's intended to be used on the body data that comes from an onBody callback.

**Comment by afrind** [comment]
RFC1867Test.cpp has sort of an example usage as well.  Closing for now.
