### ISSUE TITLE
Is there a way to get more details on what part of the header is invalid

### ISSUE THREAD

**Issue by kdp-dev** [facebook/proxygen#211]
I0118 08:33:37.268347  9165 http_client.cpp:225] In onError
E0118 08:33:37.268425  9165 http_client.cpp:226] error.describe()what="Error parsing message: invalid character in header", direction=0, proxygenError=ParseHeader, codecStatusCode=-1, httpStatusCode=0
E0118 08:33:37.268440  9165 http_client.cpp:227] error.what(): Error parsing message: invalid character in header

**Comment by dddmello** [comment]
Hmm can take a look about trying to improve the message and perhaps at least provide an index.

**Comment by w-o-o** [comment]
I think we do have the detailed error message, which header name and value in HTTP2Codec.cpp.  Here is one example 

> HTTP2Codec.cpp:422] Failed parsing header list for stream=1, error=Bad header value: name=x-forwarded-for value=126976\`h\'h\"\\, header block=00000000  82 87 c7 c4 cc c6 7f 00  97 08 9c 7d d7 3f ff 87  |...........}.?..|

@kdp-dev  are you using http/1.1 or spdy?

**Comment by kdp-dev** [comment]
@w-o-o I’m using http/1.1
Will try this though.
