### ISSUE TITLE
Consistent Cloudfront 403s with curl sample client

### ISSUE THREAD

**Issue by psrikhanta** [facebook/proxygen#214]
# Environment
OS: Ubuntu 16.04.3 LTS
built from master

# Description:
Accessing resources via the curl example on cloudfront leads to 403s. Attempting the same request with nghttp2, browser or go 1.9 works fine.

_Sidenote_: Cloudfront will return a 403 if a get request has a body https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/RequestAndResponseBehaviorCustomOrigin.html#RequestCustom-get-body 

# Repo Steps:

urls to try
https://http2.akamai.com/demo/tile-104.png (works)
https://d2vtxyv01zs38e.cloudfront.net/tmp/img-1.jpg (fails on cloudfront)
https://contestimg.wish.com/api/webimage/57e4d4ab411d8d05df39fceb-tiny (fails on cloudfront)

## Cloudfront Resource (fails)
./curl -v=100 -logtostderr -url https://d2vtxyv01zs38e.cloudfront.net/tmp/img-1.jpg >out.txt 2>stderr.log
Sample Server Response
I0208 05:48:04.707757 28523 HTTPSession.cpp:1084] proto=http/2, local=10.138.0.2:53584, 54.230.142.3:443=upstream received settings ack
I0208 05:48:04.707763 28523 HTTP2Codec.cpp:353] parsing HEADERS frame for stream=1 length=186
I0208 05:48:04.707790 28523 HTTP2Codec.cpp:494] Processing header=:status value=403
I0208 05:48:04.707813 28523 HTTP2Codec.cpp:494] Processing header=server value=CloudFront
I0208 05:48:04.707823 28523 HTTP2Codec.cpp:494] Processing header=date value=Thu, 08 Feb 2018 05:48:04 GMT
I0208 05:48:04.707828 28523 HTTP2Codec.cpp:494] Processing header=content-type value=text/html
I0208 05:48:04.707834 28523 HTTP2Codec.cpp:494] Processing header=content-length value=551
I0208 05:48:04.707842 28523 HTTP2Codec.cpp:494] Processing header=x-cache value=Error from cloudfront
I0208 05:48:04.707851 28523 HTTP2Codec.cpp:494] Processing header=via value=1.1 570a1979c411cb4529fa1e711db52490.cloudfront.net (CloudFront)
I0208 05:48:04.707859 28523 HTTP2Codec.cpp:494] Processing header=x-amz-cf-id value=6euftCXalGAr15bqwpFIO9dDnsFym4XCmDdZ1drM5LK4Ev1WKA2MSQ==
[cf1.log](https://github.com/facebook/proxygen/files/1705862/cf1.log)

## Akamai Resource (works)
./curl -v=100 -logtostderr -url https://http2.akamai.com/demo/tile-104.png >out.txt 2>stderr.log
**Sample Server Response:**
I0208 05:46:28.703138 28500 HTTP2Codec.cpp:353] parsing HEADERS frame for stream=1 length=327
I0208 05:46:28.703177 28500 HTTP2Codec.cpp:494] Processing header=:status value=200
I0208 05:46:28.703204 28500 HTTP2Codec.cpp:494] Processing header=server value=Apache
I0208 05:46:28.703213 28500 HTTP2Codec.cpp:494] Processing header=etag value="6584bd2d2e6ce0f81bdd5bc6da403601:1425453591"
I0208 05:46:28.703222 28500 HTTP2Codec.cpp:494] Processing header=last-modified value=Wed, 04 Mar 2015 07:19:51 GMT
I0208 05:46:28.703227 28500 HTTP2Codec.cpp:494] Processing header=accept-ranges value=bytes
I0208 05:46:28.703233 28500 HTTP2Codec.cpp:494] Processing header=content-length value=3684
I0208 05:46:28.703238 28500 HTTP2Codec.cpp:494] Processing header=content-type value=image/png
I0208 05:46:28.703243 28500 HTTP2Codec.cpp:494] Processing header=expires value=Thu, 08 Feb 2018 05:46:28 GMT
I0208 05:46:28.703248 28500 HTTP2Codec.cpp:494] Processing header=cache-control value=max-age=0, no-cache, no-store
I0208 05:46:28.703253 28500 HTTP2Codec.cpp:494] Processing header=pragma value=no-cache
I0208 05:46:28.703258 28500 HTTP2Codec.cpp:494] Processing header=date value=Thu, 08 Feb 2018 05:46:28 GMT
I0208 05:46:28.703263 28500 HTTP2Codec.cpp:494] Processing header=access-control-max-age value=86400
I0208 05:46:28.703269 28500 HTTP2Codec.cpp:494] Processing header=access-control-allow-credentials value=false
I0208 05:46:28.703274 28500 HTTP2Codec.cpp:494] Processing header=access-control-allow-headers value=*
I0208 05:46:28.703294 28500 HTTP2Codec.cpp:494] Processing header=access-control-allow-methods value=GET,HEAD,POST
I0208 05:46:28.703299 28500 HTTP2Codec.cpp:494] Processing header=access-control-allow-origin value=*
I0208 05:46:28.703305 28500 HTTP2Codec.cpp:494] Processing header=strict-transport-security value=max-age=31536000 ; includeSubDomains
[akamai.log](https://github.com/facebook/proxygen/files/1705863/akamai.log)

**Comment by afrind** [comment]
My hunch is that this is because proxygen can sometimes send the EOM flag in an empty DATA frame, even for GETs.  Try changing CurlClient to sendHeaders/sendBody/sendEOM for POST and sendHeadersWIthEOM for GET - I suspect this will work.  

I'm inclined to say CloudFront is not totally compliant with the spec here - there is no body for this GET, it just has a delayed END_STREAM flag, but perhaps its a grey area.  The HTTP spec says GETs *can* have a body (though this is rare in practice, I'm sure), hence proxygen library doesn't assume that GET headers need a END_STREAM flag in the frame.

**Comment by psrikhanta** [comment]
Confirmed 👍 - changed to sendHeadersWithEOM and commented out txn_->sendEOM(); in sendRequest.

I'm going to close this out since it only applies to me.

Thank you :)

**Comment by afrind** [comment]
We'd accept a PR since that is strictly better, or we will update CurlClient when we get around to it.
