### ISSUE TITLE
proxygen curlclient is storing the Entire File in the IOBufQueue . How to avoid this ?

### ISSUE THREAD

**Issue by venkatesh551** [facebook/proxygen#215]
Hi,
Currently, I am benchmarking the proxygen samples/curl client. Its memory utilization is very high in case of PUT. 
txn->sendBody(iobuf)  not writing to the wire immediately. How to do that?

**Comment by maxgeorg** [comment]
Hi @venkatesh551,
To throttle egress in CurlClient you can register your implementation of HTTPTransaction::TransportCallback interface with the transmitting HTTPTransaction object. HTTPTransaction will call HTTPTransaction::TransportCallback::bodyBytesGenerated() every time a the next block of data is transmitted. You can use it as a signal to read more data from the file, and queue this data for transmission with HTTPTransaction.

**Comment by venkatesh551** [comment]
Ok, Thanks, It's working Fine. After a series of txn_->sendBody() in 
bodyBytesGenerated()  method,  calling txn->sendEom() is causing segfault

**Comment by maxgeorg** [comment]
@venkatesh551, calling txn_->sendEom() inside bodyBytesGenerated() callback is not a good idea. One of the possible crash reasons is HTTPTransaction::sendEOM() internally calling transportCallback_->bodyBytesGenerated(...):
https://github.com/facebook/proxygen/blob/master/proxygen/lib/http/session/HTTPTransaction.cpp#L1000
But there could be also other reasons.

**Comment by afrind** [comment]
Instead of bodyBytesGenerated, your handler can implement onEgressPaused/onEgressResumed.  You can set a flag in onEgressPaused that breaks your file reading loop, and you can resume the loop from onEgressResumed.

Here's a little snippet from a server that does something similar:

```
  void onEgressPaused() noexcept override {
    paused_ = true;
  }

  void onEgressResumed() noexcept override {
    paused_ = false;
    sendBodyInChunks();
  }

  void sendBodyInChunks() {
    while (!paused_) {
      // read a chunk from a file
      if (!chunk) {
        readEOF_ = true;
        break;  // end of file
      }
      txn_->sendBody(std::move(chunk));
    }
    if (!paused_ && !readEOF_ && !sentEOF_) {
      txn_->sendEOM();
      sentEOF_ = true;
    }
  }
```
