### ISSUE TITLE
lib/http fails to compile with  "undefined reference to jump_fcontext"

### ISSUE THREAD

**Issue by dsclassen** [facebook/proxygen#219]
I'm stuck on this step. I've compiled all dependencies from source. I'm on CentOS 7 using the devtoolset-7 environment.

<code>make  all-recursive
make[1]: Entering directory '/usr/local/dcs/proxygen/proxygen/lib/http'
Making all in .
make[2]: Entering directory '/usr/local/dcs/proxygen/proxygen/lib/http'
/bin/sh ../../libtool  --tag=CXX   --mode=link g++  -pthread -DLIBMC_FBTRACE_DISABLE  -Wno-missing-field-initializers -Wno-deprecated -O3 -g -W -Wall -Wextra -Wno-unused-parameter -fno-strict-aliasing -g -O2   -o CompressionSimulator codec/compress/test/HTTPArchive.o codec/compress/experimental/simulator/Main.o codec/compress/experimental/simulator/CompressionSimulator.o libqpack.la libqcram.la libproxygenhttp.la ../services/libproxygenservices.la -ldl -lwangle -lfolly -lz -lssl -lcrypto -levent -lgflags -lglog  -L/usr/lib64 -L/usr/lib -lpthread -pthread -lfolly -lglog -ldouble-conversion -lboost_system -lboost_thread
libtool: link: g++ -pthread -DLIBMC_FBTRACE_DISABLE -Wno-missing-field-initializers -Wno-deprecated -O3 -g -W -Wall -Wextra -Wno-unused-parameter -fno-strict-aliasing -g -O2 -o CompressionSimulator codec/compress/test/HTTPArchive.o codec/compress/experimental/simulator/Main.o codec/compress/experimental/simulator/CompressionSimulator.o -pthread  ./.libs/libqpack.a -L/usr/lib64 -L/usr/lib ./.libs/libqcram.a ./.libs/libproxygenhttp.a ../services/.libs/libproxygenservices.a -ldl -lwangle -lz -lssl -lcrypto -levent -lgflags -lpthread -lfolly -lglog -ldouble-conversion -lboost_system -lboost_thread -pthread
//usr/local/lib/libfolly.a(Fiber.cpp.o): In function `folly::fibers::FiberImpl::FiberImpl(folly::Function<void ()>, unsigned char*, unsigned long)':
/usr/local/dcs/proxygen/folly/folly/fibers/BoostContextCompatibility.h:72: undefined reference to `make_fcontext'
//usr/local/lib/libfolly.a(Fiber.cpp.o): In function `folly::fibers::FiberImpl::deactivate()':
/usr/local/dcs/proxygen/folly/folly/fibers/BoostContextCompatibility.h:101: undefined reference to `jump_fcontext'
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:905: CompressionSimulator] Error 1
make[2]: Leaving directory '/usr/local/dcs/proxygen/proxygen/lib/http'
make[1]: *** [Makefile:1132: all-recursive] Error 1
make[1]: Leaving directory '/usr/local/dcs/proxygen/proxygen/lib/http'
make: *** [Makefile:648: all] Error 2</code>

**Comment by dr-hagar** [comment]
The link line needs this added:

`-lboost_context -dl`

took me a while to figure out :/

**Comment by afrind** [comment]
resolved a while ago
