### ISSUE TITLE
Could i send file directly without copy to userspace when download some file.

### ISSUE THREAD

**Issue by corndolly** [facebook/proxygen#224]
I implement "download" by copy data into userspace with proxygen,   it is very costed.
Does proxygen support "sendfile" now?

**Comment by maxgeorg** [comment]
@corndolly, could you please clarify what is the problem you run into while uploading files? You don't need to load the whole file to RAM before sending it. Instead you can read file piece-by-piece, and send it using chunked encoding, proxygen::HTTPTransaction has an interface for that.

**Comment by corndolly** [comment]
@maxgeorg 

> Instead you can read file piece-by-piece, and send it using chunked encoding, proxygen::HTTPTransaction has an interface for that.

Exactly, this is my way now.  But it is very costly,  because we need to copy data into userspace before send it.   The max speed for one thread is only about 120MB/s.

**Comment by maxgeorg** [comment]
120Mb/s is enough to saturate 1Gb network interface.
@corndolly, are you trying to saturate a network interface faster than 1Gb?
Also where do you suspect the bottleneck is?

**Comment by corndolly** [comment]
@maxgeorg 

> are you trying to saturate a network interface faster than 1Gb

Yes,  my NIC is 25Gb. 

> where do you suspect the bottleneck is?

Because i found lots of malloc/free and memcpy in perf.

**Comment by afrind** [comment]
There's one malloc/free on the write path that we have a patch to eliminate, but it needs some more testing/validation.  But we're unlikely to support something like sending a file directly from disk, especially since that would require kernel support for TLS for most of our use cases.

**Comment by afrind** [comment]
We improved HTTP/2 performance dramatically in the last 6 months or so.  Give it another go and let us know if you have bottlenecks.  We don't have plans to implement a sendFile interface at this time.
