### ISSUE TITLE
_ZN5folly12BadFormatArgD1Ev

### ISSUE THREAD

**Issue by bolanbujing** [facebook/proxygen#227]
I download  proxygen-2018.05.07.00 and build ,  get an error,  information is :
libtool: link: g++  -fPIC -DPIC -shared -nostdlib /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/crti.o /usr/lib/gcc/x86_64-linux-gnu/5/crtbeginS.o  .libs/HTTPServer.o .libs/HTTPServerAcceptor.o .libs/RequestHandlerAdaptor.o .libs/SignalHandler.o   ../lib/.libs/libproxygenlib.a -liberty -lwangle -lz -lssl -lcrypto -levent -lgflags -L/usr/lib64 -lpthread -lfolly -lglog -ldouble-conversion -lboost_system -lboost_thread -L/usr/lib/gcc/x86_64-linux-gnu/5 -L/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu -L/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib -L/lib/x86_64-linux-gnu -L/lib/../lib -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-linux-gnu/5/../../.. -lstdc++ -lm -lc -lgcc_s /usr/lib/gcc/x86_64-linux-gnu/5/crtendS.o /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/crtn.o  -pthread -O3 -g -g -O2 -pthread   -pthread -Wl,-soname -Wl,libproxygenhttpserver.so.0 -o .libs/libproxygenhttpserver.so.0.0.0
/usr/bin/ld: //usr/local/lib/libfolly.a(FormatArg.cpp.o): relocation R_X86_64_32 against `_ZN5folly12BadFormatArgD1Ev' can not be used when making a shared object; recompile with -fPIC

**Comment by bolanbujing** [comment]
@afrind platform is Ubuntu 16.04.4 LTS and build script is deps.sh

**Comment by suspend0** [comment]
https://github.com/facebook/proxygen/pull/229 -- this modified `deps.sh` to compile with -fPIC.  Perhaps it fixes your issue?

**Comment by bolanbujing** [comment]
@suspend0 but i don't know how to   modified deps.sh to compile with -fPIC

**Comment by suspend0** [comment]
Sorry I was unclear. I meant the Pull Request here: https://github.com/facebook/proxygen/pull/229 merged changes to deps.sh which enable -fPIC (the cmake option -DCMAKE_POSITION_INDEPENDENT_CODE=ON).  If you click through to the Pull Request you will see.

Since these changes are merged very recently updating your copy of proxygen may help.

**Comment by bolanbujing** [comment]
@suspend0 think you ，i see
