### ISSUE TITLE
Running as a service/daemon

### ISSUE THREAD

**Issue by Charles-iSentium** [facebook/proxygen#235]
Is there any documentation on running this as a daemon?  Just knowing how to run the echo demo as one would be great.  Thanks!

**Comment by afrind** [comment]
I don't think there's anything special about running a proxygen based server as a daemon.  Wrap it in nohup?

**Comment by aftabnaveed** [comment]
It's very easy these days to setup something like this in systemd.  

https://www.freedesktop.org/software/systemd/man/systemd.service.html

**Comment by afrind** [comment]
Please reopen if this doesn't answer your question.
