### ISSUE TITLE
Proxy sample - request_.getHost() returning empty string

### ISSUE THREAD

**Issue by idofilus** [facebook/proxygen#236]
When I tried the proxy sample, seems like the request_.getHost() return empty strings.

The result of curl:

`$ curl -v --header "Host: google.com" http://localhost:11000`

```
* Rebuilt URL to: http://localhost:11000/             
* Hostname was NOT found in DNS cache                 
*   Trying ::1...                                     
* connect to ::1 port 11000 failed: Connection refused
*   Trying 127.0.0.1...                               
* Connected to localhost (127.0.0.1) port 11000 (#0)  
> GET / HTTP/1.1                                      
> User-Agent: curl/7.35.0                             
> Accept: */*                                         
> Host: google.com                                    
>                                                     
< HTTP/1.1 503 Bad Gateway                            
< Date: Sun, 15 Jul 2018 18:48:13 GMT                 
< Connection: keep-alive                              
< Content-Length: 34                                  
<                                                     
* Connection #0 to host localhost left intact         
Could not parse server from URL: /
```

Of course it can be solved with:
`const std::string host = headers->getHeaders().getSingleOrEmpty("Host");`

But, why doesn't it show the correct host in the request_ ?

**Comment by afrind** [comment]
If you are curling through a proxy you need an absolute URL.  Try:

curl -x localhost:11000 http://www.google.com

**Comment by idofilus** [comment]
Yeah, it did worked.
But the issue I described also happen when I tried to put: `127.0.0.1 example.com` in the hosts file, now when I'm going to http://example.com it have the same issue. Any idea why ?

**Comment by afrind** [comment]
The proxy sample is a forward proxy and only looks at the authority in the absolute URL passed to it for where to make its connection.  I suppose you could also fallback to the Host header if a relative URL was passed, but I've always seen clients using absolute URLs to traverse forward proxies.

I'm not sure I follow what you are trying to do with 127.0.0.1 and example.com.  Can you include more details like the exact curl commands and output?

**Comment by idofilus** [comment]
Thanks, you actually made it very clear pointing out that the sample is a _forward proxy_. While my goal is _reverse proxy_.
