### ISSUE TITLE
Proxygen as a Reverse Proxy

### ISSUE THREAD

**Issue by idofilus** [facebook/proxygen#237]
As far as I understand from learning about proxygen, I believe the current open-sourced proxygen is a forward proxy. And the Facebook's proxygen reverse proxy version is currently closed-source due the deeply integration with the Facebook's internal code _(as I seen [here](https://news.ycombinator.com/item?id=8563539))_.

I want to know what the current status, how much missing from the current open source to support reverse proxy, is it possible for 1 person to keep adding missing features by he's own along the project development or is more complicated than that ?

I'm already was sold by proxygen months ago, and now I'm starting to implement it. Seeing that I have issues Reverse proxy of a HTTPS requests made the issue clear.

**Comment by idofilus** [comment]
My actual goal with proxygen as a reverse proxy is not too complicated.
I'm not sure if the issue I described is a missing component or wrong usage of the library.
HTTPS requests work great with ```curl -x localhost:11000 https://www.google.com```. But if I understand right, and I want to use it as a reverse proxy. Setting up my Windows hosts file and changing the IP to localhost, _(using of course forwarding to forward 80 to 11000)_. Then trying to use it via the browser. I get  _ERR_SSL_PROTOCOL_ERROR_. I tried to implement the snippet code of the SSL test in the tests folder. But no much success there. Am I doing something wrong .. ? or is it part of the missing components ?

**Comment by afrind** [comment]
So a reverse proxy acts like the server it is proxying - eg: you should not need the -x parameter to curl.  You would just curl http://example.com:11000, and it would be configured/hardcoded to route your request to the server it is proxying.  If you are reverse proxying more than one server, you can implement logic to decide which server to proxy to (eg: using the Host header, or other parts of the URL, headers, etc).

**Comment by idofilus** [comment]
Thanks a lot, one last thing.
In the two wrappers we can see in the _proxy_ sample, we have _onEgressPaused_ and _onEgressResumed_. Could it be a typo that the _onEgressResumed_ wrap the ```parent_.onServerEgressPaused();``` and not ```parent_.onServerEgressResumed();``` ?

https://github.com/facebook/proxygen/blob/master/proxygen/httpserver/samples/proxy/ProxyHandler.h#L109

**Comment by jalopezsilva** [comment]
@idofilus  Thanks for spotting that, it's been fixed! I'm tentatively closing this, let us know if you have any questions!
