### ISSUE TITLE
Ubuntu 14.04 LTS unable to find boost_context 

### ISSUE THREAD

**Issue by wackykid** [facebook/proxygen#239]
downloade the latest version of proxygen on Ubuntu 14.04 LTS and tried to use ./deps.sh to build... got the following error..

```
-- Found folly: /usr/local
CMake Error at /usr/share/cmake-3.2/Modules/FindBoost.cmake:1201 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.54.0

  Boost include path: /usr/include

  Could not find the following Boost libraries:

          boost_context

  Some (but not all) of the required Boost libraries were found.  You may
  need to install these additional Boost libraries.  Alternatively, set
  BOOST_LIBRARYDIR to the directory containing Boost libraries or BOOST_ROOT
  to the location of Boost.
Call Stack (most recent call first):
  CMakeLists.txt:39 (find_package)


-- Could NOT find LIBGMOCK (missing:  LIBGMOCK_MAIN_LIBRARY LIBGMOCK_LIBRARY LIBGTEST_LIBRARY LIBGMOCK_LIBRARIES LIBGMOCK_INCLUDE_DIR LIBGTEST_INCLUDE_DIR) 
-- Configuring incomplete, errors occurred!

```

**Comment by lnicco** [comment]
@wackykid thanks for reporting this issue. 
deps.sh specifies libboost-all-dev as a dependency 
and according to Ubuntu 14.04 docs that should include libbost-context-dev
https://packages.ubuntu.com/trusty/libboost-all-dev

Perhaps something went wrong on your box when installing libboost-all-dev ? could you please try manually uninstalling that package and running deps.sh again ? 

Let us know if the problem persists and there is something we can help you with, but deps.sh looks fine to me

**Comment by wackykid** [comment]
hi... thanks.. you are right.. looks like it is because in my environment LD_LIBRARY it contains paths to other project directories where by there exists part of libboost libraries in one of the directories... as a result even when i tried reinstalling the package the same problem still occurred. but once i removed the paths from LD_LIBRARY the issue is resolved.

**Comment by NoOneNo** [comment]
" my environment LD_LIBRARY it contains paths to other project directories where by there exists part of libboost libraries" 
I have same situation. how to check this ???

**Comment by wackykid** [comment]
i just ran:
`env | grep LD_LIBRARY`

After which i examine each of the path, the problem with my environment is due to me having some of my projects depended on specific boost static libraries, hence my environment was setup to point to these static libraries which are contained inside my project's sub-directories. But since my project didn't contain all the boost libraries (because they are not required) hence I encountered the error with missing boost libraries because cmake located the boost in the wrong directory. I just need to remove the paths to my project for cmake to locate the correct libraries.
