### ISSUE TITLE
install proxygen without internet

### ISSUE THREAD

**Issue by yjr930** [facebook/proxygen#243]
I need to install proxygen on a machine without internet.
I have installed all dependency, but when I run ./deps-centos.sh it seems that it must connect to github.com to download something.

--2018-08-10 14:30:22--  (try:11)  https://github.com/google/googletest/archive/release-1.8.0.zip
Connecting to github.com|52.74.223.119|:443... failed: Connection timed out.
Connecting to github.com|13.250.177.223|:443... failed: Connection timed out.
Connecting to github.com|13.229.188.59|:443... failed: Connection timed out.
Retrying.

--2018-08-10 14:30:41--  (try:12)  https://github.com/google/googletest/archive/release-1.8.0.zip
Connecting to github.com|52.74.223.119|:443... failed: Connection timed out.
Connecting to github.com|13.250.177.223|:443... failed: Connection timed out.
Connecting to github.com|13.229.188.59|:443... failed: Connection timed out.
Retrying.

--2018-08-10 14:31:00--  (try:13)  https://github.com/google/googletest/archive/release-1.8.0.zip
Connecting to github.com|52.74.223.119|:443... failed: Connection timed out.
Connecting to github.com|13.250.177.223|:443... failed: Connection timed out.
Connecting to github.com|13.229.188.59|:443... failed: Connection timed out.

How do I intall proxygen without internet?

**Comment by udippant** [comment]
As you can see in the [deps.sh](https://github.com/facebook/proxygen/blob/master/proxygen/deps.sh), proxygen requires `folly`, and `wangle`, which if not present, attempts to fetch them with `git`.

You can try manually installing those repos where proxygen expects them to be (with the proper revision checked out) and try with locally removing those fetches in `deps.sh`.
