### ISSUE TITLE
Accurate representation of proxygen

### ISSUE THREAD

**Issue by leecalcote** [facebook/proxygen#251]
Hi,

I'm trying to compile and accurate list of projects and offerings that includes Proxygen. Would you mind making a few quick comments to ensure Proxygen is well-represented?

The list is at https://layer5.io/landscape/ and is referenced by a good many readers in a recent short book I authored - https://www.linkedin.com/pulse/enterprise-path-service-mesh-architectures-lee-calcote/

**Comment by lnicco** [comment]
Hi @leecalcote, 
we are happy for proxygen to be featured in your list!
the OSS Proxygen library not only powers our load balancer, but it's also used by HHVM
https://github.com/facebook/hhvm

Please let us know if there is more specific information that we can provide and that you may want to report in your list. 

Also, there is a Proxygen discussion group at
https://groups.google.com/forum/#!forum/facebook-proxygen
I'd like to encourage you to post there to ask who is using the proxygen lib and what they use it for

**Comment by leecalcote** [comment]
Thank you, @lnicco! There's no commercial offering of Proxygen, correct? Which month and year was the project announced and which month and year do you consider it GA'ed / 1.0ed (was production-ready)?

// @girishranganathan

**Comment by afrind** [comment]
Correct there is no commercial offering.  It was announced in November 2014, which was effectively GA since Facebook was already using this code in production at that time.

**Comment by leecalcote** [comment]
That's great, @afrind. This sheet is updated with what is hopefully complete information - https://layer5.io/landscape. Please do point out any other details that you consider should be highlighted.

**Comment by afrind** [comment]
Looks great!
