### ISSUE TITLE
Build Broken (due to fizz?)

### ISSUE THREAD

**Issue by jmccl** [facebook/proxygen#256]
Running deps.sh on debian results in this:

libtool: link: g++ -pthread -DLIBMC_FBTRACE_DISABLE -Wno-missing-field-initializers -Wno-deprecated -O3 -g -W -Wall -Wextra -Wno-unused-parameter -fno-strict-aliasing -g -O2 -o SessionTests HTTPTransactionSMTest.o DownstreamTransactionTest.o HTTPDownstreamSessionTest.o HTTPSessionAcceptorTest.o HTTPUpstreamSessionTest.o HTTP2PriorityQueueTest.o MockCodecDownstreamTest.o HTTPDefaultSessionCodecFactoryTest.o TestUtils.o -pthread  ../../../services/.libs/libproxygenservices.a -L/usr/lib64 ../../../test/.libs/libtestmain.a ../../../test/.libs/libtesttransport.a ../../../utils/.libs/libutils.a ../../codec/test/.libs/libcodectestutils.a ../../.libs/libproxygenhttp.a -lwangle -lfizz -lz -lssl -lcrypto -levent -lgflags -lpthread -lfolly -lglog -ldouble-conversion -lboost_system -lboost_thread -pthread
/usr/bin/ld: //usr/local/lib/libwangle.so: undefined reference to symbol 'randombytes_buf'
//usr/lib/x86_64-linux-gnu/libsodium.so.18: error adding symbols: DSO missing from command line

I'm assuming this is due to the addition of fizz.

**Comment by afrind** [comment]
CC: @knekritz in case you have any ideas

**Comment by jmccl** [comment]
The patch above fixes this.

**Comment by afrind** [comment]
Will work on merging it, thanks

**Comment by miaogen123** [comment]
Has this matter been solved? i met it just now .

**Comment by jmccl** [comment]
The move to cmake appears to have fixed this.
