### ISSUE TITLE
dist tarballs missing build files (e.g. CMakeLists.txt)

### ISSUE THREAD

**Issue by eklitzke** [facebook/proxygen#258]
The dist tarballs (the ones listed on the Github "releases" page, e.g. https://github.com/facebook/proxygen/archive/v2019.03.18.00.tar.gz ) are missing `CMakeLists.txt` so you can't easily build proxygen from them. They're also missing the generated autotools files (e.g. they include `configure.ac`, but not a pre-generated `configure` script) which is less serious but still annoying and non-standard.

**Comment by mingtaoy** [comment]
The commit introducing CMakeLists was made after the 2019.03.18 tag was created. It will be in the release tag in the following week.

```
$ git merge-base --is-ancestor v2019.03.18.00 cfa2dd5d0ac376e5bcef6ec8fc5bbae2613f894e && echo 'yes'
yes
```

**Comment by udippant** [comment]
It is now included in the new release. Closing it.
Please let us know if you see any issues.
