### ISSUE TITLE
Failed to build when using --with-quic for deps.sh 

### ISSUE THREAD

**Issue by adikabintang** [facebook/proxygen#267]
OS: Ubuntu 18.04
gcc version 7.4.0
cmake version 3.10.2
GNU Make 4.1
Proxygen commit `2791720c7e2423a20b6796ce31ffec8bab300cab`

I wanted to try the `hq` example, so I build the proxygen with `./deps.sh --with-quic`. However, when linking CXX executable hq, it cannot find `-lmvfst_fizz`. Here is the error output:
```
[100%] Linking CXX executable hq
/usr/bin/ld: cannot find -lmvfst_fizz
collect2: error: ld returned 1 exit status
proxygen/httpserver/CMakeFiles/hq.dir/build.make:181: recipe for target 'proxygen/httpserver/hq' failed
make[2]: *** [proxygen/httpserver/hq] Error 1
CMakeFiles/Makefile2:432: recipe for target 'proxygen/httpserver/CMakeFiles/hq.dir/all' failed
make[1]: *** [proxygen/httpserver/CMakeFiles/hq.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
```

I have tried to build and install the latest mvfst (`2e6e2898a3de2de1d0cdadf1b62b9c786539029b`) but the problem still exists.

**Comment by lnicco** [comment]
thanks for reporting the issue @adikabintang. 
We have a fix for it, it will be synced to github soon.

**Comment by lnicco** [comment]
@adikabintang this should be working now. Could you please rebase and give it another try ?

**Comment by adikabintang** [comment]
@lnicco I have tried building from master (`f9dbc6fd54404a9005579549c3c0b8b254381d48`) and it works now. Thanks!

**Comment by adikabintang** [comment]
@lnicco First of all, I am sorry if I shouldn't ask here. I am not sure if I have to create a new issue or whether it's ok to ask here.

I ran the client by running:
```
./hq -mode client -draft_version 20 -early_data true -host 127.0.0.1 -port 4433 -path / -httpversion 3
```

and the server by running:
```
./hq -mode server -port 4433 -draft_version 20 -early_data true -host 0.0.0.0 -httpversion 3
```

The client printed the headers upon completing the request. I noticed the `Connection` header there. The `Connection` header must not exist for HTTP2 ([wikipedia](https://en.wikipedia.org/wiki/List_of_HTTP_header_fields)) and it looks like that the same rule applies for http over quic ([wiki](https://github.com/quicwg/base-drafts/wiki/QPACK-Static-Table)).

Is this behavior expected? Or am I missing something?

**Comment by lnicco** [comment]
@adikabintang yes there is no Connection header in HTTP/2 and HTTP/3. 
The message in the hq sample client/server is printed at the handler (see `CurlClient::sendRequest` at `request_.dumpMessage(4);`), hence that is independent from what actually gets sent on the wire. 
The `Connection` header will get striped at a lower layer than the handler (in the codec). 

As a proof of this you can print the message received on the server side by running the server with `--v=4`

**Comment by adikabintang** [comment]
@lnicco Oh yes I can see that with --v=4. If I want to try the "real" HTTP3 client and server, is it true that I only need to give `-httpversion=3.0` and `-protocol=h3-20` to run the `hq` example? I choose `-protocol=h3-20` since [HQSession.cpp](https://github.com/facebook/proxygen/blob/master/proxygen/lib/http/session/HQSession.cpp#L67) implements [h3-20](https://tools.ietf.org/html/draft-ietf-quic-http-20#section-2.1), but I have no clue about option `-httpversion`.
