### ISSUE TITLE
Docker file for proxygen

### ISSUE THREAD

**Issue by bkannadassan** [facebook/proxygen#269]
Hi All,

  I am lookin for a Dockerfile for proxygen, I found one in github docker jrandall/proxygen, this docker works fine but the Dockerfile inside the same is giving error. Please let me know if any Dockerfile available for the same. Btw do we have rpm for Centos 7 ?.

rgds
Balaji

**Comment by bkannadassan** [comment]
Btw to add centos deps also broken.

**Comment by sptrakesh** [comment]
https://hub.docker.com/repository/docker/sptrakesh/proxygen shows how I built it for Alpine.

**Comment by jbeshay** [comment]
Looking at this a few years too late, but better late than never!

I am not sure if you're referring to an image to use for building proxygen or to run one of the binaries included. EIther ways, we don't have an official docker image for proxygen. 

The closest I know of is the Dockerfile used to build the container image for QUIC interop testing:
https://github.com/lnicco/mvfst-qns/blob/master/Dockerfile

This is Ubuntu-based. It builds proxygen in a container then packages the `hq` binary and its dependencies in the resulting image. 

I will proceed to close this issue but feel free to re-open if you're still looking for an answer and the Dockerfile above is not sufficient.
