### ISSUE TITLE
Gitter chat room

### ISSUE THREAD

**Issue by sethkrasnianski** [facebook/proxygen#27]
While google groups offer great open forums, a channel for bouncing ideas around would be great. Having a gitter channel for this repository would support immediate correspondence and be beneficial for the community aspect of this project.

**Comment by afrind** [comment]
We have a channel on irc.freenote.net called #proxygen.

**Comment by sethkrasnianski** [comment]
:+1:

**Comment by afrind** [comment]
Typo: irc.freenode.net
