### ISSUE TITLE
install script doesn't work after move to CMake

### ISSUE THREAD

**Issue by jmccl** [facebook/proxygen#270]
:# ./install.sh 
make: *** No rule to make target 'uninstall'.  Stop.

**Comment by lnicco** [comment]
ouch, my fault! 
thanks for reporting

**Comment by lnicco** [comment]
CMake does not provide an uninstall target by default
https://gitlab.kitware.com/cmake/community/wikis/FAQ#can-i-do-make-uninstall-with-cmake

a proper fix is coming (probably tomorrow)
in the meantime you can comment out the uninstall command

**Comment by lnicco** [comment]
@jmccl should work now, 
please give it a try and reopen this issue if needed

**Comment by jmccl** [comment]
I'm not getting this. (Docker ubuntu 18.04 image)

root@f47f0131f19d:/proxygen/proxygen# ./install.sh 
Scanning dependencies of target uninstall
CMake Error at cmake_uninstall.cmake:2 (message):
  Cannot find install manifest:
  /proxygen/proxygen/_build/install_manifest.txt


CMakeFiles/uninstall.dir/build.make:57: recipe for target 'CMakeFiles/uninstall' failed
make[3]: *** [CMakeFiles/uninstall] Error 1
CMakeFiles/Makefile2:968: recipe for target 'CMakeFiles/uninstall.dir/all' failed
make[2]: *** [CMakeFiles/uninstall.dir/all] Error 2
CMakeFiles/Makefile2:975: recipe for target 'CMakeFiles/uninstall.dir/rule' failed
make[1]: *** [CMakeFiles/uninstall.dir/rule] Error 2
Makefile:539: recipe for target 'uninstall' failed
make: *** [uninstall] Error 2

**Comment by lnicco** [comment]
oh yeah, this is still broken. reopening
