### ISSUE TITLE
'make install' should not install 'samples'

### ISSUE THREAD

**Issue by jmccl** [facebook/proxygen#271]
‘make install’ installs ‘echo’, ‘static’, ‘push’ and ‘proxy’. If using the build.sh script this isn’t a problem because now it doesn’t install to system directories. However, I modified build.sh to install to system directories so that I wouldn’t have to modify my own builds to look in the proxygen build directory (and _build/deps for the dependencies.) 

The problem is that ‘echo’ takes precedence over the shell ‘echo’ command, which breaks a bunch of unrelated stuff.

(Although this is clearly technically 'not a bug' since I had to modify build.sh to cause it, it is however unusual 'make install' behavior and I doubt I'll be the only one debugging it.)

**Comment by lnicco** [comment]
yeah makes sense, and that's why the sample curl client is called `pcurl`.
perhaps the right fix is to prefix all the samples with `proxygen_`: `proxygen_curl`, `proxygen_echo` and so on. What do you think ?

**Comment by jmccl** [comment]
Sure, that sounds fine to me.

**Comment by jmccl** [comment]
BTW, hq has cmake install configured but didn't seem to be installed. I didn't look into what was going on though.

**Comment by lnicco** [comment]
@jmccl I fixed the binary names. I cannot however reproduce the problem with `hq` you mentioned. Any chance you can provide a repro?

**Comment by jmccl** [comment]
@lnicco I didn't run build.sh with '--build-quick', so hq doesn't get built. There's no issue here. Thanks for fixing this.
