### ISSUE TITLE
HTTP/2 DOS VULNERABILITIES

### ISSUE THREAD

**Issue by sathipkr** [facebook/proxygen#278]
Hi
  We read about the newfound HTTP/2 vulnerabilities (https://github.com/Netflix/security-bulletins/blob/master/advisories/third-party/2019-002.md)
Are there any patches/fixes planned for the same ?

Thanks
Satwik

**Comment by afrind** [comment]
These have been addressed in commits 864818f6 and ce5fb2b8.  Please fetch the latest trunk to pick theseu p.
