### ISSUE TITLE
Crash from Samsung KNOX Summer 2019 Security Patches 

### ISSUE THREAD

**Issue by mattvlasach** [facebook/proxygen#282]
Across various Summer 2019 releases made by Samsung (May, June, July), we have observed the proxygen library is failing and crashing its host app (Facebook and Instagram, at least) when a proxy is configured on the device.  This is configuration common in many high-security enterprise environments.

When a proxy configuration is applied on a Samsung Android device, a proxy service is created on localhost. Networking libraries – like proxygen – request the proxy host from the OS to route subsequent web requests, and the OS (prior to the security updates) returns `localhost`.  Proxygen obeys and sends its proxified web requests to `localhost`. 

So this has all worked great until these security patches, at which point Samsung now returns `[::1]` as the proxy destination.  Proxygen does not like this change, throwing the below exception and eventually crashing:

```09-07 23:44:55.331 12056 12129 E fb4a.AppStateLoggerExceptionHandler: Handling uncaught exception
09-07 23:44:55.331 12056 12129 E fb4a.AppStateLoggerExceptionHandler: com.facebook.jni.CppSystemErrorException: Failed to resolve address for '[::1]':  (error=8): Exec format error
09-07 23:44:55.331 12056 12129 E fb4a.AppStateLoggerExceptionHandler: 	at com.facebook.jni.ThreadScopeSupport.runStdFunctionImpl(Native Method)
09-07 23:44:55.331 12056 12129 E fb4a.AppStateLoggerExceptionHandler: 	at com.facebook.jni.ThreadScopeSupport.runStdFunction(:0)
09-07 23:44:55.331 12056 12129 E fb4a.AppStateLoggerExceptionHandler: 	at com.facebook.proxygen.EventBase.loopForever(Native Method)
09-07 23:44:55.331 12056 12129 E fb4a.AppStateLoggerExceptionHandler: 	at com.facebook.proxygen.HTTPThread.run(:20)
09-07 23:44:55.331 12056 12129 E fb4a.AppStateLoggerExceptionHandler: 	at X.13i.run(:7)
09-07 23:44:55.331 12056 12129 E fb4a.AppStateLoggerExceptionHandler: 	at java.lang.Thread.run(Thread.java:764)
``` 
It appears that Samsung has erroneously added the square brackets to represent an IPv6 literal address (the proxy address on `::1`), when square brackets should only be used in URLs, e.g. `http://[::1]` ( https://tools.ietf.org/html/rfc2732).  This is causing the lib to try to resolve `::1` via DNS instead of using it as a literal IP address.  Further the DNS lookup of `::1`  is throwing the final exception because it cannot handle the IPv6 address format in the DNS lookup itself (`(error=8): Exec format error` , it is probably expecting a hostname, etc.)

While Samsung will be reverting this change, they will not be reverting it across all platforms and they expect the change to not be committed until early 2020(!).  This will leave a large percentage of modern Galaxy devices (S8, S9, and S10) unable to use proxygen-based apps on enterprise networks for months or potentially indefinitely.

Would it be possible to check for this specific string literal (`[::1]`) when returned as the proxy address to use and normalize it to `::1` so that everything continues to work downstream as expected?

**Comment by amirlivneh** [comment]
Thanks for reporting this. We addressed the issue in our proxygen-based apps. The change will be available in one of the next releases.

**Comment by mattvlasach** [comment]
For the record, this has been resolved successfully in the Facebook, Messenger, and Instagram apps released around September 24, 2019.  Thank you!

**Comment by JKNAUG** [comment]
@mattvlasach would you mind to share how it was actually solved in the mentioned Apps? Because the corresponding ticket in the mono repo still doesn't provide a solution and we're in desperate need for at least a workaround.

**Comment by mattvlas** [comment]
@JKNAUG Unfortunately i'm not sure as the change was made by @amirlivneh in the core applications.  We just observed the apps began working properly once the builds with the fixes hit the play store.  Sorry I can't be of more help!
