### ISSUE TITLE
How to configure HTTPS server

### ISSUE THREAD

**Issue by chenchenliux** [facebook/proxygen#283]
Proxygen how to use openssl self-built certificate, I always report the following error:
*** Check failure stack trace: ***
    @       0x7f9c806718  google::LogMessage::Fail()
    @       0x7f9c808614  google::LogMessage::SendToLog()
    @       0x7f9c806290  google::LogMessage::Flush()
    @       0x7f9c808eb4  google::LogMessageFatal::~LogMessageFatal()
    @           0x522a3c  wangle::Acceptor::init()
    @           0x47c2e4  proxygen::AcceptorFactory::newAcceptor()
    @           0x548884  wangle::ServerWorkerPool::threadStarted()
    @           0x4bd488  folly::ThreadPoolExecutor::addObserver()
    @           0x473138  wangle::ServerBootstrap<>::group()
    @           0x464e90  proxygen::HTTPServer::start()
    @           0x437cf8  _ZZ4mainENKUlvE_clEv
    @           0x447824  _ZNSt12_Bind_simpleIFZ4mainEUlvE_vEE9_M_invokeIJEEEvSt12_Index_tupl
eIJXspT_EEE
    @           0x447760  _ZNSt12_Bind_simpleIFZ4mainEUlvE_vEEclEv
    @           0x4476e8  _ZNSt6thread5_ImplISt12_Bind_simpleIFZ4mainEUlvE_vEEE6_M_runEv
    @       0x7f9c3c7280  (unknown)
    @       0x7f9c556fc4  start_thread

**Comment by chenchenliux** [comment]
I use it this way:

wangle::SSLContextConfig sslConfig;
  std::string certPath = "/home/xx/work/ssl/server-cert.pem";
  std::string keyPath = "/home/xx/work/ssl/server-key.pem";
  std::string passwordPath = "/home/xx/work/ssl/passwd";
  sslConfig.addCertificate(certPath, keyPath, passwordPath);

How else does sslConfig need to be configured?? who can help me

**Comment by afrind** [comment]
See an example in this unit test: 

https://github.com/facebook/proxygen/blob/master/proxygen/httpserver/tests/HTTPServerTest.cpp#L157

Looks like it's dying in a LOG(FATAL) but you didn't include the error message

**Comment by chenchenliux** [comment]
How to use openssl generate the self-built certificate, need the client to add the certificate?

**Comment by chenchenliux** [comment]
openssl genrsa -des3 -out privkey.pem 2048

**Comment by chenchenliux** [comment]
> See an example in this unit test:
> 
> https://github.com/facebook/proxygen/blob/master/proxygen/httpserver/tests/HTTPServerTest.cpp#L157
> 
> Looks like it's dying in a LOG(FATAL) but you didn't include the error message

**Comment by chenchenliux** [comment]
> See an example in this unit test:
> 
> https://github.com/facebook/proxygen/blob/master/proxygen/httpserver/tests/HTTPServerTest.cpp#L157
> 
> Looks like it's dying in a LOG(FATAL) but you didn't include the error message

openssl genrsa -des3 -out privkey.pem 2048
openssl req -new -x509 -key privkey.pem -out cacert.pem -days 1095

std::string certPath = "./work/ssl_1028_1/cacert.pem";
  std::string keyPath = "./work/ssl_1028_1/privkey.pem";
  std::string passwordPath = "";
  
  sslConfig.isDefault = true;
  sslConfig.setCertificate(certPath, keyPath, passwordPath);

terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to read private key from file: ./work/ssl_1028_1/privkey.pem, password file: Failed to load cert or key at key path ./work/ssl_1028_1/privkey.pem, cert path ./work/ssl_1028_1/cacert.pem

who can help me???
