### ISSUE TITLE
how to build hq in qt?

### ISSUE THREAD

**Issue by jaehong8754** [facebook/proxygen#293]
hello!

i want build hq in qt 

my qt project is add httpserver/samples/hq files and link all library file in proxygen folder 
 (libproxygen.a, libmvfst_client.a, libmvfst_server.a, libfolly.a, libfizz.a, libwangle.a, ...)

but fail to build and issue message is

/home/wg/proxygen/proxygen/httpclient/samples/curl/CurlClient.cpp:169: error: undefined reference to `proxygen::HTTP2Codec::requestUpgrade(proxygen::HTTPMessage&)'

/home/wg/proxygen/proxygen/httpclient/samples/curl/CurlClient.cpp:154: error: undefined reference to `proxygen::HTTPUpstreamSession::newTransaction(proxygen::HTTPTransactionHandler*)'
...

I wonder if there is any documentation to build

**Comment by afrind** [comment]
That's strange, HTTPUpstreamSession and HTTP2Codec are both part of libproxygen.a.

**Comment by afrind** [comment]
Assuming this is not still an issue, closing for now.  Please reopen or open a new issue if you need more assistance.
