### ISSUE TITLE
The deployment of server and client

### ISSUE THREAD

**Issue by weiyuxingchen** [facebook/proxygen#295]
Thanks for your contribution and perseverance in awesome proxygen！
I have built the proxygen and run server&client successfully in my Ubuntu, but I wonder how to deploy proxygen, server and client in another different machines with Linux OS or Windows. Is it necessary to bulid the project from scratch or using something helpful like docker to reduce the complexity in deployment？Thanks!

**Comment by afrind** [comment]
Since proxygen is library, rather than a service, there aren't any pre-built dockers for deployment, etc.  The samples are not meant for widespread deployment, but rather to guide you on how to build an HTTP enabled service or client using proxygen.
