### ISSUE TITLE
Can not run  QUIC HTTP/3 server inside Docker

### ISSUE THREAD

**Issue by yaseenit** [facebook/proxygen#296]
Hello there,
I was able to build the library successfully on my machine (ubuntu 18 inside a docker container). I used (./build.sh --with-quic ) because I want to support the connections with QUIC. 
But I am getting the following error: I will appreciate any help.

root@cbfb8b357f25:/proxygen/proxygen/_build/bin# ./hq --mode=server
terminate called after throwing an instance of 'folly::AsyncSocketException'
  what():  AsyncSocketException: failed to bind the async udp socket for:[::1]:6666, type = Socket not open, errno = 99 (Cannot assign requested address)
*** Aborted at 1572873607 (unix time) try "date -d @1572873607" if you are using GNU date ***
PC: @     0x7f7eace67e97 gsignal
*** SIGABRT (@0x72a9) received by PID 29353 (TID 0x7f7ea8de3700) from PID 29353; stack trace: ***
terminate called recursively
    @     0x7f7eaef87890 (unknown)
    @     0x7f7eace67e97 gsignal
    @     0x7f7eace69801 abort
terminate called recursively
terminate called recursively
    @     0x7f7ead85c957 (unknown)
F1104 13:20:07.360257 29353 QuicServer.cpp:236] Check failed: initialized_ 
*** Check failure stack trace: ***
    @     0x7f7eae3a70cd  google::LogMessage::Fail()
    @     0x7f7eae3a8f33  google::LogMessage::SendToLog()
    @     0x7f7ead862ab6 (unknown)
    @     0x7f7eae3a6c28  google::LogMessage::Flush()
    @     0x7f7eae3a9999  google::LogMessageFatal::~LogMessageFatal()
    @     0x55d8ef23ca9b  (unknown)
    @     0x55d8ef241c1f  (unknown)
    @     0x55d8ef0fc72b  (unknown)
    @     0x55d8ef0c6bec  (unknown)
    @     0x7f7eace4ab97  __libc_start_main
    @     0x55d8ef0cbf5a  (unknown)
    @     0x7f7ead861b19 (unknown)
Aborted (core dumped)

 I will appreciate any help.

**Comment by afrind** [comment]
Does your docker container have IPv6?

**Comment by yaseenit** [comment]
Thank you @afrind !
I enabled docker ipv6 and that did the trick.
Here is how:
etc/docker/daemon.json example:
{
    "ipv6": true,
    "fixed-cidr-v6": "2001:0db8:1234:5678:9abc::1/80"
}
also added --ipv6 to /usr/lib/systemd/system/docker.service and then reload and restart.
