### ISSUE TITLE
Cannot upload files with large volume using mothod POST

### ISSUE THREAD

**Issue by Enjia** [facebook/proxygen#297]
When I use --body to upload large volume file（~500M）rather than some tiny file such as txt, there comes some problem:

I1111 13:56:39.195076   902 HQSession.cpp:1942] onFlowControlUpdate sess=proto=h1q-fb, client CID=afea3903471e1721, server CID=400005c002e94099, local=[::]:34098, [::1]:6666=upstream, drain=done: streamID=0
I1111 13:56:39.195106   902 HTTPTransaction.cpp:1426] asked to resume egressproto=h1q-fb, client CID=afea3903471e1721, server CID=400005c002e94099, local=[::]:34098, [::1]:6666=upstream, drain=done, streamID=0
I1111 13:56:39.195132   902 CurlClient.cpp:287] Egress resumed
E1111 13:56:39.195147   902 StateMachine.h:33] HTTPTransactionEgress: invalid transition tried: EOMQueued sendEOM
F1111 13:56:39.195168   902 HTTPTransaction.cpp:1172] Check failed: HTTPTransactionEgressSM::transit( egressState_, HTTPTransactionEgressSM::Event::sendEOM) , proto=h1q-fb, client CID=afea3903471e1721, server CID=400005c002e94099, local=[::]:34098, [::1]:6666=upstream, drain=done, streamID=0
*** Check failure stack trace: ***
    @     0x7f0c8e4900cd  google::LogMessage::Fail()
    @     0x7f0c8e491f33  google::LogMessage::SendToLog()
    @     0x7f0c8e48fc28  google::LogMessage::Flush()
    @     0x7f0c8e492999  google::LogMessageFatal::~LogMessageFatal()
    @     0x55ff0957495d  (unknown)
    @     0x55ff095f6477  (unknown)
    @     0x55ff095f654b  (unknown)
    @     0x55ff09571434  (unknown)
    @     0x55ff09571971  (unknown)
    @     0x55ff095989e9  (unknown)
    @     0x55ff09626647  (unknown)
    @     0x55ff0962b53c  (unknown)
    @     0x55ff09652ebf  (unknown)
    @     0x55ff098dc843  (unknown)
    @     0x7f0c900638f8  (unknown)
    @     0x7f0c9006433f  event_base_loop
    @     0x55ff098e269a  (unknown)
    @     0x55ff09520379  (unknown)
    @     0x55ff095206d2  (unknown)
    @     0x55ff094f6d84  (unknown)
    @     0x7f0c8cf33b97  __libc_start_main
    @     0x55ff094fc0aa  (unknown)

Could you please tell me how to upload files with large volumes? Thanks

**Comment by afrind** [comment]
I see you closed this issue so I assume you found a fix.  Please reopen if you want us to investigate.
