### ISSUE TITLE
New to http development, is there any tutorial?

### ISSUE THREAD

**Issue by ParanoiaUPC** [facebook/proxygen#299]
Hi there, I failed to find any tutorial or blog about how to get start with proxygen. Although there are same sample codes in the project, it's too hard for a beginner to understand the codes.
I just wonder if there was any tutorial for proxygen. Thanks a lot!

**Comment by afrind** [comment]
The readme has a high level overview of the proxygen architecture: https://github.com/facebook/proxygen/blob/master/README.md. There's not a tutorial though.

The samples show you how to write a handler that can receive and respond to HTTP requests.  echo is probably the simplest - just take a look at EchoHandler - most of the other code there in EchoServer is just boilerplate to setup and start the server.  I also recommend building the sample, setting breakpoints, and stepping through in gdb to get a better idea of what is going on.

**Comment by ParanoiaUPC** [comment]
Thank you @afrind that helps a lot :)

**Comment by afrind** [comment]
Great!
