### ISSUE TITLE
Does Proxygen make use of  Multiplexing encapsulated in QUIC

### ISSUE THREAD

**Issue by Enjia** [facebook/proxygen#302]
Hi
I wonder when running proxygen which depends on mvfst, is there any codes indicate that proxygen makes use of multiplexing because it's an important trait in QUIC to avoid the head-of-line blocking issue, or if there's any interface for users to set up the number of cocurrent streams in one connection？ Thanks！

**Comment by afrind** [comment]
If you look at the HQServer example (proxygen/httpserver/samples/hq/HQServer.cpp), in HQServerTransportFactory::make(), you can call sock_->setTransportSettings(...), which, among other things, controls the maximum level of concurrency from the client: `advertisedInitialMaxStreamsBidi`.  The default appears to be unlimited, which perhaps is too high :)

**Comment by afrind** [comment]
Some of the other transport settings defaults there are also nonsensical (flow control = 0 is problematic).  Beware of gotchas until we clean that up.

**Comment by Enjia** [comment]
Thanks, yes actually I have found that param before, the core issue I want to know is how data(eg. a huge size file) is split and packed into several stream concurrently and automatically as QUIC draft says, I  would be appreciate if you can point out the core code for streams splitting process because I just found some relative code in tperf.cpp where there's a predefined params named "numStreams" as well as a code line: buf = folly::IOBuf::createChain(std::max<uint64_t>(maxToSend / numStreams_, 64), blockSize_). Thanks again :）

**Comment by yangchi** [comment]
I'm not sure if HQClient or HQServer has any of that magic, but at least the Mvfst transport doesn't automatically split a large input into multiple streams for you. You need to split the input yourself and create streams to send them.

I don't think Quic draft says transport will automatically split input into multiple streams. In fact, bytes within one stream and across multiples streams have different delivery order guarantees. So only the users of the transport, not the transport, can possibly know if something should belong to one stream or multiple streams.

**Comment by afrind** [comment]
The HTTP/3 specification states that a single request/response pair uses a single transport stream.  I'm not sure what you are hoping to gain by splitting a single file amongst multiple streams, but you could do so by issuing Range requests (eg: HTTP GETs each with a different Range header).
