### ISSUE TITLE
http_parser.data bingding issue

### ISSUE THREAD

**Issue by nieyanbing** [facebook/proxygen#304]
If HTTP1xCodec is called in the following cases:
auto codec = std::move(HTTP1xCodec(...));
Because http_parser_init is only called in the constructor and the data binding is also in the constructor.
 the callbacks of http_parser_execute will be invalid.

**Comment by afrind** [comment]
Thanks for the report.  I guess in all this time we've never needed to move an HTTP1xCodec.

**Comment by afrind** [comment]
I don't think we are going to prioritize this, but we'd accept a PR for it.  I'm going to close it out for now.
