### ISSUE TITLE
macOS: Build fails with various jemalloc redefiniton errors

### ISSUE THREAD

**Issue by brakmic** [facebook/proxygen#310]
Hi,

I am running into several *redefinition errors*:

```shell
folly/memory/detail/MallocImpl.h:43:17: error: redefinition of 'xallocx' as different kind
                
folly/memory/detail/MallocImpl.h:44:17: error: redefinition of 'sallocx' as different kind
      of symbol
    
folly/memory/detail/MallocImpl.h:45:15: error: redefinition of 'dallocx' as different kind

folly/memory/detail/MallocImpl.h:46:15: error: redefinition of 'sdallocx' as different kind
```

This, obviously, is a problem coming from `folly` and there is also a [PR](https://github.com/facebook/folly/pull/1264) related to it. 

Now, I am not sure if there is an alternative way to overcome it or should I simply wait until a proper solution has been merged into `folly`?

I'm running **macOS Catalina 10.15.2** with **clang 9.0.0** and **jemalloc 5.2.1**

Cheers,

**Comment by mjoras** [comment]
There's unfortunately nothing we can really do if folly is having build errors, as we have a hard dependency on it and no way to carry diffs against it.

Feel free to ping on that PR, I can also ping on it internally.
