### ISSUE TITLE
how to use SessionPool and SessionHolder

### ISSUE THREAD

**Issue by stevezhou6** [facebook/proxygen#313]
I'm trying to implement a connection pool for the http client.
I'm attempting to store for every remote address (host:port) a queue of HTTPUpstreamSessions that I can reuse.

but  sessionpool  can only be used from one thread。 and not support find url。
it seam one host:port one sessionpool.

**Comment by afrind** [comment]
That's correct.  HTTPSessions cannot be shared between threads concurrently, although with some effort you can move an idle one between threads.  

Our primary proxy has the following design:

A "Server" class that represents a single IP/port which has
 * folly::ThreadLocal<SessionPool>
 * ServerIdleSessionController

We also have a "Pool" class which holds a list of servers and a "LoadBalancingAlgorithm" class which can be used to get a Server from a Pool.

**Comment by sindhudhatri** [comment]
Hi, is this SessionPool class to be used only for httpserver?
We are also trying to implement a http client using proxygen, where we want to have pool of  connections opened and use it with a server from a single or multiple threads. 
Can you please clarify if we can use the SessionPool or not for the client handling. 
Thank you.

**Comment by afrind** [comment]
SessionPool is designed to be used by an HTTP client to do exactly what you suggest.

**Comment by sindhudhatri** [comment]
Thanks a lot for your response.
