### ISSUE TITLE
GSO issue among different Linux kernel versions

### ISSUE THREAD

**Issue by Enjia** [facebook/proxygen#315]
Hi I found that if I set the GSO param in Linux with kernel version 4.14 the transfer speed slowed down comparing to same system but with higher kernerl version. I checked out that GSO is designed for Linux with higer version beyond 4.14. So besides upgrade system is there any good choice to enable GSO to play a role in my current system? Thanks!

**Comment by afrind** [comment]
This sounds like it may not be specific to the proxygen HTTP libraries?

**Comment by Enjia** [comment]
Actually in different kernel versions I use the same libraries, but when server starts up and begins to send data in Linux with kernerl version 4.14, the code "sock.getGSO() = -1" in QuicBatchWriter.cpp track down the error(92) message "netops::getsockopt(fd_, SOL_UDP, UDP_SEGMENT, &gso, &optlen)". Some relative blogs say that the acceleration using UDP GSO can only satisfy Linux systems with appropriate kernel version, So I just wonder if there's any solution to accelerate speed using GSO in Linux with low kernel version such as 4.14 other than upgrade system to higher version   to cater to GSO demand?

**Comment by mjoras** [comment]
@Enjia the only option I'm aware of is to either upgrade the kernel or backport the GSO patchset to earlier Linux versions. I believe they apply relatively cleanly to 4.16 (not all the features were present until 4.18 IIRC).

Other than that I'm not aware of any solution for using GSO. You could alternatively use sendmmsg (which our batch writer also supports) which should give you some speedup over single sendmsg calls.

**Comment by Enjia** [comment]
Thanks a lot. One more question, have you done some statistical tests about acceleration effect of GSO applied in your applications?

**Comment by mjoras** [comment]
@Enjia It can have an effect of 10-20% on CPU cycles per batch send, which is quite significant. This is largely in line with what others have found as well.
