### ISSUE TITLE
Where can I find binaries for Mac OS X or Ubuntu?

### ISSUE THREAD

**Issue by MathBunny** [facebook/proxygen#318]
Are there binaries offered for OS X or Ubuntu? I don't have the hardware to compile all the dependencies, and I just want to setup a simple HTTP server using Proxygen and Folly. Thanks

**Comment by triplewy** [comment]
Have you tried building with `-t` (no tests) flag set? You could also try using linux swapfiles if you have a memory constraint.

**Comment by mjoras** [comment]
We don't distribute packages unfortunately, since we don't have the resources to maintain them. What @triplewy suggests above is a good idea, though.

**Comment by MathBunny** [comment]
Thanks, will close this for now then.
