### ISSUE TITLE
HTTPSessionBase::InfoCallback  onRequest callback

### ISSUE THREAD

**Issue by stevezhou6** [facebook/proxygen#319]
proxygen::HTTPSessionBase::InfoCallback{
    virtual void onRequestBegin(const HTTPSessionBase&) {
    }
    virtual void onRequestEnd(const HTTPSessionBase&,
                              uint32_t /*maxIngressQueueSize*/) {
    }
}
first call onRequestEnd then call onRequestBegin

**Comment by afrind** [comment]
I'm not sure I'm following your question - you are saying that onRequestEnd is called before onRequestEnd sometimes?  Can you send the HTTP request that reproduces that?

**Comment by stevezhou6** [comment]
yes ， onRequestEnd is called before onRequestEnd。
`
class CurlClient
    : public proxygen::HTTPConnector::Callback
    , public proxygen::HTTPTransactionHandler 
    , public proxygen::HTTPSessionBase::InfoCallback {

void CurlClient::connectSuccess(HTTPUpstreamSession* session) {
  session->setInfoCallback(this);
 ...
}

  void onRequestBegin(const proxygen::HTTPSessionBase&) {
    LOG(INFO) << "onRequestBegin";
  }
  void onRequestEnd(const proxygen::HTTPSessionBase&,
                    uint32_t /*maxIngressQueueSize*/) {
    LOG(INFO) << "onRequestEnd";
  }

I0428 09:56:37.994102  9396 CurlClientMain.cpp:97] Trying to connect to 52.74.223.119:443
I0428 09:56:38.295825  9396 CurlClient.h:138] onRequestEnd
I0428 09:56:38.887997  9396 CurlClient.h:134] onRequestBegin

`
