### ISSUE TITLE
Create a ./deps.sh option to compile using a certain number of threads

### ISSUE THREAD

**Issue by hilnius** [facebook/proxygen#32]
I've had problems compiling proxygen because of the amount of RAM proxygens compilation takes. I've noticed that 8 cc1plus instances were running and as my computer has limited capacity, those instances were just taking up too much RAM for the system resulting in a failed compilation. 

I've solved that problem by increasing my swap.

Specifying how many processes should run at the same time could greatly help in the future though, for all who have limited computers.

**Comment by afrind** [comment]
Thanks for the report, we'll take a look

**Comment by afrind** [comment]
This was actually fixed in fbfd30c559b4160aea10332fd37b6746849aee87
