### ISSUE TITLE
When I use responseBuilder, how can I change http1.1 to http1.0?

### ISSUE THREAD

**Issue by yanke1311** [facebook/proxygen#320]
I am at a situation that need use http1.0, and the lib has been build, so i cannot change source code. how can i change http1.1 to http1.0 when i use responseBuilder? what i only need is http support

**Comment by afrind** [comment]
You currently cannot do this.  Note that if the client sends an HTTP 1.0 request, the server will respond with HTTP/1.0 semantics, even though the message version will be HTTP/1.1.  This advertises to a conservative client that HTTP/1.1 is available.

**Comment by yanke1311** [comment]
Thank you @afrind very much!
