### ISSUE TITLE
from a client perspective， How to connect to HTTPS proxy?

### ISSUE THREAD

**Issue by stevezhou6** [facebook/proxygen#323]
HTTPConnector connect      proxygen::HTTPMethod::CONNECT
AsyncSocket how to convert to AsyncSSLSocket

**Comment by afrind** [comment]
Use `HTTPConnector::connectSSL`

**Comment by afrind** [comment]
Oops, I misunderstood your question.

**Comment by jalopezsilva** [comment]
Are you attempting to send an HTTP CONNECT from the perspective of a client or manage it from the perspective of a proxy?

We have an example of how to handle HTTP CONNECTs on our proxy handler.  https://github.com/facebook/proxygen/blob/master/proxygen/httpserver/samples/proxy/ProxyHandler.cpp#L75

If you're attempting to do it from a client perspective, you can create an AsyncSSLSocket from an already established socket: https://github.com/facebook/folly/blob/master/folly/io/async/AsyncSSLSocket.h#L208-L237

You won't be able to upgrade the transport of an existing upstream session though.

**Comment by stevezhou6** [comment]
yes, i do it from a client perspective。
1. CurlClient  proxygen::HTTPMethod::CONNECT   HTTPConnector::connect
2. CurlClient::connectSuccess  sendRequest 
3. CurlClient::onHeadersComplete   
void CurlClient::onHeadersComplete(unique_ptr<HTTPMessage> msg) noexcept {
    StatusCode:200   StatusMessage:Connection established
   
      initializeSsl();
  folly::AsyncSocket* socket =
      dynamic_cast<folly::AsyncSocket*>(session_->getTransport());
  auto sslSock = new folly::AsyncSSLSocket(
      sslContext_, socket->getEventBase(), socket->getNetworkSocket(), false);
  sslSock->setServerName(getServerName());
  sslSock->forceCacheAddrOnFailure(true);
  sslSock->sslConn(this, 3000ms);
}   

question:
1. HTTPUpstreamSession   holder AsyncSocket   how switch AsyncSSLSocket
2. i dont't get AsyncSSLSocket::HandshakeCB  handshakeSuc or handshakeErr  event.

**Comment by jalopezsilva** [comment]
As I mentioned above, you can't switch the existing transport on an HTTPSession. Your best bet here is to create a custom Connector that will 1) Establish a TCP connection to the proxy, similar to how HTTPConnector works. 2) Send an HTTP CONNECT through the transport 3) Then establish a TLS session similar to how connnectSSL works. 4) Once that connection succeeds, you can create the upstream session.

**Comment by stevezhou6** [comment]
Thank you for your suggestion~
I followed your advice has implemented a feature。
