### ISSUE TITLE
Any reason why setup_fizz() has BUILD_TESTS explicitly turned on?

### ISSUE THREAD

**Issue by triplewy** [facebook/proxygen#325]
In build.sh, all proxygen dependencies support the `$NO_BUILD_TESTS` flag except for fizz, which explicitly has `-DBUILD_TESTS=ON` as part of its cmake. Is there any specific reason for this?

**Comment by lnicco** [comment]
right now proxygen tests have a dependency on a target that is only exported when building Fizz tests. that is the reason

**Comment by triplewy** [comment]
The last step of the build script has `$MAYBE_BUILD_TESTS` for proxygen. So wouldn't setting`$NO_BUILD_TESTS` via the `-t` flag imply that the user does not want to build tests for proxygen as well as for Fizz? Am I missing something here?

**Comment by lnicco** [comment]
no you are right! 
it was probably skipped by mistake. 
I'll send a fix

**Comment by triplewy** [comment]
Thanks!

**Comment by lnicco** [comment]
fixed in https://github.com/facebook/proxygen/commit/3298c325c501f85a85035442e0d776e54fb1a3a5
