### ISSUE TITLE
SocketState check compatibility on VCC

### ISSUE THREAD

**Issue by FatsharkGo** [facebook/proxygen#326]
I'm trying to run unittests of proxygen on Windows, the case `HTTPDownstreamSessionTest.Connect` fails on run out of stack. Afater some digging,
I figure out that the `HTTPSession::readsShutdown` give an unexpected result when called by `HTTPSession::shutdownTransport`, the unexpected behavor due to VCC treats enum as signed int by default, which is explained in this post: [Is it safe to use an enum in a bit field?
](https://stackoverflow.com/questions/11983231/is-it-safe-to-use-an-enum-in-a-bit-field),  the instructions list below,

```asm
   669:   bool readsShutdown() const {
   ...
   670:     return reads_ == SocketState::SHUTDOWN;
000000013F8F8EAE  mov         rax,qword ptr [this]  
000000013F8F8EB3  mov         eax,dword ptr [rax+8B8h]  
000000013F8F8EB9  shl         eax,1Eh  
000000013F8F8EBC  sar         eax,1Eh  
000000013F8F8EBF  cmp         eax,2  
000000013F8F8EC2  jne         proxygen::HTTPSession::readsShutdown+3Dh (013F8F8ECDh)  
000000013F8F8EC4  mov         dword ptr [rsp],1  
000000013F8F8ECB  jmp         proxygen::HTTPSession::readsShutdown+44h (013F8F8ED4h)  
000000013F8F8ECD  mov         dword ptr [rsp],0  
000000013F8F8ED4  movzx       eax,byte ptr [rsp]  
   671:   }
   ...
```

For the comparison, Clang threat enum as unsigned int,

```asm
(lldb) disass
SessionTests`proxygen::HTTPSession::readsShutdown:
    0x10072bd50 <+0>:  pushq  %rbp
    0x10072bd51 <+1>:  movq   %rsp, %rbp
    0x10072bd54 <+4>:  movq   %rdi, -0x8(%rbp)
    0x10072bd58 <+8>:  movq   -0x8(%rbp), %rax
->  0x10072bd5c <+12>: movw   0x868(%rax), %cx
    0x10072bd63 <+19>: andw   $0x3, %cx
    0x10072bd67 <+23>: movzwl %cx, %edx
    0x10072bd6a <+26>: cmpl   $0x2, %edx
    0x10072bd6d <+29>: sete   %sil
    0x10072bd71 <+33>: andb   $0x1, %sil
    0x10072bd75 <+37>: movzbl %sil, %eax
    0x10072bd79 <+41>: popq   %rbp
    0x10072bd7a <+42>: retq
    0x10072bd7b <+43>: nopl   (%rax,%rax)
```

It's easily to fix this by using typed enum,

```C++
enum class SocketState : unsigned int {
  UNPAUSED = 0,
  PAUSED = 1,
  SHUTDOWN = 2,
};
```

It will be greatly appreciated your maintainers fix this for the Windows users of proxygen, thanks!

**Comment by mjoras** [comment]
This is turning out to be more annoying than I expected. GCC is rejecting the `unsigned int`, since when you specify the type it checks if the bitfield is big enough to hold the entire type range.

**Comment by mjoras** [comment]
See https://gcc.gnu.org/bugzilla/show_bug.cgi?id=51242

**Comment by FatsharkGo** [comment]
It's my fault that i forgot there is a compiler called `GCC` in the street corner. LOL

I tried the following code snippet in `GCC4.8.5` which is the most obsolete i can find on my machines, it 
grumbles some warnings and successfully generates the executable, the error mentioned in bug report [51242](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=51242) cannot be reproduced,

```C++
#include <iostream>

struct ebb {
  bool readsShutdown() const {
    return reads_ == SocketState::SHUTDOWN;
  }

  enum class SocketState : unsigned int {
    UNPAUSED = 0,
    PAUSED = 1,
    SHUTDOWN = 2,
  };

  SocketState reads_ : 2;
  SocketState writes_ : 2;
};

int main(int argc, char* argv[]) {
  ebb ebb_;
  ebb_.reads_ = ebb::SocketState::SHUTDOWN;
  auto r = ebb_.readsShutdown();
  std::cout << "We got read: " << r << std::endl;
}
```

```shell
[fatsharkgo@vision trial]$ gcc enumfb.cpp -o enumfb -std=c++11 -lstdc++
enumfb.cpp:14:24: warning: ‘ebb::reads_’ is too small to hold all values of ‘enum class ebb::SocketState’ [enabled by default]
   SocketState reads_ : 2;
                        ^
enumfb.cpp:15:25: warning: ‘ebb::writes_’ is too small to hold all values of ‘enum class ebb::SocketState’ [enabled by default]
   SocketState writes_ : 2;
                         ^
```

Maybe simply add a compiler validation for preprocessor can fix this? Thanks!

**Comment by FatsharkGo** [comment]
I tried the test code snippet in [godbolt](https://godbolt.org/z/zpGsY5) `GCC4.8.2` and `GCC4.8.1`，compilling progress reached the end successfully too, did i miss somthing important?

**Comment by mjoras** [comment]
@FatsharkGo I think I fixed this with f6c360c2c7090d1518ba9f5b7ca1a59ad29efd35, can you verify?

**Comment by mjoras** [comment]
@FatsharkGo for my GCC build there's no way to suppress the warning, and we compile with -Werror, so there's no way to prevent the error, hence the commit above.

**Comment by FatsharkGo** [comment]
I merged the fixing into my local source tree, it works well. Thanks for your great job!
