### ISSUE TITLE
CTests failures on Ubuntu 20.04 MATE

### ISSUE THREAD

**Issue by lexuscrossover** [facebook/proxygen#329]
Hi Guys,

I successfully built proxygen on Unbuntu 20.04 MATE, then I ran the unit tests and observed that these tests failed:

`99% tests passed, 14 tests failed out of 978

Total Test time (real) =  20.78 sec

The following tests FAILED:
	663 - */HTTPSessionAcceptorTestNPN.Npn/* (Failed)
	664 - */HTTPSessionAcceptorTestNPNPlaintext.PlaintextProtocols/* (Failed)
	665 - HTTPSessionAcceptorTestNPNJunk.Npn (Failed)
	666 - HTTPSessionAcceptorTestNPN.AcceptorConfigCapture (Failed)
	942 - SSL.SSLTest (Failed)
	943 - SSL.TestAllowInsecureOnSecureServer (SEGFAULT)
	944 - SSL.DisallowInsecureOnSecureServer (Failed)
	945 - SSL.TestResumptionWithTickets (Failed)
	946 - SSL.TestResumptionAfterUpdateFails (Failed)
	947 - SSL.TestUpdateTLSCredentials (Failed)
	949 - GetListenSocket.TestBootstrapWithNoBinding (Failed)
	950 - GetListenSocket.TestBootstrapWithBinding (Failed)
	957 - ScopedServerTest.StartSSLWithInsecure (Failed)
	958 - ConnectionFilterTest.Test (Failed)
Errors while running CTest
make: *** [Makefile:107: test] Error 8
`
Are these tests known to fail?  or is this a problem with the the particular dependencies I have or bugs in master?

Thank you!

**Comment by lnicco** [comment]
@lexuscrossover thanks for reporting this issue. 
All the tests are healthy on Ubuntu 18.04 which is the distribution we fully support at this time. 
We'll take a look at 20.04 soon but in the meantime these failure don't seem like a blocker to your tests.

Please reopen this issue if the problem becomes blocking for you.
