### ISSUE TITLE
Calling deps.sh twice causes an error.

### ISSUE THREAD

**Issue by gilgil1973** [facebook/proxygen#33]
Hi, thank you for your great product proxygen. Nowadays I am in the middle of reviewing feature of proxygen, and have a question.

No error occurs when I call deps.sh for the first time. But calling twice "deps.sh" causes and error as follows.

"fatal: destination path 'fbthrift' already exists and is not an empty directory.
Cannot rebase: You have unstaged changes.
Please commit or stash them."

I think installing other modules(fbthrift, folly and many other libraries) and building should be separated in shell command line.

Thank you in advance.

**Comment by afrind** [comment]
I removed the dependency on fbthrift (now proxygen depends only on folly) and added the proper shell logic to not clone folly if it appears to be there already.
