### ISSUE TITLE
How to set _build/proxygen/httpserver/hq --mode=server to run in single thread?

### ISSUE THREAD

**Issue by heyitsmine** [facebook/proxygen#330]
I want to do a benchmark on HTTP/3 server, and test its performance on single thread. I noticed hq use CPUThreadPoolExecutor and IOThreadPoolExecutor to run in  multiple threads. So, is there a way to set hq to run in single thread?

**Comment by lnicco** [comment]
right now you'll have to modify the code just a tiny bit.

hardcode this to 1
https://github.com/facebook/proxygen/blob/master/proxygen/httpserver/samples/hq/HQServer.cpp#L203
