### ISSUE TITLE
Installs a file with %%CMAKE_BUILD_TYPE%% in its name

### ISSUE THREAD

**Issue by yurivict** [facebook/proxygen#336]
```
lib/cmake/proxygen/proxygen-config.cmake
lib/cmake/proxygen/proxygen-targets-%%CMAKE_BUILD_TYPE%%.cmake
lib/cmake/proxygen/proxygen-targets.cmake
```

**Comment by yangchi** [comment]
I don't think I understand this issue. Can you elaborate more?

**Comment by yurivict** [comment]
It install the file with the percent (%) symbol in its name.

**Comment by yangchi** [comment]
What's the use case?

**Comment by yurivict** [comment]
cmake package discovery.

**Comment by yangchi** [comment]
I have zero know-how of cmake package discovery. Do you have a link to what it is and how it work?

Also, we don't use cmake inside FB. So if you have a PR to support this we are happy to take it. Otherwise, I don't know if people will have time to actually support this.

**Comment by yurivict** [comment]
https://cmake.org/

**Comment by lnicco** [comment]
@yurivict it works fine for me with 3.17.4 
so that makes me believe this is a CMake bug, which version do you have?
```
...
-- Installing: /home/ubuntu/lnicco/proxygen/proxygen/_build/lib/cmake/proxygen/proxygen-targets.cmake
-- Installing: /home/ubuntu/lnicco/proxygen/proxygen/_build/lib/cmake/proxygen/proxygen-targets-relwithdebinfo.cmake
-- Installing: /home/ubuntu/lnicco/proxygen/proxygen/_build/lib/cmake/proxygen/proxygen-config.cmake
...
```

**Comment by yurivict** [comment]
I use cmake-3.19.2 and experience the problem.

It'll cause failure to locate the ```proxygen``` package if/once somebody would try to do that.

**Comment by alishir** [comment]
@yurivict Yesterday I installed proxygen and I have no problem. My cmake version is 3.18.4.

**Comment by yangchi** [comment]
Closing since we can't repro this one and it's been months. If you still face this problem with latest code, please open a new issue. Thanks.
