### ISSUE TITLE
Performance Testing

### ISSUE THREAD

**Issue by iriszero** [facebook/proxygen#343]
I've been looking for performance (stress) testing code within the repository, but there seems nothing much yet?
Performance testing can be two folds: throughput and the number of concurrent requests.

**Comment by lnicco** [comment]
we have not published any numbers indeed. we'd rather release a loadtest tool with instructions so you can get the actual numbers for your hardware. 
Internally we use a loadtest tool similar to httperf but implemented with proxygen itself so that it supports http1/2/3.
It's on our list of tools to opensource but needs some work still

**Comment by iriszero** [comment]
Thank you for the reply, @lnicco . Can we do a simple test with current code?

I think it's good to start with downloading a big file (e.g., 2GB), as other implementations do and as the `perf` part of [msquic](https://github.com/nibanks/quic-perf/blob/master/draft-banks-quic-performance.md) also describes.

I'm looking for what `nginx` provides, when the server is given:
```
curl {ip}/1234
```
, it will send random (not sure, probably zeroed?) bytes from the server.


My first try goes:
```
in proxygen/proxygen/_build/proxygen/httpserver
➜ ./hq --mode=client -host  {internal_ip} -outdir="{local_path}" -path="/10M.html"
I1113 14:19:45.913280 14770 HQClient.cpp:62] HQClient connecting to {internal_ip}:6666
I1113 14:19:45.918680 14770 CurlClient.cpp:271] Got EOM
```

And at the local path, 10M.html, occupying 78 bytes, says:
```
Invalid URL: cannot extract requested response-length from url path: /10M.html
```

At the server:
```
➜ ./hq --mode=server -host {internal_ip} -static_root {local_path}
I1113 14:18:50.048017 19720 HQServer.cpp:238] HQ server started at: {internal_ip}:6666
E1113 14:19:45.911465 19726 SampleHandlers.h:576] Invalid URL: cannot extract requested response-length from url path: /10M.html
```

`/10M.html` is generated by `dd` command, so not an HTML-formatted file.

In what format should I supply a html (or in other extensions) at the server? Or is there some interface I can easily use?

**Comment by afrind** [comment]
Paths that start with a number trigger the randbytes handler (which generate a random response of that length).  Change your filename to TenMB.html and it should work as you expect, or request /10000000, which will return 10MB worth of random bytes.
