### ISSUE TITLE
HQ client/server with migration seems to not be working

### ISSUE THREAD

**Issue by LucasS98** [facebook/proxygen#345]
When trying to run the tests, they work fine without migration (I run /echo/300 and see 300 characters being sent from the server to client).

Unfortunately, when adding the migration flag, I get an exception on both ends and the connection fails. Reverting to the commit 8477f0799f8d41ea5e3c77156933d704759e826e made the test work. It seems this capability may have been broken in between that commit and today.

Is migration in Proxygen broken, or could it be the Mvfst implementation that is? Or is it just the sample?
Hopefully someone with more insight can help me understand what is going wrong.
Thanks!

**Comment by jbeshay** [comment]
Closing old request. Quic connection migration currently works with the hq cli tool.
