### ISSUE TITLE
configure fails: add_library cannot create imported target "sodium" because another target

### ISSUE THREAD

**Issue by yurivict** [facebook/proxygen#346]
```
CMake Error at build/fbcode_builder/CMake/FindSodium.cmake:257 (add_library):
  add_library cannot create imported target "sodium" because another target
  with the same name already exists.
Call Stack (most recent call first):
  /usr/local/share/cmake/Modules/CMakeFindDependencyMacro.cmake:47 (find_package)
  /usr/local/lib/cmake/fizz/fizz-config.cmake:52 (find_dependency)
  /usr/local/share/cmake/Modules/CMakeFindDependencyMacro.cmake:47 (find_package)
  /usr/local/lib/cmake/mvfst/mvfst-config.cmake:45 (find_dependency)
  CMakeLists.txt:69 (find_package)
```

Version: 2020.11.16.00
OS: FreeBSD 12.2

**Comment by lnicco** [comment]
thanks for reporting. this is a known issue caused by this fizz commit
https://github.com/facebookincubator/fizz/commit/99983646c7c627a24bc42f274aada5d958e248d2
but the fix is probably in mvfst. 

anyway, not sure whether it works out of the box on freebsd, but you can try another build script we have added in the meantime 

`./getdeps.sh`

**Comment by yurivict** [comment]
The FreeBSD port doesn't run ```getdeps.sh```, it just runs cmake.

> but the fix is probably in mvfst.

The same failure occurs with the latest mvfst revision 868d428c873469e3dcf6d041d8023afec3df787b

**Comment by lnicco** [comment]
> The FreeBSD port doesn't run getdeps.sh, it just runs cmake.

I am not sure I get this: getdeps is just a different script the build is still cmake-based. Did you try to run and got an error ? If so could you paste it here ? 


In the meantime, here is a bit of a hack to get the build working again. 
I'll keep looking for a better solution, and will land this if instead I don't find it in a reasonable time.

```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 29f81467..1e4e88a0 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -65,8 +65,11 @@ endif()
 find_package(fmt REQUIRED)
 find_package(folly REQUIRED)
 find_package(wangle REQUIRED)
-find_package(Fizz REQUIRED)
-find_package(mvfst QUIET)
+if (BUILD_QUIC)
+  find_package(mvfst REQUIRED)
+else()
+ find_package(Fizz REQUIRED)
+endif()
 find_package(Zstd REQUIRED)
 find_package(ZLIB REQUIRED)
 find_package(OpenSSL REQUIRED)
```

**Comment by yurivict** [comment]
This patch helped, thanks!

----------

> I am not sure I get this: getdeps is just a different script the build is still cmake-based. Did you try to run and got an error ?

The ports framework normally runs 'cmake . && gmake'. We try to avoid running custom scripts.

**Comment by lnicco** [comment]
> The ports framework normally runs 'cmake . && gmake'. We try to avoid running custom scripts. 

ah got it. makes sense. thanks for explaining
