### ISSUE TITLE
QUIC support building errors

### ISSUE THREAD

**Issue by alexliyu7352** [facebook/proxygen#348]
It seems the mvfst version is not fit this project.
1. The transportInfo of HQSessionTestCommon.h missing:
        .totalPacketsSent = 0,
        .totalPacketsMarkedLost = 0,
        .totalPacketsMarkedLostByPto = 0,
        .totalPacketsMarkedLostByReorderingThreshold = 0,
2. After add these codes, the build finished, but run hq will shows Signal 6 (SIGABRT) (0x3e800003a01) received by PID 14849 (pthread TID 0x7f1648628500) (linux TID 14849) (maybe from PID 14849, UID 1000) (code: -6), stack trace: ***

**Comment by yangchi** [comment]
For (1), do you mean this thing? https://github.com/facebook/proxygen/blob/master/proxygen/lib/http/session/test/HQSessionTestCommon.h#L170

Does that even matter if those fields aren't initialized there?

For (2), can you paste the stack trace?

**Comment by lnicco** [comment]
1) yes with certain compilers/configurations it does matter. working on a fix

2) +1 for getting both the stack trace and the repro commands

**Comment by lnicco** [comment]
the build error was addressed in https://github.com/facebook/proxygen/commit/9dacc93ab5dec2163e1d598bbe9e5929cc0f294c 

please rebase
