### ISSUE TITLE
Building succeed ,but testing failed !

### ISSUE THREAD

**Issue by triump2020** [facebook/proxygen#349]
Here is the error message :

`1030/1031 Test #1030: CompressionFilterTest/*.CompressionDisabledForEncoding ..................   Passed    0.01 sec
          Start 1031: CompressionFilterTest/*.NoResponseBody
1031/1031 Test #1031: CompressionFilterTest/*.NoResponseBody ..................................   Passed    0.01 sec

99% tests passed, 10 tests failed out of 1031

Total Test time (real) =  27.44 sec

**The following tests FAILED:**
        994 - SSL.SSLTest (Failed)
        995 - SSL.TestAllowInsecureOnSecureServer (SEGFAULT)
        996 - SSL.DisallowInsecureOnSecureServer (Failed)
        997 - SSL.TestResumptionWithTickets (Failed)
        998 - SSL.TestResumptionAfterUpdateFails (Failed)
        999 - SSL.TestUpdateTLSCredentials (Failed)
        1001 - GetListenSocket.TestBootstrapWithNoBinding (Failed)
        1002 - GetListenSocket.TestBootstrapWithBinding (Failed)
        1009 - ScopedServerTest.StartSSLWithInsecure (Failed)
        1010 - ConnectionFilterTest.Test (Failed)
Errors while running CTest
make: *** [Makefile:118: test] Error 8`

**Comment by chriselving** [comment]
Newer versions of OpenSSL no longer accept SHA-1 certs, but the proxygen/httpserver/tests/certs test certs use SHA-1. Until someone regenerates the certs, you can work around the problem by changing your /etc/ssl/openssl.cnf CipherString directive to "CipherString = DEFAULT:@SECLEVEL=1".

**Comment by nsapi** [comment]
This was eventually fixed as issue #404.
