### ISSUE TITLE
how to visit httpserver/ hq in chrome?

### ISSUE THREAD

**Issue by jialianchen** [facebook/proxygen#353]
I want to visit httpserver/ hq in chrome,but i failed.
I run "_build/proxygen/httpserver/hq --mode=server -h2port=11000 ",but i can't visit ”http://localhost:11000/“ in chrome.(my chrome supports quic).
I can easily use "_build/proxygen/httpserver/proxygen_echo"and visit it in chrome.
I wonde how to visit hq in chrome.
Thanks very much.

**Comment by lnicco** [comment]
(mirrored from the google group)

two recommendations that should make this work:
* looks like the alt-svc header is added conditionally, only if the --protocol flag is used to start the server. 
* the alt-svc header includes the port number, so it is necessary to run the http2 and http3 servers on the same port for alt-svc to work

```
# start the server
hq --mode=server --port=8080 --h2port=8080 --protocol=h3-27
# check that alt-svc header is added to the response
curl -v -k https://localhost:8080
< HTTP/2 200
< x-echo-host: localhost:8080
< x-echo-user-agent: curl/7.64.1
< x-echo-accept: */*
< alt-svc: h3-27=":8080"; ma=3600
< date: Thu, 11 Feb 2021 17:32:02 UTC

```
after checking this you can point Chrome to https://localhost:8080

**Comment by jialianchen** [comment]
Thanks for your help!
Then I use 
`hq --mode=server --port=8080 --h2port=8080 --protocol=h3-27`
and

`curl -v -k  https://localhost:8080`
I get 


```
*   Trying ::1:8080...
* Connected to localhost (::1) port 8080 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /usr/local/etc/openssl@1.1/cert.pem
*  CApath: /usr/local/etc/openssl@1.1/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
```
I wonder why i didn`t get the same output as you.
(I wonder whether i should change some codes.)

**Comment by jialianchen** [comment]
I learned from the group that I should add cert...
But  I use 
```
_build/proxygen/httpserver/hq --mode=server --port=8080 --h2port=8080 --protocol=h3-27 --key=mypath/server.key --cert=mypath/server.crt
```
I still can`t get the same output, I still get 
```
*   Trying ::1:8080...
* Connected to localhost (::1) port 8080 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /usr/local/etc/openssl@1.1/cert.pem
*  CApath: /usr/local/etc/openssl@1.1/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
```
It seems that the server still can't handshake....
I don't know why and could you told me some way i can try.

**Comment by lnicco** [comment]
hard to say from this log alone. 
can you run the `hq` server with `--v=5` and post the logs you get when trying to connect? 
Also, to increase the info from curl you can try to add `--trace-time` and `--trace-ascii`

**Comment by jialianchen** [comment]
In the past i use ssh port forwarding from linux ,i get 
```
*   Trying ::1:8080...
* Connected to localhost (::1) port 8080 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /usr/local/etc/openssl@1.1/cert.pem
*  CApath: /usr/local/etc/openssl@1.1/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
```
in the linux itself ,i get 
```
*   Trying 127.0.0.1:8080...
* TCP_NODELAY set
* connect to 127.0.0.1 port 8080 failed: Connection refused
* Failed to connect to localhost port 8080: Connection refused
* Closing connection 0
curl: (7) Failed to connect to localhost port 8080: Connection refused
```
it seems that the curl can't connection.
I use 
```
curl -v -k  --http2  https://localhost:8080
```
get the same output(Connection refused).
（curl don't support http2 default，but it seems not the reason ）
I use `hq` server with `--v=5`,
i found the server don't find the client is trying to connect it ,
the server always
```
I0223 10:04:28.730891 459076 SSLContextManager.cpp:541] For vip vip_, setting sid_ctx Proxygen
I0223 10:04:28.730919 459076 TLSTicketKeyManager.cpp:288] Adding key for 1 type=1 Name=276e4bc2
I0223 10:04:28.730934 459076 SSLContextManager.cpp:548] On VipID=[::1]:8080 context=0x7f97480d8f20
I0223 10:04:28.730962 459076 SSLContextManager.cpp:903] Adding SSLContext with best available crypto
I0223 10:04:28.730978 459076 SSLContextManager.cpp:951] Adding CN/Subject-alternative-name "Proxygen" for SNI search
I0223 10:04:28.743623 459101 EventBase.cpp:317] EventBase(): Starting loop.
I0223 10:04:28.745154 459076 EventBase.cpp:317] EventBase(): Starting loop.
```

**Comment by afrind** [comment]
Closing this old issue, please open a new one if you need assistance.
