### ISSUE TITLE
HTTP/2 how to use ./proxygen_echo

### ISSUE THREAD

**Issue by Shawn314** [facebook/proxygen#354]
1. I used curl, command is "curl --http2 -v http://localhost:11002/", got below err msg .
![image](https://user-images.githubusercontent.com/30689370/111150770-7737d300-85c9-11eb-9a14-69e9ec30fb26.png)
2. I used curl, command is "curl --http2-prior-knowledge -v http://localhost:11002/", got nothing .
![image](https://user-images.githubusercontent.com/30689370/111150820-8880df80-85c9-11eb-814f-1a5e27a36352.png)
3. I used ./proxygen_curl, command is "./proxygen_curl --http_method=GET --url="http://localhost:11002" --h2c", got err msg .
![image](https://user-images.githubusercontent.com/30689370/111150949-b82fe780-85c9-11eb-9e95-44ce7fa4b416.png)

so, how to test HTTP/2? any suggestions for me?

**Comment by jdryan** [comment]
To debug a bit on your own, try running the server with higher log level: `--v=4`

In this case there's an extra message beforehand:
> HTTP2Codec.cpp:81] missing connection preface

And a packet hexdump after.

The connection preface that's missing is the h2 one called out in the rfc https://tools.ietf.org/html/rfc7540#section-3.5.

This means we're sending something other than h2 traffic to the server: the h1 negotiation to use h2. The echo server doesn't handle this

You are on the right track with both `curl --http2` and `curl --http2-prior-knowledge`, but the first one sends an h1 negotiation beforehand and the second one doesn't actually send h2.

Try combining the two to both send h2 and skip the negotation.

`curl --http2 --http2-prior-knowledge http://localhost:11002`

**Comment by Shawn314** [comment]
Thank you for your reply jdryan. I success test with this commnad "curl --http2 --http2-prior-knowledge http://localhost:11002" or "curl --http2-prior-knowledge http://localhost:11002"
Also I want to know that how to simulate negotation and how to HTTP/1.1 upgrade HTTP2. 
![image](https://user-images.githubusercontent.com/30689370/111254499-2e772d00-8650-11eb-96f1-8308bcc3d58c.png)
So I have two problem from this pic. 
1) This Request is HTTP/1.1, and curl request port is 11000. Header involve that Connection: Upgrade, HTTP2-Settings, but server response is 200. Both is HTTP/1.1. I don't get 101 that switch protocol.  how to get it?
2) If I get 101 response code, how to simulate continuous transmit data using http/2. which port I will use, 11000 or 11002?

Looking forward your reply.

**Comment by jdryan** [comment]
Sorry, the existing echo server doesn't support connection upgrades, it just echos back what you send it. You'd have to extend the echo handler with some header validation and something like `ResponseBuilder(...).acceptUpgradeRequest(...);`

**Comment by Shawn314** [comment]
Understand， Very grateful to your reply. Please close this.
