### ISSUE TITLE
Build Issues

### ISSUE THREAD

**Issue by naveen24691** [facebook/proxygen#36]
Hi,
   When I was trying to build the proxygen, I got the "fbthrift +folly Build failed" error.
   After digging into it, I found out that proxygen is building the older version of fbthrift and also fbthrift is trying to build older version of folly. So I cloned the latest fbthrift/folly and build it separately and commented out the fbthrift /folly build script in "proxygen/deps.sh". Now it worked !

Can we set the proxygen to use the latest fbthrift/folly rather than the older versions? (same goes for fbthrift)

**Comment by bugok** [comment]
Hello @naveen24691,
Thank you for reporting this. I'll get on it.
Noam.

**Comment by bugok** [comment]
@naveen24691 I just pushed a new version that should fix this.
Please let us know if you continue to see errors.
