### ISSUE TITLE
2021.05.10.00 fails: error: /usr/local/lib/libfolly.so.0.58.0-dev: undefined reference to typeinfo for snappy::Source

### ISSUE THREAD

**Issue by yurivict** [facebook/proxygen#361]
Log: https://people.freebsd.org/~yuri/proxygen-2021.05.10.00.log

OS: FreeBSD 12.2
snappy-1.1.9 (folly depends on it)

**Comment by linkensphere201** [comment]
I had this problem too, but it only failed to build those sample executables(proxygen_[push/echo/static/etc...]). my nasty solution is to comment out those targets.

**Comment by linkensphere201** [comment]
@yurivict  you can run this `make VERBOSE=1` to check which instruction goes wrong. For me, I've found CMAKE_LIBRARY_PATH is not set correctly.

**Comment by yurivict** [comment]
Log: https://people.freebsd.org/~yuri/proxygen-2021.05.17.00.log

**Comment by linkensphere201** [comment]
> Log: https://people.freebsd.org/~yuri/proxygen-2021.05.17.00.log

@yurivict Maybe you need to rebuild snappy and turn on `-frtti` (e.g. need to modify CMakeLists.txt). By default, snappy turn off this feature in it's CMakeLists.txt by adding something like `-fno-rtti`.

**Comment by yurivict** [comment]
```folly``` is a culprit: https://github.com/facebook/folly/issues/1606

**Comment by yurivict** [comment]
@linkensphere201 Do you know how to ask snappy to not disable RTTI info?

Issues are disabled there for some reason.

**Comment by linkensphere201** [comment]
need to modify CMakeLists.txt  add something like `-frtti`. check this line: https://github.com/google/snappy/blob/master/CMakeLists.txt#L80

**Comment by yurivict** [comment]
This is what has been done to fix this problem. Thanks!
