### ISSUE TITLE
Make fails gen_HTTPCommonHeaders.cpp.sh: command not found

### ISSUE THREAD

**Issue by aajtodd** [facebook/proxygen#38]
Clean checkout of proxygen (72622b8) fails to build.

Checked out the latest proxygen and was unable to build it.

Ran `./deps.sh` which makes its way to this error:
```
Making all in services
make[3]: Entering directory `/home/ajt/libs/proxygen/proxygen/lib/services'
Making all in .
make[4]: Entering directory `/home/ajt/libs/proxygen/proxygen/lib/services'
make[4]: Nothing to be done for `all-am'.
make[4]: Leaving directory `/home/ajt/libs/proxygen/proxygen/lib/services'
make[3]: Leaving directory `/home/ajt/libs/proxygen/proxygen/lib/services'
Making all in http
make[3]: Entering directory `/home/ajt/libs/proxygen/proxygen/lib/http'
FBCODE_DIR=../../.. INSTALL_DIR=. HEADERS_LIST=./HTTPCommonHeaders.txt gen_HTTPCommonHeaders.cpp.sh
/bin/bash: gen_HTTPCommonHeaders.cpp.sh: command not found
make[3]: *** [HTTPCommonHeaders.cpp] Error 127
make[3]: Leaving directory `/home/ajt/libs/proxygen/proxygen/lib/http'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/home/ajt/libs/proxygen/proxygen/lib'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/ajt/libs/proxygen/proxygen'
make: *** [all] Error 2
```

I drilled down to the specific makefile and tried to run it independently:
```
ajt@xps15:~/libs/proxygen/proxygen$ cd lib/http/
ajt@xps15:~/libs/proxygen/proxygen/lib/http$ make
FBCODE_DIR=../../.. INSTALL_DIR=. HEADERS_LIST=./HTTPCommonHeaders.txt gen_HTTPCommonHeaders.cpp.sh
/bin/bash: gen_HTTPCommonHeaders.cpp.sh: command not found
make: *** [HTTPCommonHeaders.cpp] Error 127
```

Even modified the path to include that directory but the sed command in the script fails as well, which is where I gave up (not a sed or makefile expert and was really just going to play around with proxygen).

```
ajt@xps15:~/libs/proxygen/proxygen/lib/http$ export PATH=$PATH:$(pwd)
ajt@xps15:~/libs/proxygen/proxygen/lib/http$ make
FBCODE_DIR=../../.. INSTALL_DIR=. HEADERS_LIST=./HTTPCommonHeaders.txt gen_HTTPCommonHeaders.cpp.sh
sed: -e expression #1, char 10: unterminated `s' command
(standard input): The input file is empty!
make: *** [HTTPCommonHeaders.cpp] Error 1
```

I had built proxygen a few months ago with no difficulty, looks like the build process related to this may have changed recently in this commit:
12b0212de40557fd1a5b8f0b845ebc1b7930d385

Built on:
Ubuntu 14.04
g++ 4.8.2

Let me know if you need anything else if it is in fact an issue.

-Aaron

**Comment by jwatzman** [comment]
The `sed` failure has something to do with newline escaping, and `bash` vs `dash`. If you change `lib/http/gen_HTTPCommonHeaders.cpp.sh` to start with `#!/bin/bash` the problem goes away.

**Comment by aajtodd** [comment]
It crossed my mind yesterday that could  be the issue. Confirmed that fixes it for me.

An aside comment/observation. The switch to sed to get rid of ruby is fine but it's one more thing to consider for cross platform compatibility someday. I realize proxygen does not support windows at the moment but it's not outside the realm of possibility it might one day, especially once folly runs on Windows.

**Comment by planetbeing** [comment]
I experienced similar issue building for Mac. Makefile.am proxygen/lib/http/Makefile.am needs to refer to "./gen_HTTPCommonHeaders.h.sh" and "./gen_HTTPCommonHeaders.cpp.sh" instead of "gen_HTTPCommonHeaders.h.sh" and "gen_HTTPCommonHeaders.cpp.sh".

The shell in those scripts used should be /bin/bash and not /bin/sh, or newline escaping has issues on Mac as well.

Finally, on Mac, the BSD sed doesn't work properly. gsed installed via Homebrew can be substituted.

It might honestly be easier to depend on ruby or python here since the shell and sed are so variable across platforms.

**Comment by aajtodd** [comment]
Right, still leaves the path issue "./gen_HTTPCommonHeaders.X.sh".

FYI the sed script looks like it also dumped out the same enum value for every header name, I didn't look any further into that.

I must be bored...took a stab substituting the sed scripts for python over at https://github.com/aajtodd/proxygen/commit/af88827a572c1dcded5d3fa19052d2889bcb30bc

Script is little rough still since I wasn't exactly sure what all the requirements on the script are other than:
* Substitute the HTTPCommonHeaders.txt into the templates
* Generate the cpp file with gperf

Reversed the logic from the old ruby script and the current output files.

Header file and cpp files match mostly. The only differences are enum order on a few and gperf added lots of compiler directives similar to `#line 92 "HTTPCommonHeaders.gperf"` in the generated HTTPCommonHeaders.cpp file.

Test suite passed.

Unrelated also fixed `reinstall.sh` since fbthrift was removed.

If I had more info I could make a better script, otherwise I'm going to call it a day and leave it to the team to address.

**Comment by viswanathgs** [comment]
Thanks for reporting this, I wish we had caught this before we pushed it. This is fixed now.
