### ISSUE TITLE
Proxygen HTTP server example with fizz

### ISSUE THREAD

**Issue by ss7pro** [facebook/proxygen#388]
Folks,

Do you have HTTPS server example implemented with fizz?

**Comment by afrind** [comment]
I think fizz is enabled by default for TLS 1.3 connections if you configure SSL/TLS.  There are a couple examples in proxygen/httpserver/test/HTTPServerTest.cpp that set an SSLContextConfig.

**Comment by ss7pro** [comment]
Are yo sure? When I'm looking at HQ server I have a different feeling: https://github.com/facebook/proxygen/blob/main/proxygen/httpserver/samples/hq/HQServer.cpp

**Comment by lnicco** [comment]
@ss7pro what's your feeling? 

hqserver definitely uses fizz

**Comment by ss7pro** [comment]
HQ is using fizz 100%. Examplex from HTTPServerTest just use folly AsyncSSL implementation which uses openssl/boringssl.
