### ISSUE TITLE
Testsuite for proxygen 19.0 fails

### ISSUE THREAD

**Issue by andor72** [facebook/proxygen#39]
Fresh checkout of proxygen 19.0 fails during testsuite

make[8]: Entering directory '/proxygen/proxygen/lib/http/codec/test'
*** Error in `/proxygen/proxygen/lib/http/codec/test/.libs/lt-CodecTests': free(): invalid size: 0x0000000001a46f50 ***
../../../../build-aux/test-driver: line 107: 15806 Aborted                 (core dumped) "$@" > $log_file 2>&1
FAIL: CodecTests
make[9]: Entering directory '/proxygen/proxygen/lib/http/codec/test'
Making all in .
make[10]: Entering directory '/proxygen/proxygen/lib/http/codec/test'
make[10]: Nothing to be done for 'all-am'.
make[10]: Leaving directory '/proxygen/proxygen/lib/http/codec/test'
make[9]: Leaving directory '/proxygen/proxygen/lib/http/codec/test'
============================================================================
Testsuite summary for proxygen 19.0
============================================================================
# TOTAL: 1
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
============================================================================
See lib/http/codec/test/test-suite.log
============================================================================
Makefile:806: recipe for target 'test-suite.log' failed
make[8]: *** [test-suite.log] Error 1
make[8]: Leaving directory '/proxygen/proxygen/lib/http/codec/test'
Makefile:912: recipe for target 'check-TESTS' failed
make[7]: *** [check-TESTS] Error 2
make[7]: Leaving directory '/proxygen/proxygen/lib/http/codec/test'
Makefile:1010: recipe for target 'check-am' failed
make[6]: *** [check-am] Error 2
make[6]: Leaving directory '/proxygen/proxygen/lib/http/codec/test'
Makefile:699: recipe for target 'check-recursive' failed
make[5]: *** [check-recursive] Error 1
make[5]: Leaving directory '/proxygen/proxygen/lib/http/codec/test'
Makefile:351: recipe for target 'check-recursive' failed
make[4]: *** [check-recursive] Error 1
make[4]: Leaving directory '/proxygen/proxygen/lib/http/codec'
Makefile:865: recipe for target 'check-recursive' failed
make[3]: *** [check-recursive] Error 1
make[3]: Leaving directory '/proxygen/proxygen/lib/http'
Makefile:1014: recipe for target 'check' failed
make[2]: *** [check] Error 2
make[2]: Leaving directory '/proxygen/proxygen/lib/http'
Makefile:499: recipe for target 'check-recursive' failed
make[1]: *** [check-recursive] Error 1
make[1]: Leaving directory '/proxygen/proxygen/lib'
Makefile:404: recipe for target 'check-recursive' failed
make: *** [check-recursive] Error 1

lib/http/codec/test/test-suite.log:
=======================================================
   proxygen 19.0: lib/http/codec/test/test-suite.log
=======================================================

# TOTAL: 1
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: CodecTests
================

[==========] Running 51 tests from 5 test cases.
[----------] Global test environment set-up.
[----------] 2 tests from DefaultFlowControl
[ RUN      ] DefaultFlowControl.flow_control_construct

[WARNING] gmock-1.6.0/gtest/src/gtest-death-test.cc:789:: Death tests use fork(), which is unsafe particularly in a threaded context. For this test, Google Test couldn't detect the number of threads.
[       OK ] DefaultFlowControl.flow_control_construct (177 ms)
[ RUN      ] DefaultFlowControl.send_update
[       OK ] DefaultFlowControl.send_update (0 ms)
[----------] 2 tests from DefaultFlowControl (177 ms total)

[----------] 2 tests from BigWindow
[ RUN      ] BigWindow.recv_too_much
[       OK ] BigWindow.recv_too_much (7 ms)
[ RUN      ] BigWindow.remote_increase
[       OK ] BigWindow.remote_increase (1 ms)
[----------] 2 tests from BigWindow (8 ms total)

[----------] 3 tests from HTTPChecksTest
[ RUN      ] HTTPChecksTest.send_trace_body_death

[WARNING] gmock-1.6.0/gtest/src/gtest-death-test.cc:789:: Death tests use fork(), which is unsafe particularly in a threaded context. For this test, Google Test couldn't detect the number of threads.
*** Aborted at 1428583805 (unix time) try "date -d @1428583805" if you are using GNU date ***
PC: @     0x7f60c715bd27 (unknown)
*** SIGABRT (@0x3e800003dbe) received by PID 15806 (TID 0x7f60c8ae4840) from PID 15806; stack trace: ***
    @     0x7f60c82abc90 (unknown)
    @     0x7f60c715bd27 (unknown)
    @     0x7f60c715d418 (unknown)
    @     0x7f60c719d9f4 (unknown)
    @     0x7f60c71a5006 (unknown)
    @           0x48b4b3 proxygen::HTTPHeaders::disposeOfHeaderNames()
    @           0x48b564 proxygen::HTTPHeaders::~HTTPHeaders()
    @           0x4903a4 proxygen::HTTPMessage::~HTTPMessage()
    @           0x40eca1 HTTPChecksTest_send_trace_body_death_Test::TestBody()
    @           0x4ef543 testing::internal::HandleExceptionsInMethodIfSupported<>()
    @           0x4e7f0a testing::Test::Run()
    @           0x4e8058 testing::TestInfo::Run()
    @           0x4e8135 testing::TestCase::Run()
    @           0x4e8438 testing::internal::UnitTestImpl::RunAllTests()
    @           0x4e8707 testing::UnitTest::Run()
    @           0x40e3b1 main
    @     0x7f60c7146ec5 (unknown)
    @           0x40e869 (unknown)
    @                0x0 (unknown)

reinstall then fails with:
./reinstall.sh: line 15: cd: fbthrift/thrift/folly/folly: No such file or directory

System:
------------------------------------------------------------
Ubuntu 14.10
gcc (Ubuntu 4.9.1-16ubuntu6) 4.9.1
Linux MacBookPro 3.16.0-24-generic #32-Ubuntu SMP Tue Oct 28 13:07:32 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

**Comment by viswanathgs** [comment]
I just pushed some build fixes that appears to fix the test as well. Could you rebase and confirm if the tests pass? Either way, the reinstall.sh problem is fixed for sure now.

**Comment by viswanathgs** [comment]
Oh, and thanks for reporting this!

**Comment by afrind** [comment]
Pretty sure this is fixed so closing for now.  Please reopen if it's still broken for you.
