### ISSUE TITLE
Do we have a plan to support webTransport?

### ISSUE THREAD

**Issue by xujiasci** [facebook/proxygen#392]
https://datatracker.ietf.org/doc/html/draft-ietf-webtrans-http3-02.txt

**Comment by afrind** [comment]
Yes, we are involved in the specification process and will have an implementation.  The timeline is a bit TBD right now.

**Comment by unicomp21** [comment]
Any updates here?  Chrome just released webtransport recently, right?

**Comment by RavikumarTulugu** [comment]
Hi, 
any update on this ?? we are planning to use proxygen for our backend.

**Comment by afrind** [comment]
Thanks for your patience here.  We did some work at the IETF hackathon in November and were able to demonstrate webtransport interop with Chrome and a proxygen based server.  The bad news is the diffs are pretty hacky and we're struggling to find the time to prioritize polishing them.  We're hoping to find some cycles in Q2.  Would any community members be willing to help in the meantime?  We can definitely provide the starter diffs, direction and code review.

**Comment by hhrsscc** [comment]
> 

Great! How to join?

**Comment by afrind** [comment]
@hhrsscc : Send me an email afrind @ meta

**Comment by afrind** [comment]
WebTransport support has landed in proxygen.  The generic WebTransport API is here: 

https://github.com/facebook/proxygen/blob/main/proxygen/lib/http/webtransport/WebTransport.h

And hq supports the devious-baton sample:

https://github.com/facebook/proxygen/blob/main/proxygen/httpserver/samples/hq/SampleHandlers.cpp#L297

The API is new so feedback is welcome.
