### ISSUE TITLE
Proxygen using single thread for all requests

### ISSUE THREAD

**Issue by ss7pro** [facebook/proxygen#393]
Folks,

I'm looking through the code and found this one:

https://github.com/facebook/proxygen/blob/main/proxygen/httpserver/HTTPServer.h#L191

Do you happen to have HTTPServer implementation where you don't start a new thread for every new connection. Similar to what nginx does?

Tomasz

**Comment by ss7pro** [comment]
I found this one: QueuedImmediateExecutor: https://github.com/facebook/folly/blob/main/folly/executors/QueuedImmediateExecutor.cpp.

Do you think it should work well with proxygen HTTP server?

**Comment by afrind** [comment]
The HTTPServer doesn't start a thread per connection.  The number of IO threads is configurable here: https://github.com/facebook/proxygen/blob/main/proxygen/httpserver/HTTPServerOptions.h#L49.

It uses epoll to handle multiple connections in a single thread much like nginx.
