### ISSUE TITLE
build issue 

### ISSUE THREAD

**Issue by olcydvt** [facebook/proxygen#395]
Hi,

When I tried to run build.sh on ubuntu 20.04 I got this error. I installed all dependencies.
It seems that there is conflict on function signature manner. But it is a core thing so I can not fix it
 Could you please check this?

[  2%] Building CXX object CMakeFiles/folly_base.dir/folly/io/async/AsyncTimeout.cpp.o
/opt/mega/proxygen/proxygen/_**build/deps/folly/folly/init/Init.cpp: **In function 'void folly::init(int*, char***, folly::InitOptions)':
/opt/mega/proxygen/proxygen/_build/deps/folly/folly/init/Init.cpp:79:34: error: invalid conversion from 'void (*)() noexcept' to 'google::logging_fail_func_t' {aka 'void (*)() __attribute__((noreturn))'} [-fpermissive]
   79 |   google::InstallFailureFunction(abort);
      |                                  ^~~~~
      |                                  |
      |                                  void (*)() noexcept
In file included from /opt/mega/proxygen/proxygen/_build/deps/folly/folly/init/Init.cpp:19:**
/usr/local/include/glog/logging.h:637:70: note:   initializing argument 1 of 'void google::InstallFailureFunction(google::logging_fail_func_t)'
  637 | GOOGLE_GLOG_DLL_DECL void InstallFailureFunction(logging_fail_func_t fail_func);
      |                                                  ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~**
make[2]: *** [CMakeFiles/folly_base.dir/build.make:1961: CMakeFiles/folly_base.dir/folly/init/Init.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:197: CMakeFiles/folly_base.dir/all] Error 2

**Comment by afrind** [comment]
Sorry for not responding in a timely way.  Please give it another try if it's still a problem and reopen.
