### ISSUE TITLE
Does that proxygen's dependency is wrong? depends mvfst?

### ISSUE THREAD

**Issue by jiayuehua** [facebook/proxygen#396]
https://github.com/microsoft/vcpkg/pull/22834/files
I can compile proxygen successfully without mvfst. Thanks.

**Comment by jbeshay** [comment]
The mvfst dependency is there for building with QUIC/HTTP3 support. It would be used here: https://github.com/facebook/proxygen/blob/acc779bede18306a02d37dd7099b56b250b0dc0a/CMakeLists.txt#L72

**Comment by jiayuehua** [comment]
thanks
