### ISSUE TITLE
Build is successful, but tests failed!

### ISSUE THREAD

**Issue by MohammadArik** [facebook/proxygen#404]
``Hi,
I was installing proxygen in my machine... The build process was error-free and successful. But when I tried to test in the ``_build`` directory I got some tests were failed. Can anyone help me out here? 

The log is this...
```
99% tests passed, 11 tests failed out of 1066

Total Test time (real) =  31.16 sec

The following tests FAILED:
        1028 - SSL.SSLTest (Failed)
        1029 - SSL.SSLTestWithMultiCAs (Failed)
        1030 - SSL.TestAllowInsecureOnSecureServer (SEGFAULT)
        1031 - SSL.DisallowInsecureOnSecureServer (Failed)
        1032 - SSL.TestResumptionWithTickets (Failed)
        1033 - SSL.TestResumptionAfterUpdateFails (Failed)
        1034 - SSL.TestUpdateTLSCredentials (Failed)
        1036 - GetListenSocket.TestBootstrapWithNoBinding (Failed)
        1037 - GetListenSocket.TestBootstrapWithBinding (Failed)
        1044 - ScopedServerTest.StartSSLWithInsecure (Failed)
        1045 - ConnectionFilterTest.Test (Failed)
Errors while running CTest
Output from these tests are in: /home/mohammadarik/proxygen/proxygen/_build/Testing/Temporary/LastTest.log
Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.
make: *** [Makefile:71: test] Error 8
```

**Comment by lnicco** [comment]
thanks for reporting, is this on macOS or Linux ?

**Comment by MohammadArik** [comment]
@lnicco it's Linux...

**Comment by EverydayDiesel** [comment]
fedora 36 (linux) here 


99% tests passed, 11 tests failed out of 1057

Total Test time (real) =  33.69 sec

The following tests FAILED:
	1019 - SSL.SSLTest (Failed)
	1020 - SSL.SSLTestWithMultiCAs (Failed)
	1021 - SSL.TestAllowInsecureOnSecureServer (SEGFAULT)
	1022 - SSL.DisallowInsecureOnSecureServer (Failed)
	1023 - SSL.TestResumptionWithTickets (Failed)
	1024 - SSL.TestResumptionAfterUpdateFails (Failed)
	1025 - SSL.TestUpdateTLSCredentials (SEGFAULT)
	1027 - GetListenSocket.TestBootstrapWithNoBinding (Failed)
	1028 - GetListenSocket.TestBootstrapWithBinding (Failed)
	1035 - ScopedServerTest.StartSSLWithInsecure (Failed)
	1036 - ConnectionFilterTest.Test (Failed)

**Comment by lnicco** [comment]
@MohammadArik @EverydayDiesel 
I am unfortunately unable to reproduce on Ubuntu 18.04. 
Could you please run one of the failing tests manually and paste the logs here ?

The following one should do
```
_build/proxygen/httpserver/tests/HTTPServerTests
```

**Comment by lnicco** [comment]
ha! I managed to reproduce this on a mac. 
This seems to depend on the openssl version installed. On the mac I have `OpenSSL 3.0.5` which version do you have on your system?

```
[  FAILED  ] SSL.SSLTestWithMultiCAs (2 ms)
[ RUN      ] SSL.TestAllowInsecureOnSecureServer
E20220831 13:57:18.657270 7053557 SSLContextManager.cpp:713] error loading SSL certificate /Users/lniccolini/github/proxygen/proxygen/httpserver/tests/certs/test_cert1.pem: std::runtime_error: SSL_CTX_use_certificate_chain_file: /Users/lniccolini/github/proxygen/proxygen/httpserver/tests/certs/test_cert1.pem: ca md too weak
/Users/lniccolini/github/proxygen/proxygen/httpserver/tests/HTTPServerTest.cpp:450: Failure
Value of: st->start()
  Actual: false
Expected: true
*** Aborted at 1661979438 (unix time) try "date -d @1661979438" if you are using GNU date ***
PC: @                0x0 folly::AtFork::init_
*** SIGSEGV (@0x88) received by PID 57355 (TID 0x10331c580) stack trace: ***
    @        0x191b3f4a4 _sigtramp
    @        0x102576f0c SSL_TestAllowInsecureOnSecureServer_Test::TestBody()
    @        0x102576f0c SSL_TestAllowInsecureOnSecureServer_Test::TestBody()
    @        0x102720a60 testing::internal::HandleExceptionsInMethodIfSupported<>()
    @        0x1027209ac testing::Test::Run()
    @        0x102721cac testing::TestInfo::Run()
    @        0x102722790 testing::TestSuite::Run()
    @        0x1027333b4 testing::internal::UnitTestImpl::RunAllTests()
    @        0x102732950 testing::internal::HandleExceptionsInMethodIfSupported<>()
    @        0x1027328b8 testing::UnitTest::Run()
    @        0x1026ff1d8 main
[1]    57355 segmentation fault  _build/proxygen/httpserver/tests/HTTPServerTests
```

**Comment by lnicco** [comment]
by the way, this just means we need to regenerate the test certs to be stronger

**Comment by EverydayDiesel** [comment]
Thanks for the reply.  I am using version 
$ openssl version
OpenSSL 3.0.5 5 Jul 2022 (Library: OpenSSL 3.0.5 5 Jul 2022)



[  FAILED  ] SSL.SSLTest (4 ms)
[----------] 1 test from SSL (4 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (4 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] SSL.SSLTest

 1 FAILED TEST
<end of output>
Test time =   0.01 sec
----------------------------------------------------------
Test Failed.
"SSL.SSLTest" end time: Aug 31 17:00 CDT
"SSL.SSLTest" time elapsed: 00:00:00
----------------------------------------------------------

1020/1057 Testing: SSL.SSLTestWithMultiCAs
1020/1057 Test: SSL.SSLTestWithMultiCAs
Command: "/home/user/apps/proxygen/proxygen-main/proxygen/_build/proxygen/httpserver/tests/HTTPServerTests" "--gtest_filter=SSL.SSLTestWithMultiCAs"
Directory: /home/user/apps/proxygen/proxygen-main/proxygen/_build/proxygen/httpserver/tests
"SSL.SSLTestWithMultiCAs" start time: Aug 31 17:00 CDT
Output:
----------------------------------------------------------
Note: Google Test filter = SSL.SSLTestWithMultiCAs
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from SSL
[ RUN      ] SSL.SSLTestWithMultiCAs
E0831 17:00:09.963863 77258 SSLContextManager.cpp:713] error loading SSL certificate /home/user/apps/proxygen/proxygen-main/proxygen/httpserver/tests/certs/test_cert1.pem: std::runtime_error: SSL_CTX_use_certificate_chain_file: /home/user/apps/proxygen/proxygen-main/proxygen/httpserver/tests/certs/test_cert1.pem: ca md too weak
/home/user/apps/proxygen/proxygen-main/proxygen/httpserver/tests/HTTPServerTest.cpp:343: Failure
Value of: st.start()
  Actual: false
Expected: true
/home/user/apps/proxygen/proxygen-main/proxygen/httpserver/tests/HTTPServerTest.cpp:351: Failure
Value of: cb.success
  Actual: false
Expected: true
[  FAILED  ] SSL.SSLTestWithMultiCAs (5 ms)
[----------] 1 test from SSL (5 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (5 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] SSL.SSLTestWithMultiCAs

 1 FAILED TEST
<end of output>
Test time =   0.02 sec
----------------------------------------------------------
Test Failed.
"SSL.SSLTestWithMultiCAs" end time: Aug 31 17:00 CDT
"SSL.SSLTestWithMultiCAs" time elapsed: 00:00:00
----------------------------------------------------------
