### ISSUE TITLE
Frame restriction after receiving the HTTP/2 connection preface

### ISSUE THREAD

**Issue by coyorkdow** [facebook/proxygen#408]
In RFC7540#3.5, it says

> That is, the connection preface starts with the string PRI * HTTP/2.0\r\n\r\nSM\r\n\r\n). This sequence MUST be followed by a [SETTINGS](https://httpwg.org/specs/rfc7540.html#SETTINGS) frame ([Section 6.5](https://httpwg.org/specs/rfc7540.html#SETTINGS)), which MAY be empty.

So after receving the connection preface, the next frame MUST be SETTINGS.

In https://github.com/facebook/proxygen/blob/main/proxygen/lib/http/codec/HTTP2Codec.cpp, the function`HTTP2Codec::onIngress`. After the connection preface parsed, the frameState will be changed to `FRAME_HEADER`. In line 95,96, the condtion of causing error is that frameState is `DOWNSTREAM_CONNECTION_PREFACE` but frame is not SETTINGS. If this is a logic to restrict the frame that follow by connection preface, it seems won't work. 

RFC also says
> The server connection preface consists of a potentially empty [SETTINGS](https://httpwg.org/specs/rfc7540.html#SETTINGS) frame ([Section 6.5](https://httpwg.org/specs/rfc7540.html#SETTINGS)) that MUST be the first frame the server sends in the HTTP/2 connection.

So line 95,96 is a restriction for receiving from server, not the client? We need restriction for both upstream and downstream.

**Comment by hanidamlaj** [comment]
Thanks for opening the issue! From quickly glancing at the code snippet you provided, this does seem to be inconsistent with the H2 RFC7540. Hoping to follow up with a fix soon :).

**Comment by hanidamlaj** [comment]
Thanks for your patience! Just merged the fix here: https://github.com/facebook/proxygen/commit/ebdf8e6f1ebfa7ada33efa9923256bfca7ad7daf
