### ISSUE TITLE
Builds are failing on ubuntu

### ISSUE THREAD

**Issue by shoebmogal** [facebook/proxygen#41]
Here is the trace:

vagrant@vagrant-ubuntu-trusty-64:~/proxygen/proxygen/proxygen$ ./deps.sh
Reading package lists...
Building dependency tree...
Reading state information...
libssl-dev is already the newest version.
wget is already the newest version.
The following extra packages will be installed:
  autoconf automake autotools-dev libbison-dev libevent-core-2.0-5
  libevent-extra-2.0-5 libevent-openssl-2.0-5 libevent-pthreads-2.0-5
  libfl-dev m4
Suggested packages:
  autoconf2.13 gnu-standards autoconf-doc libtool gettext bison-doc
  build-essential krb5-doc
The following NEW packages will be installed:
  autoconf autoconf-archive automake autotools-dev bison flex gperf
  libbison-dev libcap-dev libevent-core-2.0-5 libevent-dev
  libevent-extra-2.0-5 libevent-openssl-2.0-5 libevent-pthreads-2.0-5
  libfl-dev libkrb5-dev libnuma-dev libsasl2-dev m4 pkg-config
0 upgraded, 20 newly installed, 0 to remove and 26 not upgraded.
Need to get 3,558 kB of archives.
After this operation, 15.2 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu/ trusty/universe autoconf-archive all 20131101-1 [710 kB]
Get:2 http://archive.ubuntu.com/ubuntu/ trusty/main m4 amd64 1.4.17-2ubuntu1 [195 kB]
Get:3 http://archive.ubuntu.com/ubuntu/ trusty/main libfl-dev amd64 2.5.35-10.1ubuntu2 [17.2 kB]
Get:4 http://archive.ubuntu.com/ubuntu/ trusty/main flex amd64 2.5.35-10.1ubuntu2 [211 kB]
Get:5 http://archive.ubuntu.com/ubuntu/ trusty-updates/main libevent-core-2.0-5 amd64 2.0.21-stable-1ubuntu1.14.04.1 [78.3 kB]
Get:6 http://archive.ubuntu.com/ubuntu/ trusty-updates/main libevent-extra-2.0-5 amd64 2.0.21-stable-1ubuntu1.14.04.1 [57.8 kB]
Get:7 http://archive.ubuntu.com/ubuntu/ trusty-updates/main libevent-openssl-2.0-5 amd64 2.0.21-stable-1ubuntu1.14.04.1 [12.6 kB]
Get:8 http://archive.ubuntu.com/ubuntu/ trusty-updates/main libevent-pthreads-2.0-5 amd64 2.0.21-stable-1ubuntu1.14.04.1 [6,126 B]
Get:9 http://archive.ubuntu.com/ubuntu/ trusty/main autoconf all 2.69-6 [322 kB]
Get:10 http://archive.ubuntu.com/ubuntu/ trusty/main autotools-dev all 20130810.1 [44.3 kB]
Get:11 http://archive.ubuntu.com/ubuntu/ trusty/main automake all 1:1.14.1-2ubuntu1 [510 kB]
Get:12 http://archive.ubuntu.com/ubuntu/ trusty/main libbison-dev amd64 2:3.0.2.dfsg-2 [338 kB]
Get:13 http://archive.ubuntu.com/ubuntu/ trusty/main bison amd64 2:3.0.2.dfsg-2 [257 kB]
Get:14 http://archive.ubuntu.com/ubuntu/ trusty/main gperf amd64 3.0.4-1 [111 kB]
Get:15 http://archive.ubuntu.com/ubuntu/ trusty/main libcap-dev amd64 1:2.24-0ubuntu2 [21.6 kB]
Get:16 http://archive.ubuntu.com/ubuntu/ trusty-updates/main libevent-dev amd64 2.0.21-stable-1ubuntu1.14.04.1 [269 kB]
Get:17 http://archive.ubuntu.com/ubuntu/ trusty/main libsasl2-dev amd64 2.1.25.dfsg1-17build1 [311 kB]
Get:18 http://archive.ubuntu.com/ubuntu/ trusty/main pkg-config amd64 0.26-1ubuntu4 [40.9 kB]
Get:19 http://archive.ubuntu.com/ubuntu/ trusty-updates/main libkrb5-dev amd64 1.12+dfsg-2ubuntu5.1 [14.4 kB]
Get:20 http://archive.ubuntu.com/ubuntu/ trusty-updates/main libnuma-dev amd64 2.0.9~rc5-1ubuntu3 [31.7 kB]
Fetched 3,558 kB in 9s (381 kB/s)
Selecting previously unselected package autoconf-archive.
(Reading database ... 77921 files and directories currently installed.)
Preparing to unpack .../autoconf-archive_20131101-1_all.deb ...
Unpacking autoconf-archive (20131101-1) ...
Selecting previously unselected package m4.
Preparing to unpack .../m4_1.4.17-2ubuntu1_amd64.deb ...
Unpacking m4 (1.4.17-2ubuntu1) ...
Selecting previously unselected package libfl-dev:amd64.
Preparing to unpack .../libfl-dev_2.5.35-10.1ubuntu2_amd64.deb ...
Unpacking libfl-dev:amd64 (2.5.35-10.1ubuntu2) ...
Selecting previously unselected package flex.
Preparing to unpack .../flex_2.5.35-10.1ubuntu2_amd64.deb ...
Unpacking flex (2.5.35-10.1ubuntu2) ...
Selecting previously unselected package libevent-core-2.0-5:amd64.
Preparing to unpack .../libevent-core-2.0-5_2.0.21-stable-1ubuntu1.14.04.1_amd64.deb ...
Unpacking libevent-core-2.0-5:amd64 (2.0.21-stable-1ubuntu1.14.04.1) ...
Selecting previously unselected package libevent-extra-2.0-5:amd64.
Preparing to unpack .../libevent-extra-2.0-5_2.0.21-stable-1ubuntu1.14.04.1_amd64.deb ...
Unpacking libevent-extra-2.0-5:amd64 (2.0.21-stable-1ubuntu1.14.04.1) ...
Selecting previously unselected package libevent-openssl-2.0-5:amd64.
Preparing to unpack .../libevent-openssl-2.0-5_2.0.21-stable-1ubuntu1.14.04.1_amd64.deb ...
Unpacking libevent-openssl-2.0-5:amd64 (2.0.21-stable-1ubuntu1.14.04.1) ...
Selecting previously unselected package libevent-pthreads-2.0-5:amd64.
Preparing to unpack .../libevent-pthreads-2.0-5_2.0.21-stable-1ubuntu1.14.04.1_amd64.deb ...
Unpacking libevent-pthreads-2.0-5:amd64 (2.0.21-stable-1ubuntu1.14.04.1) ...
Selecting previously unselected package autoconf.
Preparing to unpack .../autoconf_2.69-6_all.deb ...
Unpacking autoconf (2.69-6) ...
Selecting previously unselected package autotools-dev.
Preparing to unpack .../autotools-dev_20130810.1_all.deb ...
Unpacking autotools-dev (20130810.1) ...
Selecting previously unselected package automake.
Preparing to unpack .../automake_1%3a1.14.1-2ubuntu1_all.deb ...
Unpacking automake (1:1.14.1-2ubuntu1) ...
Selecting previously unselected package libbison-dev:amd64.
Preparing to unpack .../libbison-dev_2%3a3.0.2.dfsg-2_amd64.deb ...
Unpacking libbison-dev:amd64 (2:3.0.2.dfsg-2) ...
Selecting previously unselected package bison.
Preparing to unpack .../bison_2%3a3.0.2.dfsg-2_amd64.deb ...
Unpacking bison (2:3.0.2.dfsg-2) ...
Selecting previously unselected package gperf.
Preparing to unpack .../gperf_3.0.4-1_amd64.deb ...
Unpacking gperf (3.0.4-1) ...
Selecting previously unselected package libcap-dev:amd64.
Preparing to unpack .../libcap-dev_1%3a2.24-0ubuntu2_amd64.deb ...
Unpacking libcap-dev:amd64 (1:2.24-0ubuntu2) ...
Selecting previously unselected package libevent-dev.
Preparing to unpack .../libevent-dev_2.0.21-stable-1ubuntu1.14.04.1_amd64.deb ...
Unpacking libevent-dev (2.0.21-stable-1ubuntu1.14.04.1) ...
Selecting previously unselected package libsasl2-dev.
Preparing to unpack .../libsasl2-dev_2.1.25.dfsg1-17build1_amd64.deb ...
Unpacking libsasl2-dev (2.1.25.dfsg1-17build1) ...
Selecting previously unselected package pkg-config.
Preparing to unpack .../pkg-config_0.26-1ubuntu4_amd64.deb ...
Unpacking pkg-config (0.26-1ubuntu4) ...
Selecting previously unselected package libkrb5-dev.
Preparing to unpack .../libkrb5-dev_1.12+dfsg-2ubuntu5.1_amd64.deb ...
Unpacking libkrb5-dev (1.12+dfsg-2ubuntu5.1) ...
Selecting previously unselected package libnuma-dev:amd64.
Preparing to unpack .../libnuma-dev_2.0.9~rc5-1ubuntu3_amd64.deb ...
Unpacking libnuma-dev:amd64 (2.0.9~rc5-1ubuntu3) ...
Processing triggers for install-info (5.2.0.dfsg.1-2) ...
Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
Setting up autoconf-archive (20131101-1) ...
Setting up m4 (1.4.17-2ubuntu1) ...
Setting up libfl-dev:amd64 (2.5.35-10.1ubuntu2) ...
Setting up flex (2.5.35-10.1ubuntu2) ...
Setting up libevent-core-2.0-5:amd64 (2.0.21-stable-1ubuntu1.14.04.1) ...
Setting up libevent-extra-2.0-5:amd64 (2.0.21-stable-1ubuntu1.14.04.1) ...
Setting up libevent-openssl-2.0-5:amd64 (2.0.21-stable-1ubuntu1.14.04.1) ...
Setting up libevent-pthreads-2.0-5:amd64 (2.0.21-stable-1ubuntu1.14.04.1) ...
Setting up autoconf (2.69-6) ...
Setting up autotools-dev (20130810.1) ...
Setting up automake (1:1.14.1-2ubuntu1) ...
update-alternatives: using /usr/bin/automake-1.14 to provide /usr/bin/automake (automake) in auto mode
Setting up libbison-dev:amd64 (2:3.0.2.dfsg-2) ...
Setting up bison (2:3.0.2.dfsg-2) ...
update-alternatives: using /usr/bin/bison.yacc to provide /usr/bin/yacc (yacc) in auto mode
Setting up gperf (3.0.4-1) ...
Setting up libcap-dev:amd64 (1:2.24-0ubuntu2) ...
Setting up libevent-dev (2.0.21-stable-1ubuntu1.14.04.1) ...
Setting up libsasl2-dev (2.1.25.dfsg1-17build1) ...
Setting up pkg-config (0.26-1ubuntu4) ...
Setting up libkrb5-dev (1.12+dfsg-2ubuntu5.1) ...
Setting up libnuma-dev:amd64 (2.0.9~rc5-1ubuntu3) ...
Processing triggers for libc-bin (2.19-0ubuntu6.6) ...
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following extra packages will be installed:
  libgflags-dev libgflags2 libgoogle-glog0 libunwind8
The following NEW packages will be installed:
  libgflags-dev libgflags2 libgoogle-glog-dev libgoogle-glog0 libunwind8
0 upgraded, 5 newly installed, 0 to remove and 26 not upgraded.
Need to get 353 kB of archives.
After this operation, 1,757 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu/ trusty/main libgflags2 amd64 2.0-1.1ubuntu1 [65.9 kB]
Get:2 http://archive.ubuntu.com/ubuntu/ trusty/main libunwind8 amd64 1.1-2.2ubuntu3 [48.3 kB]
Get:3 http://archive.ubuntu.com/ubuntu/ trusty/main libgoogle-glog0 amd64 0.3.3-1 [61.3 kB]
Get:4 http://archive.ubuntu.com/ubuntu/ trusty/main libgflags-dev amd64 2.0-1.1ubuntu1 [72.7 kB]
Get:5 http://archive.ubuntu.com/ubuntu/ trusty/main libgoogle-glog-dev amd64 0.3.3-1 [105 kB]
Fetched 353 kB in 7s (49.4 kB/s)
Selecting previously unselected package libgflags2.
(Reading database ... 79615 files and directories currently installed.)
Preparing to unpack .../libgflags2_2.0-1.1ubuntu1_amd64.deb ...
Unpacking libgflags2 (2.0-1.1ubuntu1) ...
Selecting previously unselected package libunwind8.
Preparing to unpack .../libunwind8_1.1-2.2ubuntu3_amd64.deb ...
Unpacking libunwind8 (1.1-2.2ubuntu3) ...
Selecting previously unselected package libgoogle-glog0.
Preparing to unpack .../libgoogle-glog0_0.3.3-1_amd64.deb ...
Unpacking libgoogle-glog0 (0.3.3-1) ...
Selecting previously unselected package libgflags-dev.
Preparing to unpack .../libgflags-dev_2.0-1.1ubuntu1_amd64.deb ...
Unpacking libgflags-dev (2.0-1.1ubuntu1) ...
Selecting previously unselected package libgoogle-glog-dev.
Preparing to unpack .../libgoogle-glog-dev_0.3.3-1_amd64.deb ...
Unpacking libgoogle-glog-dev (0.3.3-1) ...
Setting up libgflags2 (2.0-1.1ubuntu1) ...
Setting up libunwind8 (1.1-2.2ubuntu3) ...
Setting up libgoogle-glog0 (0.3.3-1) ...
Setting up libgflags-dev (2.0-1.1ubuntu1) ...
Setting up libgoogle-glog-dev (0.3.3-1) ...
Processing triggers for libc-bin (2.19-0ubuntu6.6) ...
Reading package lists... Done
Building dependency tree
Reading state information... Done
libgflags-dev is already the newest version.
libgflags-dev set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 26 not upgraded.
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following extra packages will be installed:
  libdouble-conversion1
The following NEW packages will be installed:
  libdouble-conversion-dev libdouble-conversion1
0 upgraded, 2 newly installed, 0 to remove and 26 not upgraded.
Need to get 78.9 kB of archives.
After this operation, 344 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu/ trusty/universe libdouble-conversion1 amd64 2.0.1-1 [31.5 kB]
Get:2 http://archive.ubuntu.com/ubuntu/ trusty/universe libdouble-conversion-dev amd64 2.0.1-1 [47.3 kB]
Fetched 78.9 kB in 5s (15.5 kB/s)
Selecting previously unselected package libdouble-conversion1:amd64.
(Reading database ... 79668 files and directories currently installed.)
Preparing to unpack .../libdouble-conversion1_2.0.1-1_amd64.deb ...
Unpacking libdouble-conversion1:amd64 (2.0.1-1) ...
Selecting previously unselected package libdouble-conversion-dev.
Preparing to unpack .../libdouble-conversion-dev_2.0.1-1_amd64.deb ...
Unpacking libdouble-conversion-dev (2.0.1-1) ...
Setting up libdouble-conversion1:amd64 (2.0.1-1) ...
Setting up libdouble-conversion-dev (2.0.1-1) ...
Processing triggers for libc-bin (2.19-0ubuntu6.6) ...
Cloning folly
Cloning into 'folly'...
remote: Counting objects: 12096, done.
remote: Total 12096 (delta 0), reused 0 (delta 0), pack-reused 12096
Receiving objects: 100% (12096/12096), 5.31 MiB | 7.14 MiB/s, done.
Resolving deltas: 100% (9373/9373), done.
Checking connectivity... done.
Note: checking out 'v0.34.0'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at 7c9f263... Bump version to 34:0
configure.ac:32: warning: macro 'AM_PROG_LIBTOOL' not found in library
configure.ac:32: error: possibly undefined macro: AM_PROG_LIBTOOL
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/bin/autoconf failed with exit status: 1

**Comment by rpraveen** [comment]
Looking into this. Thanks for reporting.

**Comment by rpraveen** [comment]
@shoebmogal The builds were failing because the folly dependencies are missing in your Ubuntu box. Please check the Dependencies section in https://github.com/facebook/folly. I am working on adding them to the deps.sh script in Proxygen so that we can automatically pull them for you.
