### ISSUE TITLE
fetchcontent fail

### ISSUE THREAD

**Issue by bssbx** [facebook/proxygen#410]
this the logs:
By not providing "Findfmt.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "fmt", but
  CMake did not find one.

  Could not find a package configuration file provided by "fmt" with any of
  the following names:

    fmtConfig.cmake
    fmt-config.cmake

  Add the installation prefix of "fmt" to CMAKE_PREFIX_PATH or set "fmt_DIR"
  to a directory containing one of the above files.  If "fmt" provides a
  separate development package or SDK, be sure it has been installed.

i think caused by submodules

**Comment by afrind** [comment]
Closing old issue, please reopen if you are still having trouble
