### ISSUE TITLE
how to set the http version to HQ

### ISSUE THREAD

**Issue by wtao0221** [facebook/proxygen#412]
Hi,

One quick question, how to set the http version to HQ rather than the H1Q_FB_V1 or H1Q_FB_V2?

**Comment by chanh1964** [comment]
Not sure how your implementation is. If you use the demo hq server, you can set it by the flag `--protocol`.
For example
```sh
_build/proxygen/httpserver/hq --mode=server --protocol=h3
```

You can check these files for more information: https://github.com/facebook/proxygen/blob/a2c8ae52b035116157dd1a46f6693332199017a9/proxygen/lib/http/session/HQSession.cpp#L91-L95
https://github.com/facebook/proxygen/blob/a2c8ae52b035116157dd1a46f6693332199017a9/proxygen/httpserver/samples/hq/HQCommandLine.cpp#L38
https://github.com/facebook/proxygen/blob/a2c8ae52b035116157dd1a46f6693332199017a9/proxygen/httpserver/samples/hq/HQCommandLine.cpp#L225-L236

**Comment by wtao0221** [comment]
BTW, will H3 option override the desired option in mvfst, for example https://github.com/facebookincubator/mvfst/blob/main/quic/state/TransportSettings.h#L260?

I found that if we disable this know for multiplexing different frames from different streams into one packet. The packet trace still shows it is not disabled.

**Comment by wtao0221** [comment]
interestingly, if we set the protocol to `h3`, the knob does not work. if we set the protocol to `hq-29`, the knob works.

**Comment by wtao0221** [comment]
BTW, is there any knob to disable dynamic table?

**Comment by lnicco** [comment]
> interestingly, if we set the protocol to h3, the knob does not work. if we set the protocol to hq-29, the knob works. 

Can you please provide a repro? This is kind of surprising since the streamFramePerPacket transport setting is completely orthogonal to the ALPN version. 

> BTW, is there any knob to disable dynamic table? 

That is an HTTP/3 setting. 
you can call the `setEgressSettings` with custom settings  https://github.com/facebook/proxygen/blob/main/proxygen/lib/http/session/HQSession.h#L2088 
specifically you want `HEADER_TABLE_SIZE = 0`

**Comment by wtao0221** [comment]
Thx for the prompt response.

So basically, I made some modifications to the `mvfst` to disable the encryption (I hope there is some knob, but I failed to find one, pls correct me if I am wrong) after 1-RTT handshake (i am not sure whether this phrase is correct, it is the crypto exchange phase), so that I can easily check the content of the packet without decrypting it.

There are maybe two types of streams: uni for control messages (e.g., H3 SETTINGS, QPACK ENCODER/DECODER), bi for H3 request/response.

My observation is that, the control message frame is packed with H3 request frame into one UDP packet. But there is no H3 request frames from different streams being packed together.

Maybe this makes sense if you check https://github.com/facebookincubator/mvfst/blob/be0cd3dacc166695d3b97fe9ee4c7142a4ceeccc/quic/api/QuicPacketScheduler.cpp#L478. But I am not sure.

**Comment by wtao0221** [comment]
And is there any API that we can use to add custom header fields?

**Comment by afrind** [comment]
There isn't a flag to disable huffman encoding.  You can hack the QPACK encoder to just pass false for the huffman flag if you want to debug:

https://github.com/facebook/proxygen/blob/main/proxygen/lib/http/codec/compress/QPACKCodec.cpp#L28
