### ISSUE TITLE
MISSING quic/codec/QuicInteger.h  while using "build.sh"(./proxygen/build.sh) compile the repository.

### ISSUE THREAD

**Issue by XInitialize** [facebook/proxygen#416]
While I follow the README.md and trying to compile this job for futher development. It occurs a FATAL ERROR while compiling by using command "./build.sh" at dir root "proxygen/".

Here is my ENV:

+ linux-kernel= 5.15.0-39-generic
+ os version= Ubuntu 22.04 LTS
+ cmake version= 3.22.1
+ gcc/g++ version= 10.3.0

<pre>[ 72%] Built target StructuredHeadersTests
[ 72%] <font color="#26A269">Building CXX object proxygen/lib/http/connpool/test/CMakeFiles/ConnpoolTests.dir/SessionPoolTest.cpp.o</font>
[ 73%] <font color="#26A269">Building CXX object proxygen/lib/utils/test/CMakeFiles/UtilTests.dir/UtilTest.cpp.o</font>
In file included from <b>/home/.../proxygen-2022.06.20.00/proxygen/lib/http/codec/HQFramedCodec.h:11</b>,
                 from <b>/home/.../proxygen-2022.06.20.00/proxygen/lib/http/codec/HQControlCodec.h:11</b>,
                 from <b>/home/.../proxygen-2022.06.20.00/proxygen/lib/http/session/HQSession.h:17</b>,
                 from <b>/home/.../proxygen-2022.06.20.00/proxygen/lib/http/session/test/HQSessionMocks.h:13</b>,
                 from <b>/home/.../proxygen-2022.06.20.00/proxygen/lib/http/connpool/test/SessionPoolTest.cpp:21</b>:
<b>/home/.../proxygen-2022.06.20.00/proxygen/lib/http/codec/HQFramer.h:21:10:</b> <font color="#C01C28"><b>fatal error: </b></font>quic/codec/QuicInteger.h: 没有那个文件或目录
   21 | #include <font color="#C01C28"><b>&lt;quic/codec/QuicInteger.h&gt;</b></font>
      |          <font color="#C01C28"><b>^~~~~~~~~~~~~~~~~~~~~~~~~~</b></font>
compilation terminated.
make[2]: *** [proxygen/lib/http/connpool/test/CMakeFiles/ConnpoolTests.dir/build.make:76：proxygen/lib/http/connpool/test/CMakeFiles/ConnpoolTests.dir/SessionPoolTest.cpp.o] 错误 1
make[1]: *** [CMakeFiles/Makefile2:1458：proxygen/lib/http/connpool/test/CMakeFiles/ConnpoolTests.dir/all] 错误 2
make[1]: *** 正在等待未完成的任务....
</pre>

I tried in both of  the latest and "2022.06.20.00" version, and both of them failed at this above.

How could I fix it?

**Comment by lnicco** [comment]
this should be fixed. please rebase past the latest commit and try again, and reopen this issue if it doesn't work
