### ISSUE TITLE
HTTP3 and QUIC server/client

### ISSUE THREAD

**Issue by NooshinEghbal** [facebook/proxygen#417]
Hello,

I tried running 
_build/proxygen/httpserver/hq --mode=server
_build/proxygen/httpserver/hq --mode=client --path=www.google.com

and I got 
I0626 17:42:58.275476 236823 HQClient.cpp:61] HQClient connecting to [::1]:6666
I0626 17:42:58.278154 236823 CurlClient.cpp:187] Sending request for www.google.com
I0626 17:42:58.278918 236823 CurlClient.cpp:273] Got EOM for www.google.com. Txn Time= 0 ms

My question is that is this client really sending requests to the server to load the page address that we put after --path? Or there is no http3 client implementation in Proxygen yet?
How can we check the responses from the server? 

Thanks.

**Comment by afrind** [comment]
hq sends the request over HTTP/3.  I think the args you want are 

` ./hq --mode=client --port=443 --host www.google.com --path / -v 4 --protocol h3 --quic_version 1`
