### ISSUE TITLE
How to correctly use multiple RequestHandlerFactories.

### ISSUE THREAD

**Issue by h-barthwal** [facebook/proxygen#421]
Folks,
I am trying to figure out how to correctly use proxygen's RequestHandler/RequestHandlerFactory in my project. I have two RequestHandlerFactories: `FirstRequestHandlerFactory` and `SecondRequestHandlerFactory`. I want to be able to handle certain requests from within the `RequestHandler*` returned by the first factory and not let the flow of control go through the second factory.  But what I have observed is that the handlers are instantiated by both the factories. Although only one of the handler ends up getting executed, the other one simply gets allocated and leaks memory as it is never executed and its requestComplete (or onError) functions are not able to `delete this`. Here is a code snippet demonstrating this issue:

```cpp
class FirstRequestHandler : public proxygen::RequestHandler
{
public:
  ~FirstRequestHandler()
  {
    LOG(INFO) << "Deallocated FirstRequestHandler";
  }

  void onRequest(std::unique_ptr<proxygen::HTTPMessage> message) noexcept override
  {
    proxygen::ResponseBuilder builder(downstream_);
    builder.status(200, "OK").body("First handler's response.").sendWithEOM();
  }

  void requestComplete() noexcept override
  {
    delete this;
  }

  void onError(proxygen::ProxygenError) noexcept override
  {
    delete this;
  }
  void onBody(std::unique_ptr<folly::IOBuf>) noexcept override
  {}
  void onEOM() noexcept override
  {}
  void onUpgrade(proxygen::UpgradeProtocol) noexcept override
  {}
};

class FirstRequestHandlerFactory final : public proxygen::RequestHandlerFactory
{
public:
  void onServerStart(folly::EventBase* evb) noexcept override
  {}
  void onServerStop() noexcept override
  {}
  proxygen::RequestHandler* onRequest(proxygen::RequestHandler* upstream_request_handler,
                                      proxygen::HTTPMessage* message) noexcept override
  {
    const auto& path = message->getPath();
    if (path == "/first") {
      LOG(INFO) << "Allocated FirstRequestHandler";
      return new FirstRequestHandler;
    }
    return upstream_request_handler;
  }
};

class SecondRequestHandler : public proxygen::RequestHandler
{
public:
  ~SecondRequestHandler()
  {
    LOG(INFO) << "Deallocated SecondRequestHandler";
  }

  void onRequest(std::unique_ptr<proxygen::HTTPMessage> message) noexcept override
  {
    proxygen::ResponseBuilder builder(downstream_);
    builder.status(200, "OK").body("Second handler's response.").sendWithEOM();
  }

  void requestComplete() noexcept override
  {
    delete this;
  }

  void onError(proxygen::ProxygenError) noexcept override
  {
    delete this;
  }
  void onBody(std::unique_ptr<folly::IOBuf>) noexcept override
  {}
  void onEOM() noexcept override
  {}
  void onUpgrade(proxygen::UpgradeProtocol) noexcept override
  {}
};

class ResourceNotFoundHandler : public proxygen::RequestHandler
{
public:
  ~ResourceNotFoundHandler()
  {
    LOG(INFO) << "Deallocated ResourceNotFoundHandler";
  }

  void onRequest(std::unique_ptr<proxygen::HTTPMessage> message) noexcept override
  {
    proxygen::ResponseBuilder builder(downstream_);
    std::string error_message = "Could not find path ";
    error_message += message->getPathAsStringPiece().data();
    builder.body(std::move(error_message)).status(404, "Not Found").sendWithEOM();
  }

  void requestComplete() noexcept override
  {
    delete this;
  }

  void onError(proxygen::ProxygenError) noexcept override
  {
    delete this;
  }
  void onBody(std::unique_ptr<folly::IOBuf>) noexcept override
  {}
  void onEOM() noexcept override
  {}
  void onUpgrade(proxygen::UpgradeProtocol) noexcept override
  {}
};

class SecondRequestHandlerFactory final : public proxygen::RequestHandlerFactory
{
public:
  void onServerStart(folly::EventBase* evb) noexcept override
  {}
  void onServerStop() noexcept override
  {}
  proxygen::RequestHandler* onRequest(proxygen::RequestHandler* upstream_request_handler,
                                      proxygen::HTTPMessage* message) noexcept override
  {
    const auto& path = message->getPath();
    if (path == "/second") {
      return new SecondRequestHandler;
    }
    LOG(INFO) << "Allocated ResourceNotFoundHandler";
    return new ResourceNotFoundHandler;
  }
};


```

The factories are hooked up with the service as follows:
```cpp
  RequestHandlerChain()
      .addThen<FirstRequestHandlerFactory>()
      .addThen<SecondRequestHandlerFactory>()
      .build();
```

When I hit my service at `/first`, I get the following logs:

```bash
Allocated ResourceNotFoundHandler
Allocated FirstRequestHandler
Deallocated FirstRequestHandler
```

And thus the `ResourceNotFoundHandler` object is leaked. Can someone tell me what I am not doing right here? Thanks in advance !

**Comment by jbeshay** [comment]
If your request is for `/first`, then according to your sample code, "Allocated SecondRequestHandler" should not be printed in the log. This condition should not match:

```
    if (path == "/second") {
      LOG(INFO) << "Allocated SecondRequestHandler";
      return new SecondRequestHandler;
    }
```

I would check other logic besides what you shared in the sample.

**Comment by h-barthwal** [comment]
@jbeshay I have updated the sample code and output to demonstrate the issue. Sorry about the wrong code. It's not the `SecondRequestHandler` that is leaked. Its the `ResourceNotFoundHandler`.

**Comment by jbeshay** [comment]
The handler logic here is invalid. A request for `/first` will be handled by `FirstRequestHandler` and return a 200 with EOM. The request is now complete. The SecondRequestHandler cannot send another response. What is the `ResourceNotFoundHandler` supposed to do?

**Comment by h-barthwal** [comment]
Really appreciate you taking time to help me. Responding to your questions/comments as follows:

> What is the ResourceNotFoundHandler supposed to do?

Let's say the user hits the service at `/junk`. I want to be able to return 404 in that case. Given that all the possible paths for my service are not known to `FirstRequestHandlerFactory`, I cannot just `return new ResourceNotFoundHandler` from  `FirstRequestHandlerFactory`. However, once the flow of control tests the `path == "/second"` condition within `SecondRequestHandlerFactory` and it does not match, then we know that request should be treated as 404. That's why I have put `return new ResourceNotFoundHandler` there.

> I think the handler logic here is invalid...

I understand that logic is wrong because its clearly not doing what I want (without leaking memory). I could put the handling for both `/first` and `/second` into one `RequestHandlerFactory` and then I can avoid this problem as all the possible inputs would be handled in one place. But I am looking for a way to be able to achieve the _correct behavior_ while being able to instantiate `RequestHandler`s in two in different `RequestHandlerFactories` for the respective paths. Does that make sense?

**Comment by jbeshay** [comment]
Thanks for the explanation. Usually in a request handler chain, you'd have multiple filters followed by one terminal RequestHandlerFactory that writes a response as this example shows: https://github.com/facebook/proxygen/blob/main/proxygen/httpserver/HTTPServerOptions.h#L49-L62

OnRequest() gets called for the handler produced by the first factory in the chain. And it's the responsibility of each handler to call onRequest for its upstream handler. See https://github.com/facebook/proxygen/blob/main/proxygen/httpserver/Filters.h#L44

In you case with multiple RequestHandlerFactory instances that are writing a response. The first handler in the chain is responsible for triggering the remaining handlers. Either calling onRequest() (or requestComplete() in your case since the response has already been written).

What's happening in your case is that all the handlers are created. So for a request to `/first`, both the `FirstRequestHandler` and `ResourceNotFound` handlers are created (see https://github.com/facebook/proxygen/blob/main/proxygen/httpserver/HTTPServerAcceptor.cpp#L109-L113). OnRequest() is called for `FirstRequestHandler` but that doesn't fulfill its responsibility of signaling the `ResourceNotFound` that is its upstream. 

I wouldn't recommend keeping a design with more than one terminal RequestHandlerFactories, but if you really want to do it, you will need the `FirstRequestHandler` to keep track of its upstream handler and call `requestComplete()` function on it if it has sent a response.

**Comment by h-barthwal** [comment]
@jbeshay Thanks for the elaborate response. I would probably move all the `RequestHandler` instantiations in one `RequestHandlerFactory` to keep things simpler. Closing the issue.
