### ISSUE TITLE
add `URL::join(string_view relative)` ?

### ISSUE THREAD

**Issue by kvtb** [facebook/proxygen#423]
It would be very convenient to have `URL::join` function to construct a new `URL` from an existing `URL` and a relative path (for example one from `Location` server header on 302-redirect).

Despite simplicity, implementation has some corner cases, including security sensitive ones, so it is better to have it implemented in a library than to left is an an exercise to a library user.

**Comment by afrind** [comment]
Happy to take a PR if you are feeling ambitious

**Comment by afrind** [comment]
Would still accept a PR for this but otherwise it's nonurgent.
