### ISSUE TITLE
what's the behavior of reserved frame type in proxygen

### ISSUE THREAD

**Issue by wtao0221** [facebook/proxygen#425]
Hi,

I notice there may be some reserved frame types (`0x1f * N + 0x21`) in proxygen.

So what is the behavior of those frames? and what's the format? Are all they just consisting of one `0x00` payload?

**Comment by kvtsoy** [comment]
We do nothing with them. This is dictated by the RFC: https://www.rfc-editor.org/rfc/rfc9114.html#section-6.2.3

**Comment by wtao0221** [comment]
sorry, that is the problem. If I do not misunderstand, according to RFC, it says that the behavior of such reserved-type frames is platform-dependent.

**Comment by mjoras** [comment]
It is not platform dependent. The RFC states they must lack semantics, which is what we do.

The payload is up to the implementation. We do not send a payload.

**Comment by wtao0221** [comment]
So is it safe to say proxygen will always add just one `0x00` after these reserved types?

**Comment by mjoras** [comment]
That's the length field of the header. It will represent the length of the payload now and in the future. If we decide to add a payload later it will be reflected in the length.

**Comment by wtao0221** [comment]
Gotcha. So basically, it still follows type + length + payload format.
