### ISSUE TITLE
The example 'echo' code does not compile.

### ISSUE THREAD

**Issue by pinkisemils** [facebook/proxygen#44]
The provided example code in /proxygen/httpserver/samples/echo. 
This is on a current Archlinux installation with all the dependencies satisfied.
The makefile build fails the same as with ' g++ -std=c++11 -o my_echo EchoServer.cpp EchoHandler.cpp -lproxygenhttpserver -lfolly -lglog -lgflags -pthread'
The compiler errors given are as follows:

EchoServer.cpp:29:13: error: expected constructor, destructor, or type conversion before ‘(’ token
 DEFINE_int32(http_port, 11000, "Port to listen on with HTTP protocol");
             ^
EchoServer.cpp:30:13: error: expected constructor, destructor, or type conversion before ‘(’ token
 DEFINE_int32(spdy_port, 11001, "Port to listen on with SPDY protocol");
             ^
EchoServer.cpp:31:14: error: expected constructor, destructor, or type conversion before ‘(’ token
 DEFINE_string(ip, "localhost", "IP/Hostname to bind to");
              ^
EchoServer.cpp:32:13: error: expected constructor, destructor, or type conversion before ‘(’ token
 DEFINE_int32(threads, 0, "Number of threads to listen on. Numbers <= 0 "
             ^
EchoServer.cpp: In function ‘int main(int, char**)’:
EchoServer.cpp:54:3: error: ‘gflags’ has not been declared
   gflags::ParseCommandLineFlags(&argc, &argv, true);
   ^
EchoServer.cpp:59:20: error: ‘FLAGS_ip’ was not declared in this scope
     {SocketAddress(FLAGS_ip, FLAGS_http_port, true), Protocol::HTTP},
                    ^
EchoServer.cpp:59:30: error: ‘FLAGS_http_port’ was not declared in this scope
     {SocketAddress(FLAGS_ip, FLAGS_http_port, true), Protocol::HTTP},
                              ^
EchoServer.cpp:60:30: error: ‘FLAGS_spdy_port’ was not declared in this scope
     {SocketAddress(FLAGS_ip, FLAGS_spdy_port, true), Protocol::SPDY},
                              ^
EchoServer.cpp:61:3: error: could not convert ‘{{<expression error>, HTTP}, {<expression error>, SPDY}}’ from ‘<brace-enclosed initializer list>’ to ‘std::vector<proxygen::HTTPServer::IPConfig>’
   };
   ^
EchoServer.cpp:63:7: error: ‘FLAGS_threads’ was not declared in this scope
   if (FLAGS_threads <= 0) {
       ^
EchoServer.cpp:69:41: error: ‘FLAGS_threads’ was not declared in this scope
   options.threads = static_cast<size_t>(FLAGS_threads);

**Comment by bugok** [comment]
Thank you for reporting this. Can you please include the full output?
Thanks.

**Comment by bugok** [comment]
Closing this - as per discussion on the irc channel - seems like this is a bad header file inclusion.
Please open again if this hasn't been resolved.
