### ISSUE TITLE
ClientHello Callback

### ISSUE THREAD

**Issue by SteveSelva** [facebook/proxygen#446]
Is there any way to insert a callback at clientHello message during the TLS handshake while accepting the connection in proxygen::HTTPServer?

**Comment by afrind** [comment]
When configured to use OpenSSL as the TLS stack (eg: folly::SSLContext) we do not for sure.  The socket abstraction provides a way to set a handshake verification callback, though it might not be plumbed all the way through, and may not be what you're looking for.

I don't think Fizz has this either, but you might need to ask in their repo: https://github.com/facebookincubator/fizz

What is your high-level goal?  Maybe there's something else in place that will work.

**Comment by SteveSelva** [comment]
I want to get the server name from the SNI extension in ClientHello message.

**Comment by afrind** [comment]
Is it ok to get that after the handshake completes?  This is available in the `wangle::TransportInfo` structure `serverName` field, which is accessible from your RequestHandler as `downstream_->getSetupTransportInfo()`.

**Comment by SteveSelva** [comment]
No, I need the server name at the time of ClientHello.
