### ISSUE TITLE
[Mac] gen_HTTPCommonHeaders.*.sh require GNU sed

### ISSUE THREAD

**Issue by jwatzman** [facebook/proxygen#45]
The `gen_HTTPCommonHeaders.h.sh` and `gen_HTTPCommonHeaders.cpp.sh` shell scripts both require GNU sed, and don't work with the default BSD sed on Mac OS X. Context is that I'm poking at HHVM building on OS X again, and this is a blocker.

The problems I've seen so far:
- BSD sed doesn't support `\U` or `\0`. https://github.com/facebook/proxygen/blob/4126e0905239e5d39aee39560e2177a2fc3f6550/proxygen/lib/http/gen_HTTPCommonHeaders.cpp.sh#L7 can be replaced with `awk '{ print $0", HTTP_HEADER_"toupper($0) }'` without too much trouble though.
- BSD sed doesn't understand or deal with `\n` the same way as GNU sed, leading there to being the character `n` in the data passed to `gperf` when there should be a newline there. Example on my Mac:

```
$ echo "foo" | sed 's/foo/bar\nbaz/'
barnbaz
$ echo "foo" | gsed 's/foo/bar\nbaz/'
bar
baz
$
```

I see a couple of options here.

- Have some configuration that lets you specify what `sed` you want. This is annoying but doable. Are you cool with this? The HHVM build scripts can detect this and set the right one -- though each project using proxygen would have to do this. Not sure how to do it more generally.
- This used to be a ruby or python script or something. Is taking a dependency on one of those really that big of a deal? It's much much more likely to be portable than shell script / sed / awk shenanigans -- and we'd end up taking a dependency on `gsed` on BSD/Mac systems anyways, it does not come preinstalled. This isn't the first portability issue FWIW, cf. 4126e0905239e5d39aee39560e2177a2fc3f6550, in which the scripts originally weren't even portable to a different Linux distribution.

**Comment by bugok** [comment]
Thanks for reporting this @jwatzman.
I think it's possible to rewrite these scripts in python, since we already use python to generate some code: https://github.com/facebook/proxygen/blob/v0.21.0/proxygen/lib/utils/Makefile.am#L6
If you're up for translating bash to python - go ahead. :)
Feel free to update this issue in the future. Please ping me if you have any issue.

**Comment by bugok** [comment]
An internal diff has been submitted for this. It should be out with this week's release.
