### ISSUE TITLE
build error on ubuntu 15.04

### ISSUE THREAD

**Issue by js7222** [facebook/proxygen#48]
I haven't looked into why this happens at all yet but here is the output of the build

Reading package lists...
Building dependency tree...
Reading state information...
bison is already the newest version.
flex is already the newest version.
g++ is already the newest version.
gperf is already the newest version.
libcap-dev is already the newest version.
libevent-dev is already the newest version.
libkrb5-dev is already the newest version.
libsasl2-dev is already the newest version.
libsnappy-dev is already the newest version.
libtool is already the newest version.
pkg-config is already the newest version.
wget is already the newest version.
autoconf-archive is already the newest version.
libboost-all-dev is already the newest version.
libjemalloc-dev is already the newest version.
libnuma-dev is already the newest version.
libssl-dev is already the newest version.
0 to upgrade, 0 to newly install, 0 to remove and 0 not to upgrade.
Reading package lists...
Building dependency tree...
Reading state information...
libgoogle-glog-dev is already the newest version.
0 to upgrade, 0 to newly install, 0 to remove and 0 not to upgrade.
Reading package lists...
Building dependency tree...
Reading state information...
libgflags-dev is already the newest version.
0 to upgrade, 0 to newly install, 0 to remove and 0 not to upgrade.
Reading package lists...
Building dependency tree...
Reading state information...
libdouble-conversion-dev is already the newest version.
0 to upgrade, 0 to newly install, 0 to remove and 0 not to upgrade.
HEAD is now at 1b62ef8... Bump version to 42:0
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking how to print strings... printf
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking for a sed that does not truncate output... /bin/sed
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for fgrep... /bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for mt... mt
checking if mt is a manifest tool... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... gcc3
checking how to run the C++ preprocessor... g++ -E
checking for ld used by g++... /usr/bin/ld -m elf_x86_64
checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking for g++ option to produce PIC... -fPIC -DPIC
checking if g++ PIC flag -fPIC -DPIC works... yes
checking if g++ static flag -static works... yes
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking whether gcc understands -c and -o together... (cached) yes
checking dependency style of gcc... (cached) gcc3
checking if g++ supports C++0x features without additional flags... no
checking if g++ supports C++0x features with -std=c++0x... yes
checking if g++ supports C++0x features with -std=gnu++0x... yes
checking for openlog in -lglog... yes
checking for getenv in -lgflags... yes
checking for SSL_ctrl in -lssl... yes
checking for boostlib >= 1.51.0... yes
checking whether the Boost::Context library is available... no
checking whether the Boost::Thread library is available... yes
checking for exit in -lboost_thread... yes
checking whether the Boost::Regex library is available... yes
checking for exit in -lboost_regex... yes
checking whether the Boost::System library is available... yes
checking for exit in -lboost_system... yes
checking whether the Boost::Filesystem library is available... yes
checking for exit in -lboost_filesystem... yes
checking for ANSI C header files... (cached) yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking features.h usability... yes
checking features.h presence... yes
checking for features.h... yes
checking for inttypes.h... (cached) yes
checking limits.h usability... yes
checking limits.h presence... yes
checking for limits.h... yes
checking for stdint.h... (cached) yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking for unistd.h... (cached) yes
checking mutex.h usability... no
checking mutex.h presence... no
checking for mutex.h... no
checking malloc.h usability... yes
checking malloc.h presence... yes
checking for malloc.h... yes
checking emmintrin.h usability... yes
checking emmintrin.h presence... yes
checking for emmintrin.h... yes
checking byteswap.h usability... yes
checking byteswap.h presence... yes
checking for byteswap.h... yes
checking bits/functexcept.h usability... yes
checking bits/functexcept.h presence... yes
checking for bits/functexcept.h... yes
checking bits/c++config.h usability... yes
checking bits/c++config.h presence... yes
checking for bits/c++config.h... yes
checking double-conversion/double-conversion.h usability... yes
checking double-conversion/double-conversion.h presence... yes
checking for double-conversion/double-conversion.h... yes
checking for ceil in -ldouble-conversion... yes
checking for event_set in -levent... yes
checking for xallocx in -ljemalloc... yes
checking for stdbool.h that conforms to C99... yes
checking for _Bool... no
checking for an ANSI C-conforming const... yes
checking for inline... inline
checking for size_t... yes
checking whether time.h and sys/time.h may both be included... yes
checking for working volatile... yes
checking for __int128... yes
checking for ptrdiff_t... yes
checking for pthread_spinlock_t... yes
checking for ifunc support... yes
checking for final and override support... yes
checking for std::this_thread::sleep_for... yes
checking for constexpr strlen... yes
checking for libc++... no
checking for usable std::is_trivially_copyable... no
checking gflags namespace... google
checking for weak symbol support... yes
checking for library containing cplus_demangle_v3_callback... no
checking for library containing clock_gettime... none required
checking for pthread_atfork support... yes
checking for getdelim... yes
checking for gettimeofday... yes
checking for memmove... yes
checking for memset... yes
checking for pow... yes
checking for strerror... yes
checking for pthread_yield... no
checking for malloc_size... no
checking for malloc_usable_size... yes
checking for memrchr... yes
checking for pipe2... yes
checking sched.h usability... yes
checking sched.h presence... yes
checking for sched.h... yes
checking for sched_yield... yes
checking lz4.h usability... no
checking lz4.h presence... no
checking for lz4.h... no
checking snappy.h usability... yes
checking snappy.h presence... yes
checking for snappy.h... yes
checking for main in -lsnappy... yes
checking zlib.h usability... yes
checking zlib.h presence... yes
checking for zlib.h... yes
checking for main in -lz... yes
checking lzma.h usability... yes
checking lzma.h presence... yes
checking for lzma.h... yes
checking for main in -llzma... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating test/Makefile
config.status: creating test/function_benchmark/Makefile
config.status: creating config.h
config.status: config.h is unchanged
config.status: executing folly-config.h commands
config.status: creating folly-config.h - prefix FOLLY for config.h defines
config.status: folly-config.h is unchanged
config.status: executing depfiles commands
config.status: executing libtool commands
make  all-recursive
make[1]: Entering directory '/home/james/proxygen/proxygen/folly/folly'
Making all in .
make[2]: Entering directory '/home/james/proxygen/proxygen/folly/folly'
/bin/bash ./libtool  --tag=CXX   --mode=link g++  -std=gnu++0x -g -O2 -lboost_thread -lboost_filesystem -lboost_system -lboost_regex -lpthread -version-info 42:0:0  -o libfollybase.la  Conv.lo Demangle.lo EscapeTables.lo Format.lo FormatTables.lo Malloc.lo Range.lo StringBase.lo String.lo Unicode.lo     -llzma -lz -lsnappy -ljemalloc -levent -ldouble-conversion -lssl -lgflags -lglog 
depbase=`echo io/async/AsyncTimeout.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/bash ./libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H   -I./.. -pthread -I/usr/include   -std=gnu++0x -g -O2 -MT io/async/AsyncTimeout.lo -MD -MP -MF $depbase.Tpo -c -o io/async/AsyncTimeout.lo io/async/AsyncTimeout.cpp &&\
mv -f $depbase.Tpo $depbase.Plo
depbase=`echo io/async/AsyncUDPSocket.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/bash ./libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H   -I./.. -pthread -I/usr/include   -std=gnu++0x -g -O2 -MT io/async/AsyncUDPSocket.lo -MD -MP -MF $depbase.Tpo -c -o io/async/AsyncUDPSocket.lo io/async/AsyncUDPSocket.cpp &&\
mv -f $depbase.Tpo $depbase.Plo
depbase=`echo io/async/AsyncServerSocket.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/bash ./libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H   -I./.. -pthread -I/usr/include   -std=gnu++0x -g -O2 -MT io/async/AsyncServerSocket.lo -MD -MP -MF $depbase.Tpo -c -o io/async/AsyncServerSocket.lo io/async/AsyncServerSocket.cpp &&\
mv -f $depbase.Tpo $depbase.Plo
depbase=`echo io/async/AsyncSocket.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/bash ./libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H   -I./.. -pthread -I/usr/include   -std=gnu++0x -g -O2 -MT io/async/AsyncSocket.lo -MD -MP -MF $depbase.Tpo -c -o io/async/AsyncSocket.lo io/async/AsyncSocket.cpp &&\
mv -f $depbase.Tpo $depbase.Plo
depbase=`echo io/async/AsyncSSLSocket.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/bash ./libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H   -I./.. -pthread -I/usr/include   -std=gnu++0x -g -O2 -MT io/async/AsyncSSLSocket.lo -MD -MP -MF $depbase.Tpo -c -o io/async/AsyncSSLSocket.lo io/async/AsyncSSLSocket.cpp &&\
mv -f $depbase.Tpo $depbase.Plo
depbase=`echo io/async/EventBase.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/bash ./libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H   -I./.. -pthread -I/usr/include   -std=gnu++0x -g -O2 -MT io/async/EventBase.lo -MD -MP -MF $depbase.Tpo -c -o io/async/EventBase.lo io/async/EventBase.cpp &&\
mv -f $depbase.Tpo $depbase.Plo
depbase=`echo io/async/EventBaseManager.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/bash ./libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H   -I./.. -pthread -I/usr/include   -std=gnu++0x -g -O2 -MT io/async/EventBaseManager.lo -MD -MP -MF $depbase.Tpo -c -o io/async/EventBaseManager.lo io/async/EventBaseManager.cpp &&\
mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  g++ -DHAVE_CONFIG_H -I./.. -pthread -I/usr/include -std=gnu++0x -g -O2 -MT io/async/EventBaseManager.lo -MD -MP -MF io/async/.deps/EventBaseManager.Tpo -c io/async/EventBaseManager.cpp  -fPIC -DPIC -o io/async/.libs/EventBaseManager.o
libtool: compile:  g++ -DHAVE_CONFIG_H -I./.. -pthread -I/usr/include -std=gnu++0x -g -O2 -MT io/async/AsyncSocket.lo -MD -MP -MF io/async/.deps/AsyncSocket.Tpo -c io/async/AsyncSocket.cpp  -fPIC -DPIC -o io/async/.libs/AsyncSocket.o
libtool: compile:  g++ -DHAVE_CONFIG_H -I./.. -pthread -I/usr/include -std=gnu++0x -g -O2 -MT io/async/AsyncTimeout.lo -MD -MP -MF io/async/.deps/AsyncTimeout.Tpo -c io/async/AsyncTimeout.cpp  -fPIC -DPIC -o io/async/.libs/AsyncTimeout.o
libtool: compile:  g++ -DHAVE_CONFIG_H -I./.. -pthread -I/usr/include -std=gnu++0x -g -O2 -MT io/async/AsyncUDPSocket.lo -MD -MP -MF io/async/.deps/AsyncUDPSocket.Tpo -c io/async/AsyncUDPSocket.cpp  -fPIC -DPIC -o io/async/.libs/AsyncUDPSocket.o
libtool: compile:  g++ -DHAVE_CONFIG_H -I./.. -pthread -I/usr/include -std=gnu++0x -g -O2 -MT io/async/AsyncServerSocket.lo -MD -MP -MF io/async/.deps/AsyncServerSocket.Tpo -c io/async/AsyncServerSocket.cpp  -fPIC -DPIC -o io/async/.libs/AsyncServerSocket.o
libtool: compile:  g++ -DHAVE_CONFIG_H -I./.. -pthread -I/usr/include -std=gnu++0x -g -O2 -MT io/async/EventBase.lo -MD -MP -MF io/async/.deps/EventBase.Tpo -c io/async/EventBase.cpp  -fPIC -DPIC -o io/async/.libs/EventBase.o
libtool: compile:  g++ -DHAVE_CONFIG_H -I./.. -pthread -I/usr/include -std=gnu++0x -g -O2 -MT io/async/AsyncSSLSocket.lo -MD -MP -MF io/async/.deps/AsyncSSLSocket.Tpo -c io/async/AsyncSSLSocket.cpp  -fPIC -DPIC -o io/async/.libs/AsyncSSLSocket.o
libtool: link: warning: `-version-info/-version-number' is ignored for convenience libraries
libtool: link: ar cru .libs/libfollybase.a .libs/Conv.o .libs/Demangle.o .libs/EscapeTables.o .libs/Format.o .libs/FormatTables.o .libs/Malloc.o .libs/Range.o .libs/StringBase.o .libs/String.o .libs/Unicode.o 
libtool: link: ranlib .libs/libfollybase.a
libtool: link: ( cd ".libs" && rm -f "libfollybase.la" && ln -s "../libfollybase.la" "libfollybase.la" )
depbase=`echo io/async/EventHandler.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/bash ./libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H   -I./.. -pthread -I/usr/include   -std=gnu++0x -g -O2 -MT io/async/EventHandler.lo -MD -MP -MF $depbase.Tpo -c -o io/async/EventHandler.lo io/async/EventHandler.cpp &&\
mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  g++ -DHAVE_CONFIG_H -I./.. -pthread -I/usr/include -std=gnu++0x -g -O2 -MT io/async/EventHandler.lo -MD -MP -MF io/async/.deps/EventHandler.Tpo -c io/async/EventHandler.cpp  -fPIC -DPIC -o io/async/.libs/EventHandler.o
In file included from ./../folly/io/async/EventHandler.h:24:0,
                 from ./../folly/io/async/AsyncServerSocket.h:20,
                 from io/async/AsyncServerSocket.cpp:21:
./../folly/io/async/EventUtil.h: In static member function 'static bool folly::EventUtil::isEventRegistered(const event*)':
./../folly/io/async/EventUtil.h:38:17: error: 'const struct event' has no member named 'ev_flags'
     return (ev->ev_flags & EVLIST_REGISTERED);
                 ^
In file included from ./../folly/io/async/EventHandler.h:24:0,
                 from io/async/EventHandler.cpp:21:
./../folly/io/async/EventUtil.h: In static member function 'static bool folly::EventUtil::isEventRegistered(const event*)':
./../folly/io/async/EventUtil.h:38:17: error: 'const struct event' has no member named 'ev_flags'
     return (ev->ev_flags & EVLIST_REGISTERED);
                 ^
In file included from io/async/AsyncTimeout.cpp:23:0:
./../folly/io/async/EventUtil.h: In static member function 'static bool folly::EventUtil::isEventRegistered(const event*)':
./../folly/io/async/EventUtil.h:38:17: error: 'const struct event' has no member named 'ev_flags'
     return (ev->ev_flags & EVLIST_REGISTERED);
                 ^
In file included from io/async/AsyncTimeout.cpp:26:0:
io/async/AsyncTimeout.cpp: In static member function 'static void folly::AsyncTimeout::libeventCallback(int, short int, void*)':
io/async/AsyncTimeout.cpp:147:27: error: 'struct event' has no member named 'ev_flags'
   assert((timeout->event_.ev_flags & ~EVLIST_INTERNAL) == EVLIST_INIT);
                           ^
io/async/EventHandler.cpp: In member function 'bool folly::EventHandler::registerImpl(uint16_t, bool)':
io/async/EventHandler.cpp:53:34: error: 'struct event' has no member named 'ev_flags'
         static_cast<bool>(event_.ev_flags & EVLIST_INTERNAL) == internal) {
                                  ^
io/async/EventHandler.cpp:70:12: error: 'struct event' has no member named 'ev_flags'
     event_.ev_flags |= EVLIST_INTERNAL;
            ^
io/async/EventHandler.cpp: In member function 'bool folly::EventHandler::isPending() const':
io/async/EventHandler.cpp:171:14: error: 'const struct event' has no member named 'ev_flags'
   if (event_.ev_flags & EVLIST_ACTIVE) {
              ^
In file included from ./../folly/io/async/EventHandler.h:24:0,
                 from ./../folly/io/async/NotificationQueue.h:23,
                 from io/async/EventBase.cpp:24:
./../folly/io/async/EventUtil.h: In static member function 'static bool folly::EventUtil::isEventRegistered(const event*)':
./../folly/io/async/EventUtil.h:38:17: error: 'const struct event' has no member named 'ev_flags'
     return (ev->ev_flags & EVLIST_REGISTERED);
                 ^
io/async/EventBase.cpp: In member function 'virtual void folly::EventBase::attachTimeoutManager(folly::AsyncTimeout*, folly::TimeoutManager::InternalEnum)':
io/async/EventBase.cpp:777:9: error: 'struct event' has no member named 'ev_flags'
     ev->ev_flags |= EVLIST_INTERNAL;
         ^
Makefile:1381: recipe for target 'io/async/AsyncTimeout.lo' failed
make[2]: *** [io/async/AsyncTimeout.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
Makefile:1381: recipe for target 'io/async/EventHandler.lo' failed
make[2]: *** [io/async/EventHandler.lo] Error 1
In file included from ./../folly/io/async/EventHandler.h:24:0,
                 from ./../folly/io/async/AsyncSocket.h:28,
                 from io/async/AsyncSocket.cpp:17:
./../folly/io/async/EventUtil.h: In static member function 'static bool folly::EventUtil::isEventRegistered(const event*)':
./../folly/io/async/EventUtil.h:38:17: error: 'const struct event' has no member named 'ev_flags'
     return (ev->ev_flags & EVLIST_REGISTERED);
                 ^
Makefile:1381: recipe for target 'io/async/EventBase.lo' failed
make[2]: *** [io/async/EventBase.lo] Error 1
In file included from ./../folly/io/async/EventHandler.h:24:0,
                 from ./../folly/io/async/AsyncUDPSocket.h:23,
                 from io/async/AsyncUDPSocket.cpp:17:
./../folly/io/async/EventUtil.h: In static member function 'static bool folly::EventUtil::isEventRegistered(const event*)':
./../folly/io/async/EventUtil.h:38:17: error: 'const struct event' has no member named 'ev_flags'
     return (ev->ev_flags & EVLIST_REGISTERED);
                 ^
Makefile:1381: recipe for target 'io/async/AsyncServerSocket.lo' failed
make[2]: *** [io/async/AsyncServerSocket.lo] Error 1
In file included from ./../folly/io/async/EventHandler.h:24:0,
                 from ./../folly/io/async/AsyncSocket.h:28,
                 from ./../folly/io/async/AsyncSSLSocket.h:25,
                 from io/async/AsyncSSLSocket.cpp:17:
./../folly/io/async/EventUtil.h: In static member function 'static bool folly::EventUtil::isEventRegistered(const event*)':
./../folly/io/async/EventUtil.h:38:17: error: 'const struct event' has no member named 'ev_flags'
     return (ev->ev_flags & EVLIST_REGISTERED);
                 ^
Makefile:1381: recipe for target 'io/async/AsyncSocket.lo' failed
make[2]: *** [io/async/AsyncSocket.lo] Error 1
Makefile:1381: recipe for target 'io/async/AsyncUDPSocket.lo' failed
make[2]: *** [io/async/AsyncUDPSocket.lo] Error 1
libtool: compile:  g++ -DHAVE_CONFIG_H -I./.. -pthread -I/usr/include -std=gnu++0x -g -O2 -MT io/async/EventBaseManager.lo -MD -MP -MF io/async/.deps/EventBaseManager.Tpo -c io/async/EventBaseManager.cpp -o io/async/EventBaseManager.o >/dev/null 2>&1
Makefile:1381: recipe for target 'io/async/AsyncSSLSocket.lo' failed
make[2]: *** [io/async/AsyncSSLSocket.lo] Error 1
make[2]: Leaving directory '/home/james/proxygen/proxygen/folly/folly'
Makefile:1442: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/james/proxygen/proxygen/folly/folly'
Makefile:898: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by bugok** [comment]
Hi @js7222, thanks for reporting this.
Sorry it took a while to get back to you.
I think this is a compatibility issue with folly and Ubuntu 15.04. 
Can you please try and build folly, without proxygen? 
See https://github.com/facebook/folly

If this fails - we'll open an issue with folly.
cc: @sgolemon

**Comment by js7222** [comment]
Same with folly

make  all-recursive
make[1]: Entering directory '/home/james/folly/folly'
Making all in .
make[2]: Entering directory '/home/james/folly/folly'
/bin/bash ./libtool  --tag=CXX   --mode=link g++  -std=gnu++0x -g -O2 -lboost_context -lboost_thread -lboost_filesystem -lboost_system -lboost_regex -lpthread  -o generate_fingerprint_tables build/GenerateFingerprintTables.o libfollybase.la -llzma -lz -lsnappy -llz4 -liberty -ljemalloc -levent -ldouble-conversion -lssl -lgflags -lglog 
depbase=`echo io/async/AsyncTimeout.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/bash ./libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H   -I./.. -pthread -I/usr/include   -std=gnu++0x -g -O2 -MT io/async/AsyncTimeout.lo -MD -MP -MF $depbase.Tpo -c -o io/async/AsyncTimeout.lo io/async/AsyncTimeout.cpp &&\
mv -f $depbase.Tpo $depbase.Plo
depbase=`echo io/async/AsyncUDPSocket.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/bash ./libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H   -I./.. -pthread -I/usr/include   -std=gnu++0x -g -O2 -MT io/async/AsyncUDPSocket.lo -MD -MP -MF $depbase.Tpo -c -o io/async/AsyncUDPSocket.lo io/async/AsyncUDPSocket.cpp &&\
mv -f $depbase.Tpo $depbase.Plo
depbase=`echo io/async/AsyncServerSocket.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/bash ./libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H   -I./.. -pthread -I/usr/include   -std=gnu++0x -g -O2 -MT io/async/AsyncServerSocket.lo -MD -MP -MF $depbase.Tpo -c -o io/async/AsyncServerSocket.lo io/async/AsyncServerSocket.cpp &&\
mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  g++ -DHAVE_CONFIG_H -I./.. -pthread -I/usr/include -std=gnu++0x -g -O2 -MT io/async/AsyncTimeout.lo -MD -MP -MF io/async/.deps/AsyncTimeout.Tpo -c io/async/AsyncTimeout.cpp  -fPIC -DPIC -o io/async/.libs/AsyncTimeout.o
libtool: compile:  g++ -DHAVE_CONFIG_H -I./.. -pthread -I/usr/include -std=gnu++0x -g -O2 -MT io/async/AsyncUDPSocket.lo -MD -MP -MF io/async/.deps/AsyncUDPSocket.Tpo -c io/async/AsyncUDPSocket.cpp  -fPIC -DPIC -o io/async/.libs/AsyncUDPSocket.o
libtool: compile:  g++ -DHAVE_CONFIG_H -I./.. -pthread -I/usr/include -std=gnu++0x -g -O2 -MT io/async/AsyncServerSocket.lo -MD -MP -MF io/async/.deps/AsyncServerSocket.Tpo -c io/async/AsyncServerSocket.cpp  -fPIC -DPIC -o io/async/.libs/AsyncServerSocket.o
libtool: link: g++ -std=gnu++0x -g -O2 -o generate_fingerprint_tables build/GenerateFingerprintTables.o  ./.libs/libfollybase.a -lboost_context -lboost_thread -lboost_filesystem -lboost_system -lboost_regex -lpthread -llzma -lz -lsnappy -llz4 -liberty -ljemalloc -levent -ldouble-conversion -lssl -lgflags -lglog
depbase=`echo io/async/AsyncSignalHandler.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/bash ./libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H   -I./.. -pthread -I/usr/include   -std=gnu++0x -g -O2 -MT io/async/AsyncSignalHandler.lo -MD -MP -MF $depbase.Tpo -c -o io/async/AsyncSignalHandler.lo io/async/AsyncSignalHandler.cpp &&\
mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  g++ -DHAVE_CONFIG_H -I./.. -pthread -I/usr/include -std=gnu++0x -g -O2 -MT io/async/AsyncSignalHandler.lo -MD -MP -MF io/async/.deps/AsyncSignalHandler.Tpo -c io/async/AsyncSignalHandler.cpp  -fPIC -DPIC -o io/async/.libs/AsyncSignalHandler.o
In file included from ./../folly/io/async/EventHandler.h:24:0,
                 from ./../folly/io/async/AsyncServerSocket.h:20,
                 from io/async/AsyncServerSocket.cpp:21:
./../folly/io/async/EventUtil.h: In static member function 'static bool folly::EventUtil::isEventRegistered(const event*)':
./../folly/io/async/EventUtil.h:38:17: error: 'const struct event' has no member named 'ev_flags'
     return (ev->ev_flags & EVLIST_REGISTERED);
                 ^
In file included from io/async/AsyncTimeout.cpp:23:0:
./../folly/io/async/EventUtil.h: In static member function 'static bool folly::EventUtil::isEventRegistered(const event*)':
./../folly/io/async/EventUtil.h:38:17: error: 'const struct event' has no member named 'ev_flags'
     return (ev->ev_flags & EVLIST_REGISTERED);
                 ^
In file included from io/async/AsyncTimeout.cpp:26:0:
io/async/AsyncTimeout.cpp: In static member function 'static void folly::AsyncTimeout::libeventCallback(int, short int, void*)':
io/async/AsyncTimeout.cpp:147:27: error: 'struct event' has no member named 'ev_flags'
   assert((timeout->event_.ev_flags & ~EVLIST_INTERNAL) == EVLIST_INIT);
                           ^
In file included from ./../folly/io/async/EventHandler.h:24:0,
                 from ./../folly/io/async/AsyncUDPSocket.h:23,
                 from io/async/AsyncUDPSocket.cpp:17:
./../folly/io/async/EventUtil.h: In static member function 'static bool folly::EventUtil::isEventRegistered(const event*)':
./../folly/io/async/EventUtil.h:38:17: error: 'const struct event' has no member named 'ev_flags'
     return (ev->ev_flags & EVLIST_REGISTERED);
                 ^
Makefile:1199: recipe for target 'io/async/AsyncTimeout.lo' failed
make[2]: *** [io/async/AsyncTimeout.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
Makefile:1199: recipe for target 'io/async/AsyncUDPSocket.lo' failed
make[2]: *** [io/async/AsyncUDPSocket.lo] Error 1
libtool: compile:  g++ -DHAVE_CONFIG_H -I./.. -pthread -I/usr/include -std=gnu++0x -g -O2 -MT io/async/AsyncSignalHandler.lo -MD -MP -MF io/async/.deps/AsyncSignalHandler.Tpo -c io/async/AsyncSignalHandler.cpp -o io/async/AsyncSignalHandler.o >/dev/null 2>&1
Makefile:1199: recipe for target 'io/async/AsyncServerSocket.lo' failed
make[2]: *** [io/async/AsyncServerSocket.lo] Error 1
make[2]: Leaving directory '/home/james/folly/folly'
Makefile:1256: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/james/folly/folly'
Makefile:796: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by bugok** [comment]
Since this is an issue with folly and we are dependent in folly, could you please open an issue with the folly project?

**Comment by js7222** [comment]
I've managed to get folly working on a different machine with Ubuntu 15.04. I suspect this might be the version of boost that I'm using. I will check later

**Comment by oneOfThePeople** [comment]
you find what was the problem?
