### ISSUE TITLE
Connection Close Reason SHUTDOWN

### ISSUE THREAD

**Issue by mikekliger** [facebook/proxygen#484]
I am seeing this close reason bubbling up from proxygen. It seems like it can come from a few places. Is it possible to provide information on possible examples of the root cause of this reason?

**Comment by SteveSelva** [comment]
Connection Close Reason: Shutdown refers to closing the connection since the peer's connection has been closed, so its forced to shutdown. 

The Peer's connection may be closed due to EOF or Error.

**Comment by mikekliger** [comment]
Is there any way to glean more info about the Error? These are supposed to be persistent connections and I would think EOF would not trigger closing.

**Comment by SteveSelva** [comment]
Try running the application with verbose 4 for detailed logs, "-v 4".
