### ISSUE TITLE
proxygen fails to build when a newer glog package is installed

### ISSUE THREAD

**Issue by jmccl** [facebook/proxygen#488]
```
from /home/john/third-party/proxygen/proxygen/_build/deps/folly/folly/CancellationToken.cpp:17:
/usr/include/glog/logging.h:60:4: error: #error <glog/logging.h> was not included correctly. See the documention for how to consume the library.
   60 | #  error <glog/logging.h> was not included correctly. See the documention for how to consume the library.
      |    ^~~~~
In file included from /usr/include/glog/logging.h:63:
```

It seems basically due to this.

https://github.com/facebook/folly/issues/2149, which references the glog commit.

Having said that, my assumption is something in proxygen likely will need to change as well.

**Comment by afrind** [comment]
Since this seems to be a folly problem first, closing this out. The folly issues mention an AUR patch that can get you past it.  If you end up stuck with folly building but proxygen blocked, please reopen or file a new issue.
