### ISSUE TITLE
Remove the use of requiring sudo for installing deps

### ISSUE THREAD

**Issue by jkammerland** [facebook/proxygen#497]
Use a packagemanager or some other method

**Comment by lnicco** [comment]
@jkammerland do you have a more specific recommendation? If you can post a PR we can discuss there

**Comment by jbeshay** [comment]
@jkammerland, You're probably using the ./build.sh script. The best way to avoid sudo right now is to use `--no-install-dependencies` and handle that manually outside of the script.

**Comment by jkammerland** [comment]
Alright thanks @jbeshay, I'm closing this in favor of #496. @lnicco Sounds good! But I will have to learn abit more here and see, I mentioned in #496 that I tried to use vcpkg for proxygen, was unsuccessful. I'm not suggesting to adopt vcpkg for the whole buildsystem, but just an idea.
