### ISSUE TITLE
HTTP Parsing Issue

### ISSUE THREAD

**Issue by SteveSelva** [facebook/proxygen#507]
I came up with an issue of parsing data in Proxygen. I have created a HTTPDownstreamSession after a handshake. When the Session starts, it will read for data and then parses it and calls the callback functions accordingly. This works fine when the received data is a valid HTTP Protocol. When the received data is not HTTP data, instead of throwing Parsing error, it is calling onMessageBegin() callback function of the SessionInfoCallback. Why don't you check whether the data received is a valid data before calling onMessageBegin()?

**Comment by afrind** [comment]
The timing of an onMessageBegin is dependent on the codec used.  I believe H1 and H3 will give the callback on the first byte received, and H2 will delay until it has parsed a frame it can identify as the beginning of a message.  The design goes back to the underlying H1 parser we chose (originally from node.js), which behaves this way.

Is it causing a problem?

**Comment by afrind** [comment]
Can you explain the actual problem?  You will eventually get an error after the codec parses a bit farther.

**Comment by afrind** [comment]
>  I need some more data, which is sent through the same socket, which is not HTTP data.

This sounds like a strange use case for HTTP.  You can use HTTP upgrade to convert an HTTP/1.1 socket into a stream of bytes accessible to your application, but only after sending a 101-Switching Protocols or 200 response with the upgrade header.  If you are still waiting for the response to the first request, I don't think proxygen can look at the next bytes coming on the wire without treating them as HTTP.

**Comment by afrind** [comment]
Perhaps, but probably not on an urgent timescale.  Our implementations have diverged over time and it would take us a while to do the merge and ensure that the upgrade doesn't break anything that depends on proxygen.

**Comment by afrind** [comment]
I pinged the diff internally.  Looks like someone wanted to tweak it slightly but it may have gotten lost in the shuffle.
