### ISSUE TITLE
VCPKG proxygen client site library

### ISSUE THREAD

**Issue by EgyipTomi425** [facebook/proxygen#522]
Hi!
I'd like to compile the sample hq library from httpserver.
The error says #include <proxygen/httpclient/samples/curl/CurlClient.h> not exist.

I looked up from VCPKG installed folders and here what I found:

```
kecyke@Kecyke-Laptop-D:~/vcpkg/installed/x64-linux/include/proxygen$ ls
external  httpserver  lib
```
There is no the httpclient libraries. Where is it? Or how can I download it? Help me please.

**Comment by afrind** [comment]
This comes from here: https://github.com/facebook/proxygen/blob/main/proxygen/httpclient/samples/curl/CurlClient.h

This file: https://github.com/facebook/proxygen/blob/main/proxygen/httpclient/samples/curl/CMakeLists.txt may be missing something like is present in lib/CMakeList.txt

https://github.com/facebook/proxygen/blob/main/proxygen/lib/CMakeLists.txt#L260-L278
