### ISSUE TITLE
The use of __attribute__((__constructor__))

### ISSUE THREAD

**Issue by Orvid** [facebook/proxygen#58]
Is there a specific reason that `__attribute__((__constructor__))` is used rather than a dynamic initializer like:
```C++
static struct Example {
Example() { /* Do some assembly construction logic here */ }
} s_example;
```
I ask because, although I can provide the same thing with MSVC, it's not exactly pretty, and it would be much cleaner to switch to initializers.

**Comment by bugok** [comment]
Thanks for reporting @Orvid.
Are you referring to a specific location? I see this happening in several places in the code.
For example: https://github.com/facebook/proxygen/blob/master/proxygen/lib/http/HTTPMethod.cpp#L27

In this example - I believe that it's to make sure that this structure is available when `main()` is called.

**Comment by Orvid** [comment]
It's just a general question, regarding all uses of the attribute.

**Comment by afrind** [comment]
I think we're trying to move away from static initializers with non-trivial destructors because destruction order is difficult to reason about.

**Comment by russoue** [comment]
@Orvid, can we close this issue?

**Comment by russoue** [comment]
@Orvid, it seems that we have another issue opened for this: https://github.com/facebook/proxygen/pull/66, can you please close this one?

**Comment by Orvid** [comment]
Yep.
