### ISSUE TITLE
deps.sh needs to pull in unzip

### ISSUE THREAD

**Issue by emyr666** [facebook/proxygen#61]
Just tried to do a build on a fresh minimal install of ubuntu server. ./deps.sh failed on unzipping gmock.zip as zip was not installed. Need an apt-get install unzip in your deps.sh somewhere.

**Comment by bugok** [comment]
@emyr666: What version of Ubuntu were you running?

**Comment by bugok** [comment]
@emyr666: Is this is a problem? What version are you running?

**Comment by leizha** [comment]
this happened to me as well. i was running Ubuntu 14.04.3 LTS from standard docker image.

**Comment by bugok** [comment]
@leizha: Would you like to send a pull request?
