### ISSUE TITLE
deps.sh meet compile error in Ubuntu 14.10

### ISSUE THREAD

**Issue by xiaomi-tc** [facebook/proxygen#62]
##  at  folly/folly/io/async/EventBase.cpp
_Error message:_

depbase=`echo io/async/EventBase.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/bash ./libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H   -I./.. -pthread -I/usr/include   -std=gnu++0x -g -O2 -MT io/async/EventBase.lo -MD -MP -MF $depbase.Tpo -c -o io/async/EventBase.lo io/async/EventBase.cpp &&\
mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  g++ -DHAVE_CONFIG_H -I./.. -pthread -I/usr/include -std=gnu++0x -g -O2 -MT io/async/EventBase.lo -MD -MP -MF io/async/.deps/EventBase.Tpo -c **io/async/EventBase.cpp**  -fPIC -DPIC -o io/async/.libs/EventBase.o
```
io/async/EventBase.cpp: In member function 'virtual void folly::EventBase::FunctionRunner::messageAvailable(std::pair<void (*)(void*), void*>&&)':
io/async/EventBase.cpp:77:46:  error: 'event_base_loopbreak' was not declared in this scope
     **event_base_loopbreak(getEventBase()->evb_);**
                                              ^
```
io/async/EventBase.cpp: In constructor 'folly::EventBase::EventBase(bool)':
io/async/EventBase.cpp:170:10: error: invalid conversion from 'void*' to 'event_base*' [-fpermissive]
     evb_ = (ev.ev_base) ? event_base_new() : event_init();
          ^
io/async/EventBase.cpp: In member function 'void folly::EventBase::terminateLoopSoon()':
io/async/EventBase.cpp:477:28: error: 'event_base_loopbreak' was not declared in this scope
   event_base_loopbreak(evb_);
                            ^
Makefile:1241: recipe for target 'io/async/EventBase.lo' failed
make[2]: *** [io/async/EventBase.lo] Error 1
make[2]: Leaving directory '/root/software/proxygen/proxygen/folly/folly'
Makefile:1298: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/root/software/proxygen/proxygen/folly/folly'
Makefile:822: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by bugok** [comment]
@xiaomi-tc: I think this might be related to unsynced code. Can you please try again? I pushed our latest branch yesterday.

**Comment by xiaomi-tc** [comment]
I had a retry , but the same error

libtool: compile:  g++ -DHAVE_CONFIG_H -I./.. -pthread -I/usr/include -std=gnu++0x -g -O2 -MT io/async/AsyncSSLSocket.lo -MD -MP -MF io/async/.deps/AsyncSSLSocket.Tpo -c io/async/AsyncSSLSocket.cpp -o io/async/AsyncSSLSocket.o >/dev/null 2>&1
```
io/async/EventBase.cpp: In member function 'virtual void folly::EventBase::FunctionRunner::messageAvailable(std::pair<void (*)(void*), void*>&&)':
io/async/EventBase.cpp:77:46: error: 'event_base_loopbreak'  **was not declared in this scope**
     **event_base_loopbreak(getEventBase()->evb_);**
                                              ^
```
io/async/EventBase.cpp: In constructor 'folly::EventBase::EventBase(bool)':
io/async/EventBase.cpp:170:10: error: invalid conversion from 'void*' to 'event_base*' [-fpermissive]
     evb_ = (ev.ev_base) ? event_base_new() : event_init();
          ^
io/async/EventBase.cpp: In member function 'void folly::EventBase::terminateLoopSoon()':
io/async/EventBase.cpp:477:28: error: 'event_base_loopbreak' was not declared in this scope
   event_base_loopbreak(evb_);

**Comment by QiMata** [comment]
I am getting the same thing with Ubuntu 14.04. Even with the update.

**Comment by afrind** [comment]
What version of libevent do you have on your system?

**Comment by QiMata** [comment]
thinking this is what you want
||/ Name           Version      Architecture Description
+++-==============-============-============-=================================
ii  libevent-2.0-5 2.0.21-stabl amd64        Asynchronous event notification l
ii  libevent-core- 2.0.21-stabl amd64        Asynchronous event notification l
ii  libevent-dev   2.0.21-stabl amd64        Asynchronous event notification l
ii  libevent-extra 2.0.21-stabl amd64        Asynchronous event notification l
ii  libevent-opens 2.0.21-stabl amd64        Asynchronous event notification l
ii  libevent-pthre 2.0.21-stabl amd64        Asynchronous event notification l

**Comment by afrind** [comment]
@QiMata : your error is actually different (nothing about event_base_loopbreak).  Looks like the folly rev is behind where it should be.  Try setting it to v0.55.0.  I will update it when I push this week, not sure how it didn't get updated with any previous push in the last month.

**Comment by QiMata** [comment]
@afrind It works but you also have to update the wangle version to 0.13.0 as well

**Comment by afrind** [comment]
@QiMata : I just pushed, so HEAD should be good now.  I also updated our push procedure so it shouldn't get missed again.  Feel free to reopen if it's not working.

**Comment by QiMata** [comment]
Fresh install with the same commands, new error

libtool: compile:  g++ -DHAVE_CONFIG_H -I./.. -pthread -I/usr/include -std=gnu++0x -g -O2 -MT Random.lo -MD -MP -MF .deps/Random.Tpo -c Random.cpp -o Random.o >/dev/null 2>&1
libtool: compile:  g++ -DHAVE_CONFIG_H -I./.. -pthread -I/usr/include -std=gnu++0x -g -O2 -MT MemoryMapping.lo -MD -MP -MF .deps/MemoryMapping.Tpo -c MemoryMapping.cpp -o MemoryMapping.o >/dev/null 2>&1
make[2]: Leaving directory `/home/parallels/Documents/Libraries/proxygen/proxygen/folly/folly'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/parallels/Documents/Libraries/proxygen/proxygen/folly/folly'
make: *** [all] Error 2
