### ISSUE TITLE
HTTP2 Support

### ISSUE THREAD

**Issue by steelbrain** [facebook/proxygen#63]
Tracking bug for HTTP2. Post on here when there's a progress.

**Comment by bugok** [comment]
@steelbrain - what bug are you referring to?

**Comment by steelbrain** [comment]
@bugok It's just that we haven't seen **any** thing or signal or progress on HTTP2 support in proxygen, just a note in a article in fb engineering which says it's `In Progress`™. so I thought I'd help you guys by creating a bug where you can post the progress :smiley:

**Comment by bugok** [comment]
@steelbrain what about this:
https://github.com/facebook/proxygen/tree/master/proxygen/lib/http/codec/experimental ?

**Comment by steelbrain** [comment]
Now that's some progress :clap:

**Comment by bugok** [comment]
Please track this folder. We're currently in testing mode for http2. When the code moved out of here - that means we've pushed it completely to production.

**Comment by afrind** [comment]
Please feel free to give http/2 a try and let us know if you find any issues.  I think HTTP2Codec is pretty mature and we'll be moving it out of /experimental/ soon.

**Comment by steelbrain** [comment]
I don't use proxygen directly, I use proxygen + hhvm so no idea how to build/use experimental features with it :stuck_out_tongue:

**Comment by afrind** [comment]
The code is compiled in by default.  You can configure HHVM to advertise HTTP/2 by adding this block to the Server section in a .hdf file:

  SSLNextProtocols {
     * = h2-14
     * = spdy/3.1
     * = http/1.1
  }

I know HHVM uses .ini format externally but I don't know the exact syntax.  This is just an array of strings under Server.SSLNextProtocols

**Comment by steelbrain** [comment]
Thanks :clap:
