### ISSUE TITLE
SSL  errors

### ISSUE THREAD

**Issue by smellyfis** [facebook/proxygen#65]
proxygen: fe1070ff19b447430c346100d45330adecb7e8c0
wangle: e15b84fd02ba8135927d54e8e586e6d8cc275f96
folly: 47f0d3846c949a085da9dc3e33062b4537172edb

When I modified the sample echo server to except ssl  i get the following:
>F1028 12:32:43.463060  5326 Acceptor.cpp:74] Check failed: sslCtxManager_->>getDefaultSSLCtx() 
>*** Check failure stack trace: ***
>    @     0x7f886d763d9d  (unknown)
>    @     0x7f886d765c50  (unknown)
>    @     0x7f886d763972  (unknown)
>    @     0x7f886d76666e  (unknown)
>    @     0x7f886e13a664  wangle::Acceptor::init()
>    @     0x7f886e0b9783  proxygen::HTTPAcceptor::init()
>    @     0x7f886e0b7336  proxygen::AcceptorFactory::newAcceptor()
>    @     0x7f886e150d20  wangle::ServerWorkerPool::threadStarted()
>    @     0x7f886e15270e  wangle::ServerWorkerPool::threadPreviouslyStarted()
>    @     0x7f886e160cf5  wangle::ThreadPoolExecutor::addObserver()
>    @     0x7f886e0b257e  wangle::ServerBootstrap<>::group()
>    @     0x7f886e0a32af  proxygen::HTTPServer::start()
>    @           0x4195f6  _ZZ4mainENKUlvE_clEv
>    @           0x41afc6  >_ZNSt12_Bind_simpleIFZ4mainEUlvE_vEE9_M_invokeIIEEEvSt12_Index_tupleIIXspT_EEE
>    @           0x41aef8  _ZNSt12_Bind_simpleIFZ4mainEUlvE_vEEclEv
>    @           0x41ae66  _ZNSt6thread5_ImplISt12_Bind_simpleIFZ4mainEUlvE_vEEE6_M_runEv
>    @     0x7f886d0abc00  (unknown)
>    @     0x7f886c8c7444  (unknown)
>    @     0x7f886c60d36d  (unknown)
>Aborted

here is what I did to the echo server:
```C++
  std::vector<HTTPServer::IPConfig> IPs;
  IPs.push_back(HTTPServer::IPConfig(SocketAddress(FLAGS_ip, FLAGS_http_port, true), Protocol::HTTP));
  IPs.push_back(HTTPServer::IPConfig(SocketAddress(FLAGS_ip, FLAGS_spdy_port, true), Protocol::SPDY));
  HTTPServer::IPConfig http2Test(SocketAddress(FLAGS_ip, FLAGS_spdy_port, true), Protocol::HTTP2);
  SSLContextConfig sslCC;
  sslCC.setCertificate("server.crt", "server.key","server.csr");
  http2Test.sslConfigs.push_back(sslCC);
  IPs.push_back(http2Test);
```
and this is what i used to create the certificate key and password
>openssl genrsa -out server.key 1024
>openssl req -new -key server.key -out server.csr
>openssl x509 -req -days 366 -in server.csr -signkey server.key -out server.crt

is this a bug or am I doing it wrong?

**Comment by afrind** [comment]
Check the HTTPServerTests.cpp file, it also sets sslCtx.isDefault = true which I suspect will solve this issue.  Please reopen if it's not working.

**Comment by smellyfis** [comment]
Thank you very much!
