### ISSUE TITLE
Run curl/echo sample ERROR

### ISSUE THREAD

**Issue by wqx081** [facebook/proxygen#71]
ubuntu 14.04 / gcc-4.9
when run httpclient/samples/curl Or httpserver/samples/echo,  OUTPUT:

curl: ./../folly/io/async/NotificationQueue.h:749: void folly::NotificationQueue<MessageT>::Consumer::init(folly::EventBase*, folly::NotificationQueue<MessageT>*) [with MessageT = std::pair<void (*)(void*), void*>]: Assertion `!isHandlerRegistered()' failed.
*** Aborted at 1450194832 (unix time) try "date -d @1450194832" if you are using GNU date ***
PC: @     0x7f0770125cc9 (unknown)
*** SIGABRT (@0xc9e) received by PID 3230 (TID 0x7f0771c59880) from PID 3230; stack trace: ***
    @     0x7f0771422340 (unknown)
    @     0x7f0770125cc9 (unknown)
    @     0x7f07701290d8 (unknown)
    @     0x7f077011eb86 (unknown)
    @     0x7f077011ec32 (unknown)
    @     0x7f07710659d1 folly::NotificationQueue<>::Consumer::init()
    @     0x7f07710619dd folly::EventBase::initNotificationQueue()
    @     0x7f07710625e5 folly::EventBase::EventBase()
    @           0x40ea2b main
    @     0x7f0770110ec5 (unknown)
    @           0x410727 (unknown)
    @                0x0 (unknown)
Aborted (core dumped)

**Comment by xiaosophiawang** [comment]
Hi @wqx081 , can you post detailed steps to repro? I'm not able to repro this error here.
