### ISSUE TITLE
SPDYCodecTest.HeaderWithManyValues test fails on Ubuntu > 14

### ISSUE THREAD

**Issue by js7222** [facebook/proxygen#74]
...
[ RUN      ] SPDYCodecTest.HeaderWithManyValues
SPDYCodecTest.cpp:538: Failure
Value of: 1
Expected: callbacks.headersComplete
Which is: 0
SPDYCodecTest.cpp:540: Failure
Value of: 0
Expected: callbacks.streamErrors
Which is: 1
F1226 18:08:32.613636 22638 SPDYCodecTest.cpp:542] Check failed: 'callbacks.msg.get()' Must be non NULL 
**\* Check failure stack trace: ***
    @     0x7fd80b3f45cd  google::LogMessage::Fail()
    @     0x7fd80b3f6433  google::LogMessage::SendToLog()
    @     0x7fd80b3f415b  google::LogMessage::Flush()
    @     0x7fd80b3f6e1e  google::LogMessageFatal::~LogMessageFatal()
    @           0x45639e  SPDYCodecTest_HeaderWithManyValues_Test::TestBody()
    @           0x4f9613  testing::internal::HandleExceptionsInMethodIfSupported<>()
    @           0x4f1e0a  testing::Test::Run()
    @           0x4f1f58  testing::TestInfo::Run()
    @           0x4f2035  testing::TestCase::Run()
    @           0x4f22ff  testing::internal::UnitTestImpl::RunAllTests()
    @           0x4f9af3  testing::internal::HandleExceptionsInMethodIfSupported<>()
    @           0x4f2624  testing::UnitTest::Run()
    @           0x40f1d1  main
    @     0x7fd80a881a40  __libc_start_main
    @           0x40f689  _start
    @              (nil)  (unknown)
FAIL CodecTests (exit status: 134)
...

**Comment by w-o-o** [comment]
@js7222 , I cannot reproduce your problem in my dev server.  I am happy to investigate this further if you can provide more details about how to reproduce this.  

proxygen/lib/http/codec/test/CodecTests --gtest_filter=SPDYCodecTest.HeaderWithManyValues -v 4
Note: Google Test filter = SPDYCodecTest.HeaderWithManyValues
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from SPDYCodecTest
[ RUN      ] SPDYCodecTest.HeaderWithManyValues
V1228 13:45:14.245183 3819173 SPDYCodec.cpp:196] creating SPDY/3.0 codec
V1228 13:45:14.245311 3819173 SPDYCodec.cpp:196] creating SPDY/3.0 codec
V1228 13:45:14.247814 3819173 SPDYCodec.cpp:534] Dropping SPDY reserved header Host
V1228 13:45:14.249593 3819173 GzipHeaderCodec.cpp:280] header size orig=9032, max deflated=10314, actual deflated=9134
V1228 13:45:14.249876 3819173 SPDYCodec.cpp:1208] Got SYN_STREAM, stream=1 pri=0
[       OK ] SPDYCodecTest.HeaderWithManyValues (6 ms)
[----------] 1 test from SPDYCodecTest (6 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (6 ms total)
[  PASSED  ] 1 test.

**Comment by js7222** [comment]
I literally just ran ./deps.sh && ./reinstall.sh as per the instructions. I am using Ubuntu 15.10. Is there anything specific you would like me to provide?

**Comment by kwlo** [comment]
I got the same error messages as js7222 as well. Didn't modify anything. Just git cloned and ./deps.sh.
Ubuntu 15.10

**Comment by kwlo** [comment]
It seems this issue is caused by Ubuntu 15.10. I am able to build successfully with 14.04

**Comment by w-o-o** [comment]
@kwlo thanks for feedback.  Current our internal testing environment is 14.04.  Let's try to get a 15.10 to reproduce it.  

meanwhile, welcome to send us a pull request if you figure out the fix.

**Comment by byronhe** [comment]
reproduced by Ubuntu 15.10, X86_64.

did some debug , looks like

this test case failed:

        TEST(SPDYCodecTest, HeaderWithManyValues) 

https://github.com/facebook/proxygen/blob/master/proxygen/lib/http/codec/test/SPDYCodecTest.cpp#L517

the reason is call SPDYUtil::validateHeaderValue() failed, 
name is "host" 
value is   '\001' <repeats 11 times>

        valueOk = SPDYUtil::validateHeaderValue(value, SPDYUtil::STRICT);

https://github.com/facebook/proxygen/blob/master/proxygen/lib/http/codec/SPDYCodec.cpp#L1044

              if (*p < 0x20 || *p == 0x7f) {
                // unexpected ctl per rfc2616
                return false;
              }

https://github.com/facebook/proxygen/blob/master/proxygen/lib/http/codec/SPDYUtil.h#L104

**Comment by nitingupta910** [comment]
I get exactly the same failure on Ubuntu 16.04 (alpha).

**Comment by afrind** [comment]
I've created a task internally to add support to these newer ubuntu revs, but it might take a while to get to them.  Would gladly accept a PR :)

**Comment by afrind** [comment]
I just built a new Ubuntu 16.04 VM and ran deps.sh && resinstall.sh from HEAD and it worked.  I even ran the SPDYCodecTests with a CPU intensive job in the background to see if CPU load affected it.  I built with gcc-5.4.

Given the comment from @byronhe I wonder if it might be somehow locale dependent?  Can folks post if they are still seeing this on recent ubuntu?

**Comment by afrind** [comment]
Old issue, cannot repro.
