### ISSUE TITLE
Cannot build echo server (ubuntu 14.04)

### ISSUE THREAD

**Issue by shivamsingh262** [facebook/proxygen#75]
This is same as #73
shivam@shivam-PC:~/proxygen/proxygen/httpserver/samples/echo$ g++ -std=c++11 -o my_echo EchoServer.cpp EchoHandler.cpp -lproxygenhttpserver -lfolly -lglog -lgflags -pthread
EchoServer.cpp:14:44: fatal error: proxygen/httpserver/HTTPServer.h: No such file or directory
 #include <proxygen/httpserver/HTTPServer.h>
                                            ^
compilation terminated.
In file included from EchoHandler.cpp:10:0:
EchoHandler.h:13:48: fatal error: proxygen/httpserver/RequestHandler.h: No such file or directory
 #include <proxygen/httpserver/RequestHandler.h>
                                                ^
compilation terminated.

Got this after running ./deps.sh && ./reinstall.sh

**Comment by viswanathgs** [comment]
Looks like https://github.com/facebook/proxygen/issues/73 has been fixed. Can you follow the steps there to get a clean build with the latest wangle and folly deps?

**Comment by russoue** [comment]
I tried to reproduce it on Ubuntu 14.04 but the build went fine. I also checked that both the files exist there. Can you please try @viswanathgs's suggestion above and get back to us?

**Comment by shivamsingh262** [comment]
Had a error with cmake while building wangle deps
"....local/lib/libcurl.so.4: no version information available (required by cmake)"

so tried
$ export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/mesa/libGL.so.1

ran ./deps.sh and ./reinstall.sh again.
This time, I am able to build echo server without any issues.
