### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by akashtalole** [facebook/proxygen#76]
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.8/README.Bugs> for instructions.
make[2]: *** [CMakeFiles/BootstrapTest.dir/bootstrap/BootstrapTest.cpp.o] Error 4
make[1]: *** [CMakeFiles/BootstrapTest.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
Linking CXX executable bin/PeekingAcceptorHandshakeHelperTest
Linking CXX executable bin/OutputBufferingHandlerTest
[ 91%] Built target CodecTest
[ 91%] [ 91%] Built target PeekingAcceptorHandshakeHelperTest
Built target OutputBufferingHandlerTest
Linking CXX executable bin/AsyncSocketHandlerTest
[ 91%] Built target AsyncSocketHandlerTest
Linking CXX executable bin/ObservingHandlerTest
[ 91%] Built target ObservingHandlerTest
Linking CXX executable bin/BroadcastHandlerTest
[ 91%] Built target BroadcastHandlerTest
Linking CXX executable bin/BroadcastPoolTest
[ 91%] Built target BroadcastPoolTest
make: *** [all] Error 2

**Comment by viswanathgs** [comment]
I'm not able to repro this. What's your platform? Could you paste more info from the build logs?

**Comment by akashtalole** [comment]
I build this on Ubuntu 14.04

**Comment by akashtalole** [comment]
Build Successfully
