### ISSUE TITLE
Error building CurlClient

### ISSUE THREAD

**Issue by shivamsingh262** [facebook/proxygen#80]
I am trying to create a HTTPClient, but get a error building CurlClient provided in samples.

shivam@shivam-PC:~/proxygen/proxygen/httpclient/samples/curl$ g++ -std=c++11 -o my_echo CurlClient.cpp CurlClientMain.cpp -lproxygenhttpserver -lfolly -lglog -lgflags -pthread
/tmp/cc4U1LxS.o: In function `CurlService::CurlClient::connectSuccess(proxygen::HTTPUpstreamSession*)':
CurlClient.cpp:(.text+0x6cc): undefined reference to `proxygen::HTTPUpstreamSession::newTransaction(proxygen::HTTPTransactionHandler*)'
/tmp/cc7ZOsgn.o: In function `main':
CurlClientMain.cpp:(.text+0x41e): undefined reference to `proxygen::HTTPConnector::HTTPConnector(proxygen::HTTPConnector::Callback*, folly::HHWheelTimer*)'
CurlClientMain.cpp:(.text+0x5b4): undefined reference to `proxygen::HTTPConnector::connectSSL(folly::EventBase*, folly::SocketAddress const&, std::shared_ptr<folly::SSLContext> const&, ssl_session_st*, std::chrono::duration<long, std::ratio<1l, 1000l> >, std::map<folly::AsyncSocket::OptionKey, int, std::less<folly::AsyncSocket::OptionKey>, std::allocator<std::pair<folly::AsyncSocket::OptionKey const, int> > > const&, folly::SocketAddress const&, std::string const&)'
CurlClientMain.cpp:(.text+0x60e): undefined reference to `proxygen::HTTPConnector::connect(folly::EventBase*, folly::SocketAddress const&, std::chrono::duration<long, std::ratio<1l, 1000l> >, std::map<folly::AsyncSocket::OptionKey, int, std::less<folly::AsyncSocket::OptionKey>, std::allocator<std::pair<folly::AsyncSocket::OptionKey const, int> > > const&, folly::SocketAddress const&)'
CurlClientMain.cpp:(.text+0x631): undefined reference to `proxygen::HTTPConnector::~HTTPConnector()'
CurlClientMain.cpp:(.text+0x842): undefined reference to `proxygen::HTTPConnector::~HTTPConnector()'
collect2: error: ld returned 1 exit status

**Comment by w-o-o** [comment]
this is a link error.  did you try the make file under proxygen/proxygen/httpclient/samples/curl

**Comment by shivamsingh262** [comment]
I tried make file 

shivam@shivam-PC:~/Documents/proxygen/proxygen/httpclient/samples/curl$ make
Making all in .
make[1]: Entering directory `/home/shivam/Documents/proxygen/proxygen/httpclient/samples/curl'
make[1]: Nothing to be done for `all-am'.
make[1]: Leaving directory `/home/shivam/Documents/proxygen/proxygen/httpclient/samples/curl'

I even did 'make clean' followed by 'make'

shivam@shivam-PC:~/Documents/proxygen/proxygen/httpclient/samples/curl$ make
Making all in .
make[1]: Entering directory `/home/shivam/Documents/proxygen/proxygen/httpclient/samples/curl'
depbase=`echo CurlClient.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
        g++ -DHAVE_CONFIG_H   -I../../../.. -I../../../lib/test/gmock-1.7.0/include -I../../../lib/test/gmock-1.7.0/gtest/include  -I/usr/include   -DLIBMC_FBTRACE_DISABLE  -Wno-missing-field-initializers -Wno-deprecated -O3 -g -W -Wall -Wextra -Wno-unused-parameter -fno-strict-aliasing -std=gnu++0x -g -O2 -MT CurlClient.o -MD -MP -MF $depbase.Tpo -c -o CurlClient.o CurlClient.cpp &&\
        mv -f $depbase.Tpo $depbase.Po
depbase=`echo CurlClientMain.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
        g++ -DHAVE_CONFIG_H   -I../../../.. -I../../../lib/test/gmock-1.7.0/include -I../../../lib/test/gmock-1.7.0/gtest/include  -I/usr/include   -DLIBMC_FBTRACE_DISABLE  -Wno-missing-field-initializers -Wno-deprecated -O3 -g -W -Wall -Wextra -Wno-unused-parameter -fno-strict-aliasing -std=gnu++0x -g -O2 -MT CurlClientMain.o -MD -MP -MF $depbase.Tpo -c -o CurlClientMain.o CurlClientMain.cpp &&\
        mv -f $depbase.Tpo $depbase.Po
/bin/bash ../../../libtool  --tag=CXX   --mode=link g++  -DLIBMC_FBTRACE_DISABLE  -Wno-missing-field-initializers -Wno-deprecated -O3 -g -W -Wall -Wextra -Wno-unused-parameter -fno-strict-aliasing -std=gnu++0x -g -O2   -o curl CurlClient.o CurlClientMain.o ../../../lib/libproxygenlib.la -lwangle -lfolly -lz -lssl -lcrypto -lcap -levent -lgflags -lglog  -L/usr/lib64 -lpthread -pthread -lfolly -lglog -ldouble-conversion -lboost_system -lboost_thread
libtool: link: g++ -DLIBMC_FBTRACE_DISABLE -Wno-missing-field-initializers -Wno-deprecated -O3 -g -W -Wall -Wextra -Wno-unused-parameter -fno-strict-aliasing -std=gnu++0x -g -O2 -o curl CurlClient.o CurlClientMain.o -pthread  ../../../lib/.libs/libproxygenlib.a -L/usr/lib64 /usr/local/lib/libfolly.so -lboost_context -lboost_program_options -lboost_filesystem -lboost_regex -lboost_chrono -llzma -lsnappy -llz4 -liberty -ljemalloc -lwangle -lz -lssl -lcrypto -lcap -levent -lgflags -lpthread -lfolly -lglog -ldouble-conversion -lboost_system -lboost_thread -pthread
make[1]: Leaving directory `/home/shivam/Documents/proxygen/proxygen/httpclient/samples/curl'

But I still have the same issue.

**Comment by shivamsingh262** [comment]
I was able to resolve this by copying 'HTTPConnector.o' from  /lib/http/ directory and 'HTTPUpstreamSession.o' from /lib/http/session/ directory into the /httpclient/samples/curl directory.

Now when I run,

shivam@shivam-PC:~/proxygen/proxygen/httpclient/samples/curl$ g++ -std=c++11 -o my_echo CurlClient.cpp CurlClientMain.cpp HTTPUpstreamSession.o HTTPConnector.o -lproxygenhttpserver -lfolly -lglog -lgflags -pthread

This fixes the linker error, and the client works. There should be a better way though.
