### ISSUE TITLE
void HTTPSession::scheduleWrite() does not run in EventBaseThread

### ISSUE THREAD

**Issue by senior7515** [facebook/proxygen#88]
Hello, 

I'm getting an error w/ the HTTPSession. 

#Problem Setup:

1. Start a simple http server w/ say an artificially high number of threads 30 or whatever. 
2. Don't respond to http callbacks for a while.. i.e:

```cpp

//wait for a while
proxygen::ResponseBuilder(downstream_).status(200, "OK).sendEOM();

```

# Expected output: 

None, I just didn't expect the EventBase to crash. 

# Source of the problem 

```cpp

void
HTTPSession::scheduleWrite() {
  // Do all the network writes for this connection in one batch at
  // the end of the current event loop iteration.  Writing in a
  // batch helps us packetize the network traffic more efficiently,
  // as well as saving a few system calls.
  if (!isLoopCallbackScheduled() &&
      (writeBuf_.front() || !txnEgressQueue_.empty())) {
    VLOG(5) << *this << " scheduling write callback";
    sock_->getEventBase()->runInLoop(this);
  }
}

```

# eventBase->runInLoop(this)

does this:

```cpp


void EventBase::runInLoop(LoopCallback* callback, bool thisIteration) {
  DCHECK(isInEventBaseThread());
  callback->cancelLoopCallback();
  callback->context_ = RequestContext::saveContext();
  if (runOnceCallbacks_ != nullptr && thisIteration) {
    runOnceCallbacks_->push_back(*callback);
  } else {
    loopCallbacks_.push_back(*callback);
  }
}

```

So the issue would be simply fix by 

```cpp
auto eb = sock_->getEventBase();
eb->runInEventBase([this, ](){ 
    eb->runInLoop(this);
});

```

Any thoughts? Happy to make the PR.

**Comment by afrind** [comment]
That sounds really bizarre - how did the HTTPSession get referenced outside the thread where the sock was created and has its event base?   Did your handler try to reply to the request in a different thread than the one calling onHeaders/onEOM?  If so, this is not supported.  You need to runInEventBaseThread to get back to the thread where the socket is before you can use ResponseBuilder, et al.  If you aren't changing threads in your handler it sounds like something else we should investigate.  Can you post your handler code so I can try to repro internally?

**Comment by senior7515** [comment]
@afrind  Sure, basically I was extending the HTTPClient to have a few callbacks, etc. and I've enqueued it in the eventBaseThread();. 


1. The handler: 

https://gist.github.com/d336223975e4862802aa


2. HTTPClient.hpp (was thinking of contributing something like this to the main repo)

https://gist.github.com/4feef684319dc3177814

3. HTTPClient.cc 

https://gist.github.com/fd74e21886d0504cc3aa

**Comment by senior7515** [comment]
@afrind  Note this doesn't happen w/ a --threads=1 . It's when I increase the thread count. 

The eventbase passed to the handler, is the one given to the HandlerFactory, i retain a non owning copy of it.

**Comment by afrind** [comment]
Can I also get a paste of the stack trace when it crashes?

**Comment by senior7515** [comment]
```cpp
I0324 11:15:17.729948 12641 HTTPClient.cc:147] HTTPClient::connectSuccess(HTTPUpstreamSession *session)
I0324 11:15:17.729981 12641 HTTPClient.cc:198] HTTPClient::setTransaction(proxygen::HTTPTransaction *)
I0324 11:15:17.730173 12641 HTTPClient.cc:208] HTTPClient::onHeadersComplete(std::unique_ptr<HTTPMessage>)
I0324 11:15:17.730188 12641 HTTPClient.cc:211] HTTPClient::onHeadersComplete()=Date: Thu, 24 Mar 2016 15:15:17 GMT
I0324 11:15:17.730193 12641 HTTPClient.cc:211] HTTPClient::onHeadersComplete()=Content-Length: 0
I0324 11:15:17.730200 12641 HTTPClient.cc:211] HTTPClient::onHeadersComplete()=Content-Type: text/plain; charset=utf-8
I0324 11:15:17.730204 12641 HTTPClient.cc:211] HTTPClient::onHeadersComplete()=Connection: close
I0324 11:15:17.730212 12641 HTTPClient.cc:228] HTTPClient::onEOM()
I0324 11:15:17.730221 12641 HTTPClient.cc:202] HTTPClient::detachTransaction()
I0324 11:15:17.730228 12641 HTTPClient.cc:28] calling callback
I0324 11:15:17.730245 12641 HTTPClient.cc:51] Deleting httpclient
F0324 11:15:17.730316 12641 EventBase.cpp:494] Check failed: isInEventBaseThread() 
*** Check failure stack trace: ***
    @     0x7ffa63e1cddd  google::LogMessage::Fail()
    @     0x7ffa63e1ec90  google::LogMessage::SendToLog()
    @     0x7ffa63e1c9a2  google::LogMessage::Flush()
    @     0x7ffa63e1f68e  google::LogMessageFatal::~LogMessageFatal()
    @           0x56a471  folly::EventBase::runInLoop()
    @           0x453cb7  proxygen::HTTPSession::scheduleWrite()
    @           0x45552b  proxygen::HTTPSession::sendHeaders()
    @           0x468855  proxygen::HTTPTransaction::sendHeaders()
    @           0x418963  proxygen::ResponseBuilder::send()
    @           0x41c7cc  concord::PrincipalForwardRequestHandler::callback::success()
    @           0x422600  _ZZN7concord10HTTPClientD4EvENUlvE_clEv
    @           0x56a995  folly::EventBase::runLoopCallbacks()
    @           0x56af98  folly::EventBase::loopBody()
    @           0x56c784  folly::EventBase::loopForever()
    @           0x4f08ef  wangle::IOThreadPoolExecutor::threadRun()
    @           0x501949  _ZNKSt12_Mem_fn_baseIMN6wangle18ThreadPoolExecutorEFvSt10shared_ptrINS1_6ThreadEEELb1EEclIJRS4_EvEEvPS1_DpOT_
    @           0x4fffc7  _ZNSt5_BindIFSt7_Mem_fnIMN6wangle18ThreadPoolExecutorEFvSt10shared_ptrINS2_6ThreadEEEEPS2_S5_EE6__callIvJEJLm0ELm1EEEET_OSt5tupleIJDpT0_EESt12_Index_tupleIJXspT1_EEE
    @           0x4fd97a  _ZNSt5_BindIFSt7_Mem_fnIMN6wangle18ThreadPoolExecutorEFvSt10shared_ptrINS2_6ThreadEEEEPS2_S5_EEclIJEvEET0_DpOT_
    @           0x4fb51d  std::_Function_handler<>::_M_invoke()
    @     0x7ffa63476390  (unknown)
    @     0x7ffa64b59182  start_thread
    @     0x7ffa62f0747d  (unknown)
    @              (nil)  (unknown)
Aborted (core dumped)

```

**Comment by senior7515** [comment]
@afrind it's the same thread id: ` 12641 `

**Comment by afrind** [comment]
Ah, the EVB passed to the handler factory is the thread that does TCP accept, but is *not* necessarily the thread that your handler is invoked in (this is only the case when threads=1.  For threads > 1, after accept the new connection is load balanced to an I/O thread).  You need to find your current eventBase in onRequest().  You can use EventBaseManager for this.

**Comment by afrind** [comment]
It’s in the same thread that the client is working in, which is the one you saved in your RequestHandler, which came from the factory.  The server handler is running in a different thread.

**Comment by senior7515** [comment]
@afrind ah, thanks! well can you help me understand the iothreadpool then. 

I tried just doing 
```cpp

      return new PrincipalForwardRequestHandler(
        folly::EventBaseManager::get()->getEventBase(), timer_.get());
```

But then it errs on saying that the session->newTransaction(this) (httpclient)  - same as sample code is not in the eventbaseThread. 

Here is the stack trace:

```cpp

concord_proxy: io/async/EventBase.cpp:764: virtual bool folly::EventBase::scheduleTimeout(folly::AsyncTimeout*, folly::TimeoutManager::timeout_type): Assertion `isInEventBaseThread()' failed.
*** Aborted at 1458858262 (unix time) try "date -d @1458858262" if you are using GNU date ***
PC: @     0x7fce2954bcc9 (unknown)
*** SIGABRT (@0x3e800001485) received by PID 5253 (TID 0x7fce267ff700) from PID 5253; stack trace: ***
    @     0x7fce2b269340 (unknown)
    @     0x7fce2954bcc9 (unknown)
    @     0x7fce2954f0d8 (unknown)
    @     0x7fce29544b86 (unknown)
    @     0x7fce29544c32 (unknown)
    @           0x569460 folly::EventBase::scheduleTimeout()
    @           0x54756b folly::AsyncTimeout::scheduleTimeout()
    @           0x57f3be folly::HHWheelTimer::scheduleTimeout()
    @           0x57f49c folly::HHWheelTimer::scheduleTimeout()
    @           0x46affa proxygen::HTTPTransaction::HTTPTransaction()
    @           0x4636b0 _ZNSt8_Rb_treeIjSt4pairIKjN8proxygen15HTTPTransactionEESt10_Select1stIS4_ESt4lessIjESaIS4_EE17_M_emplace_uniqueIJRKSt21piecewise_construct_tSt5tupleIJRjEESF_IJONS2_18TransportDirectionESG_SG_RNS2_11HTTPSessionERNS2_18HTTP2PriorityQueueEOPN5folly12HHWheelTimerERPNS2_16HTTPSessionStatsEObRmOmRNS2_5http214PriorityUpdateESG_EEEEES0_ISt17_Rb_tree_iteratorIS4_EbEDpOT_
    @           0x460ce3 proxygen::HTTPSession::createTransaction()
    @           0x472c93 proxygen::HTTPUpstreamSession::newTransaction()
    @           0x425043 concord::HTTPClient::connectSuccess()
    @           0x4432d7 proxygen::HTTPConnector::connectSuccess()
    @           0x557441 folly::AsyncSocket::handleConnect()
    @           0x558e05 folly::AsyncSocket::handleWrite()
    @           0x553bca folly::AsyncSocket::ioReady()
    @     0x7fce2abd5f24 (unknown)
    @           0x56af28 folly::EventBase::loopBody()
    @           0x56c724 folly::EventBase::loopForever()
    @           0x4f088f wangle::IOThreadPoolExecutor::threadRun()
    @           0x5018e9 _ZNKSt12_Mem_fn_baseIMN6wangle18ThreadPoolExecutorEFvSt10shared_ptrINS1_6ThreadEEELb1EEclIJRS4_EvEEvPS1_DpOT_
    @           0x4fff67 _ZNSt5_BindIFSt7_Mem_fnIMN6wangle18ThreadPoolExecutorEFvSt10shared_ptrINS2_6ThreadEEEEPS2_S5_EE6__callIvJEJLm0ELm1EEEET_OSt5tupleIJDpT0_EESt12_Index_tupleIJXspT1_EEE
    @           0x4fd91a _ZNSt5_BindIFSt7_Mem_fnIMN6wangle18ThreadPoolExecutorEFvSt10shared_ptrINS2_6ThreadEEEEPS2_S5_EEclIJEvEET0_DpOT_
    @           0x4fb4bd std::_Function_handler<>::_M_invoke()
    @     0x7fce29b7e390 (unknown)
    @     0x7fce2b261182 start_thread
    @     0x7fce2960f47d (unknown)
    @                0x0 (unknown)
Aborted (core dumped)

```


I guess what's the guiding principle then. 

It looks as though the event base is what the HTTPServer uses, but the docs on async say that you should not use the evertbasemanager::get()->geteventbase() and expect things to work. 

trying to understand the design and more specifically how to reason about the eventbase threading model here. 

Thanks!

**Comment by afrind** [comment]
Same deal with the wheel timer.  It belongs to the accept thread.  If you want to send a PR, maybe add HTTPRequestHandlerFactory::onRequest(handler, msg, evb, wheeltimer), where the default impl just throws away evb and wheel timer and calls onRequest for backward compatibility.  Then you can override that.  What I don’t like is that leaves the old onRequest as a must implement in the factory but it won’t ever be called.  Another option is to add a method to HTTPRequestHandlerFactory like attachEventBase(evb, wheelTimer) which would get called immediately after your handler is created in HTTPServerAcceptor::newHandler.

**Comment by senior7515** [comment]
@afrind Got it. To distilled your thoughts, I have a local patch that implements this. 

# RequestHandlerFactory
```cpp

class RequestHandlerFactory {
 public:
  virtual ~RequestHandlerFactory() {}

  /**
   * Invoked in each thread server is going to handle requests
   * before we start handling requests. Can be used to setup
   * thread-local setup for each thread (stats and such).
   */
  virtual void onServerStart(folly::EventBase* evb) noexcept = 0;

  /**
   * Invoked in each handler thread after all the connections are
   * drained from that thread. Can be used to tear down thread-local setup.
   */
  virtual void onServerStop() noexcept = 0;

  __attribute__ ((deprecated))
  virtual RequestHandler* onRequest(RequestHandler*, HTTPMessage*) noexcept {}

  /**
   * Invoked for each new request server handles. HTTPMessage is provided
   * so that user can potentially choose among several implementation of
   * handler based on URL or something. No, need to save/copy this
   * HTTPMessage. RequestHandler will be given the HTTPMessage
   * in a separate callback.
   *
   * Some request handlers don't handle the request themselves (think filters).
   * They do take some actions based on request/response but otherwise they
   * just hand-off request to some other RequestHandler. This upstream
   * RequestHandler is given as first parameter. For the terminal RequestHandler
   * this will by nullptr.
   *
   * If you plan on not responding on RequestHandler::onEOM and delay the
   * response, then you should hold onto the EventBase ptr and call
   * proxygen::ResponseBuilder(downstream_) et all on the event base
   * thread passed to this method. i.e.: ` evb_->runInEventBaseThread `
   *
   * Similarly, the HHWeheelTimer in order to fire the timers, it must
   * be attached to the ` accept ` EventBase. So, please keep a non-owning
   * pointer.
   *
   * These extensions are useful for adding an HTTPClient for example.
   *
   */
  virtual RequestHandler* onRequest(RequestHandler* h, HTTPMessage* msg,
                                    EventBase*, folly::HHWheelTimer*) noexcept {
    onRequest(h,msg);
  }
};
```

# HTTPServer.h

```cpp


...
  /**
   * Event base in which we binded server sockets.
   */
  folly::EventBase* mainEventBase_{nullptr};

  /**
   * HHWheelTimer attached to the mainEventBase_;
   */
  folly::HHWheelTimer::UniquePtr timer_{nullptr};

```

# Remaining problem:

Effectively you need to pass a pair of EventBase* . One is the ioThread that is handling this RequestHandler* and the other is where the handler IO load balanced EventBase* uses for it's responses. 

i.e. : ` proxygen::ResponseBuilder(downstream_).. ` et al. 


# Thoughts on the internal HTTPClient. 


Can you comment on the design of the internal HTTPClient? 

What I've been able to figure out is that:

* You need access to the acceptor HHWheelTimer*  for the folly::AsyncSocket stuff. Effectively
when you call the `HTTPConnector::connect(mainThreadEventBase_*, mainThreadHHWheelTimer_*... `
* Then there is the IOThread that uses it's **own** EventBase thread to respond to clients. 

The superficial problem seems to be that the `folly::EventBaseManager::get()->getEventBase() ` might not be looping, so if you schedule calls they might never run. At least this looks like a leaky abstraction to use on my own httpclient. 

To be clear. The `folly::EventBaseManager::get()->getEventBase() ` is what one needs to use to build the response. 

Thank you. I'm happy to make the changes and continue to make the changes. 

Almost there! 

- Alex

**Comment by senior7515** [comment]
@afrind So in the mean time, I'll keep making the PR. but I worked around it by having a pair of eventbases

```cpp

      return new PrincipalForwardRequestHandler(
        folly::EventBaseManager::get()->getEventBase(), mainEventBaseThread_,
        timer_.get());
```

The main one is for the ` ResponseBuilder() -> eventmanager::get().. ` and the other is for making sockets on the client, etc.

Thanks.

**Comment by senior7515** [comment]
In retrospect, what do you think of having a context object passed around. It ha a few critical ptr's. 

1. The mainEventBase_
2. The EventBaseManager::get()->getEventBase() 
3. The HHWheelTimer* attached to the mainEventBase_

**Comment by afrind** [comment]
I can't really think of a case where you need the accept thread's wheel timer.  You can always schedule the timeout in your thread, then runInEventBaseThread back to the accept thread if you really need to run something there, but you shouldn't need to.  Basically you should just ignore the main thread event base and timer as much as you can.  You *do* need the i/o thread's timer so you can schedule timeouts in the current thread.  Putting a context object into onRequest will make it easier to extend later, so I think I do like that.

Regarding the HTTPClient design, it's pretty reasonable.  I do favor allowing the response body to be streamed to the callback rather than buffered in the client.  If you are thinking about using this as part of a proxy, you probably want to plumb the egress pause/resume callbacks on one end to pausing ingress on the other side, lest you end up with a proxy that has to buffer everything.  If you put up a PR for it we'll give it a formal review.

**Comment by senior7515** [comment]
@afrind  awesome!! ok will put something together.

**Comment by tedyu** [comment]
When would the context object be added as parameter ?
