### ISSUE TITLE
CMake!

### ISSUE THREAD

**Issue by ixtli** [facebook/proxygen#9]
I'm really interested in this project for some personal stuff I'm doing, but I think it would make the project more accessible if it used CMake instead of interfacing directly with Autotools. You might also leverage some free portability, too, as CMake emits VS and XCode projects, all from one configuration.

**Comment by trygvis** [comment]
+1

**Comment by octohydra** [comment]
:+1:

**Comment by abhiguru** [comment]
CMake does not support convenience libs so all the libs get fragmented unless we consider one of the libs as a part of the main source... anywho if anyone is interested I have /libs working with cmake (install has to be manually)  https://github.com/abhiguru/proxygen/commit/cf7ad1e303db3d3660dbf457d22f9757b5b65d46
