### ISSUE TITLE
Bug in curl sample

### ISSUE THREAD

**Issue by rcgoodfellow** [facebook/proxygen#91]
First of thank you for the wonderful library!

In the curl example, the code [here](https://github.com/facebook/proxygen/blob/master/proxygen/httpclient/samples/curl/CurlClient.cpp#L147) seems to miss the last IOBuf in the chain if there is more than 1. Shouldn't the correct logic be the following?

```c++
while (p != chain.get())
```

**Comment by wkoszek** [comment]
@rcgoodfellow Looks like this issue can be closed?

**Comment by afrind** [comment]
Fix has shipped.
