### ISSUE TITLE
Does proxygen support Windows ?

### ISSUE THREAD

**Issue by pengweichu** [facebook/proxygen#93]
Hello, does proxygen is support Windows ?

**Comment by afrind** [comment]
It doesn't currently work on Windows, but it will eventually be supported for HHVM. We have people working on this internally now.  Even once support is added, using Proxygen on Windows will be experimental for quite a while, as the sockets portability layer we are working on is far from perfect right now.

**Comment by DemiMarie** [comment]
Do you plan on using I/O Completion Ports or just falling back to the slow `select()` API?

**Comment by Orvid** [comment]
Proxygen uses Folly's event loop, which uses libevent, which in turn uses select, so unfortunately, yes, it will be using `select` rather than completion ports.

**Comment by michaelpog** [comment]
I just wanted to confirm. Folly uses libevent with select only on Windows? Or both Windows and Linux?
I would assume on Linux using epoll would be more efficient.

**Comment by Orvid** [comment]
Linux uses epoll.

**Comment by patlecat** [comment]
I would appreciate if Proxygen was at least soon usable under Windows if only for development and testing purposes. It doesn't have to be very fast or efficient, but just to be compilable with GCC, CLang and MSVC at least.

**Comment by vinniefalco** [comment]
@patlecat Try this https://github.com/vinniefalco/Beast/

**Comment by MarkoPapic** [comment]
> I would appreciate if Proxygen was at least soon usable under Windows if only for development and testing purposes. It doesn't have to be very fast or efficient, but just to be compilable with GCC, CLang and MSVC at least.

+1 on this. I am planning on deploying it to Linux anyway, but would like to have an option of developing and debugging on Windows machines using Visual Studio.

**Comment by lnicco** [comment]
we haven't prioritized this but there is no reason it shouldn't just build (other projects like mvfst build just fine on windows https://github.com/facebookincubator/mvfst)
Could you please post here the exact error you are getting?

**Comment by afrind** [comment]
Closing for now, please open a new issue with any windows specific problems.
