### ISSUE TITLE
Armhf ?(Embedded Platform)

### ISSUE THREAD

**Issue by raaka1** [facebook/proxygen#95]
I am trying to compile on 

```
 ubuntu 3.10.67-g458d45c #1 SMP PREEMPT Mon Feb 8 17:44:18 PST 2016 aarch64 aarch64 
 aarch64 GNU/Linux
```

i have received following error 

```
 checking for boostlib >= 1.51.0... yes
 checking whether the Boost::Context library is available... yes
configure: error: Could not find a version of the library!

```
My version has this 32:0

any suggestions or work arounds ?

**Comment by afrind** [comment]
First the version tags aren't being updated since we moved to continuous push.  As long as you are on the git HEAD you should be good. Looks like you need to update or install the boost library?

**Comment by raaka1** [comment]
I have tried to install boost dev libraries no luck.

**Comment by afrind** [comment]
Hmm, without your specific platform here, I'm afraid there's not much I can suggest.  Maybe uninstall and re-install boost?  Is boost in some unexpected location?  There's usually a config.log file which shows the exact commands being run and perhaps more detail on the errors.

**Comment by wkoszek** [comment]
@afrind @raaka1 It would actually be interesting to learn what platform is that.

**Comment by raaka1** [comment]
[Nvidia Jetson TK1 ](http://www.nvidia.com/object/jetson-tk1-embedded-dev-kit.html)

**Comment by afrind** [comment]
Going to close this out for now.  If you are still blocked on this - try posting in the group: https://groups.google.com/forum/#!forum/facebook-proxygen and maybe another user there can help?  Be sure to include the relevant output from config.log
