### ISSUE TITLE
`sudo: command not found` When building Docker image

### ISSUE THREAD

**Issue by mrmoje** [facebook/proxygen#96]
looks like sudo is missing from the base ubuntu image causing docker build fails at `RUN ./deps.sh && ./reinstall.sh` https://github.com/facebook/proxygen/blob/7fa73304/Dockerfile#L25

**Comment by russoue** [comment]
Thanks for the PR, will take a look at it soon.

**Comment by kristianonline** [comment]
@russoue I tried to run it also in docker today. The solution is quite simple: Add 'sudo' to the list where flex, bison, ..., wget is listed.

**Comment by jitendrabhalothia** [comment]
Add this step while building the docker file as a root and install apt-get install sudo
